/*
 * xHarbour build 0.99.70 Intl. (SimpLex)
 * Generated C source code from <ATU_SMED.PRG>
 * Command: C:\xHarbour997\bin\harbour.exe C:\HTI\SISMED\ATU_SMED.PRG /q /oC:\HTI\SISMED\ATU_SMED.c /M /N -DxHB -DXHB_0990 -DXHB_0991 -DXHB_0992 -DXHB_0993 -DXHB_0994 -DXHB_09941 -DXHB_09950 -DXHB_09951a -DXHB_09951 -DXHB_09951b -DXHB_0996 -DXHB_09960 -DXHB_09961 -DXHB_09961B -DXHB_0997 -DXHB_09970 
 * Created: 2023.06.14 08:58:28 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "ATU_SMED.PRG"

HB_FUNC( ATU_SMED );
HB_FUNC_EXTERN( __MVPRIVATE );
HB_FUNC_EXTERN( SAVESCREEN );
HB_FUNC_EXTERN( REPLICATE );
HB_FUNC_EXTERN( SPACE );
HB_FUNC_EXTERN( DBCLOSEALL );
HB_FUNC_EXTERN( DBSELECTAREA );
HB_FUNC_EXTERN( __SETFORMAT );
HB_FUNC_EXTERN( DBUSEAREA );
HB_FUNC_EXTERN( ORDLISTCLEAR );
HB_FUNC_EXTERN( ORDLISTADD );
HB_FUNC_EXTERN( ORDSETFOCUS );
HB_FUNC_EXTERN( DBGOTOP );
HB_FUNC_EXTERN( BLOQARQ );
HB_FUNC_EXTERN( EOF );
HB_FUNC_EXTERN( DEVPOS );
HB_FUNC_EXTERN( DEVOUT );
HB_FUNC_EXTERN( RECNO );
HB_FUNC_EXTERN( MLCOUNT );
HB_FUNC_EXTERN( MEMOLINE );
HB_FUNC_EXTERN( ADIREG );
HB_FUNC_EXTERN( DATE );
HB_FUNC_EXTERN( DBCOMMITALL );
HB_FUNC_EXTERN( DBUNLOCKALL );
HB_FUNC_EXTERN( DBSKIP );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 7

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_ATU_SMED )
{ "ATU_SMED", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( ATU_SMED )}, NULL },
{ "MTRACO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTIPO_IMP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__MVPRIVATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVPRIVATE )}, NULL },
{ "SAVESCREEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAVESCREEN )}, NULL },
{ "REPLICATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( REPLICATE )}, NULL },
{ "SPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPACE )}, NULL },
{ "DBCLOSEALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCLOSEALL )}, NULL },
{ "DBSELECTAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSELECTAREA )}, NULL },
{ "__SETFORMAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( __SETFORMAT )}, NULL },
{ "DBUSEAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBUSEAREA )}, NULL },
{ "ORDLISTCLEAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( ORDLISTCLEAR )}, NULL },
{ "ORDLISTADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( ORDLISTADD )}, NULL },
{ "ORDSETFOCUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ORDSETFOCUS )}, NULL },
{ "DBGOTOP", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBGOTOP )}, NULL },
{ "BLOQARQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( BLOQARQ )}, NULL },
{ "EOF", {HB_FS_PUBLIC}, {HB_FUNCNAME( EOF )}, NULL },
{ "DEVPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVPOS )}, NULL },
{ "DEVOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUT )}, NULL },
{ "RECNO", {HB_FS_PUBLIC}, {HB_FUNCNAME( RECNO )}, NULL },
{ "MLCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MLCOUNT )}, NULL },
{ "CLI", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "HISTORICO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MEMOLINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( MEMOLINE )}, NULL },
{ "ADIREG", {HB_FS_PUBLIC}, {HB_FUNCNAME( ADIREG )}, NULL },
{ "DATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DATE )}, NULL },
{ "HIST", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "DATA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "REGISTRO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CODCLI", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DESCRICAO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PROBINDEN", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "EXAM", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "DIAGNOSTIC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DIAG", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "PRESC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "COND", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "DBCOMMITALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCOMMITALL )}, NULL },
{ "DBUNLOCKALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBUNLOCKALL )}, NULL },
{ "DBSKIP", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSKIP )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_ATU_SMED )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_ATU_SMED
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_ATU_SMED = hb_vm_SymbolInit_ATU_SMED;
   #pragma data_seg()
#endif

HB_FUNC( ATU_SMED )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 14, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 9, 0,	/* 9 */
	HB_P_PUSHSYMNEAR, 3,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 1,	/* MTRACO */
	HB_P_PUSHSYMNEAR, 2,	/* MTIPO_IMP */
	HB_P_DOSHORT, 2,
/* 00015 */ HB_P_LINEOFFSET, 2,	/* 11 */
	HB_P_LOCALNEARSETINT, 1, 3, 0,	/* LCI 3*/
/* 00021 */ HB_P_LINEOFFSET, 3,	/* 12 */
	HB_P_LOCALNEARSETINT, 2, 4, 0,	/* CCI 4*/
/* 00027 */ HB_P_LINEOFFSET, 4,	/* 13 */
	HB_P_LOCALNEARSETINT, 3, 21, 0,	/* LBA 21*/
/* 00033 */ HB_P_LINEOFFSET, 5,	/* 14 */
	HB_P_LOCALNEARSETINT, 4, 76, 0,	/* CBA 76*/
/* 00039 */ HB_P_LINEOFFSET, 6,	/* 15 */
	HB_P_PUSHSYMNEAR, 4,	/* SAVESCREEN */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 6,	/* TELA570 */
/* 00054 */ HB_P_LINEOFFSET, 7,	/* 16 */
	HB_P_PUSHSYMNEAR, 5,	/* REPLICATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'=', 0, 
	HB_P_PUSHBYTE, 80,	/* 80 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 1, 0,	/* MTRACO */
/* 00070 */ HB_P_LINEOFFSET, 8,	/* 17 */
	HB_P_PUSHSYMNEAR, 6,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 5,	/* OPCAO */
/* 00080 */ HB_P_LINEOFFSET, 10,	/* 19 */
	HB_P_PUSHSYMNEAR, 7,	/* DBCLOSEALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_PUSHSYMNEAR, 8,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'1', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 9,	/* __SETFORMAT */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 1,
/* 00102 */ HB_P_LINEOFFSET, 11,	/* 20 */
	HB_P_PUSHSYMNEAR, 10,	/* DBUSEAREA */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	's', 'm', 'e', 'd', 'c', 'l', 'i', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'l', 'i', 0, 
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 8,
/* 00131 */ HB_P_LINEOFFSET, 12,	/* 21 */
	HB_P_PUSHSYMNEAR, 11,	/* ORDLISTCLEAR */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_PUSHSYMNEAR, 12,	/* ORDLISTADD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'c', 'a', 'd', 'n', 'o', 'm', 'e', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 12,	/* ORDLISTADD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'c', 'a', 'd', 'r', 'e', 'g', 0, 
	HB_P_DOSHORT, 1,
/* 00167 */ HB_P_LINEOFFSET, 13,	/* 22 */
	HB_P_PUSHSYMNEAR, 10,	/* DBUSEAREA */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	's', 'm', 'e', 'd', 'h', 'i', 's', 't', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'h', 'i', 's', 't', 0, 
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 8,
/* 00198 */ HB_P_LINEOFFSET, 14,	/* 23 */
	HB_P_PUSHSYMNEAR, 11,	/* ORDLISTCLEAR */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_PUSHSYMNEAR, 12,	/* ORDLISTADD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	's', 'm', 'e', 'd', 'h', 'i', 's', '1', 0, 
	HB_P_DOSHORT, 1,
/* 00221 */ HB_P_LINEOFFSET, 15,	/* 24 */
	HB_P_PUSHSYMNEAR, 10,	/* DBUSEAREA */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	's', 'm', 'e', 'd', 'e', 'x', 'a', 'm', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'e', 'x', 'a', 'm', 0, 
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 8,
/* 00252 */ HB_P_LINEOFFSET, 16,	/* 25 */
	HB_P_PUSHSYMNEAR, 11,	/* ORDLISTCLEAR */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_PUSHSYMNEAR, 12,	/* ORDLISTADD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	's', 'm', 'e', 'd', 'e', 'x', 'a', '1', 0, 
	HB_P_DOSHORT, 1,
/* 00275 */ HB_P_LINEOFFSET, 17,	/* 26 */
	HB_P_PUSHSYMNEAR, 10,	/* DBUSEAREA */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	's', 'm', 'e', 'd', 'c', 'o', 'n', 'd', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'c', 'o', 'n', 'd', 0, 
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 8,
/* 00306 */ HB_P_LINEOFFSET, 18,	/* 27 */
	HB_P_PUSHSYMNEAR, 11,	/* ORDLISTCLEAR */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_PUSHSYMNEAR, 12,	/* ORDLISTADD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	's', 'm', 'e', 'd', 'c', 'o', 'n', '1', 0, 
	HB_P_DOSHORT, 1,
/* 00329 */ HB_P_LINEOFFSET, 19,	/* 28 */
	HB_P_PUSHSYMNEAR, 10,	/* DBUSEAREA */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	's', 'm', 'e', 'd', 'd', 'i', 'a', 'g', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'd', 'i', 'a', 'g', 0, 
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 8,
/* 00360 */ HB_P_LINEOFFSET, 20,	/* 29 */
	HB_P_PUSHSYMNEAR, 11,	/* ORDLISTCLEAR */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_PUSHSYMNEAR, 12,	/* ORDLISTADD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	's', 'm', 'e', 'd', 'd', 'i', 'a', '1', 0, 
	HB_P_DOSHORT, 1,
/* 00383 */ HB_P_LINEOFFSET, 23,	/* 32 */
	HB_P_PUSHSYMNEAR, 8,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'l', 'i', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 13,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 14,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00408 */ HB_P_LINEOFFSET, 25,	/* 34 */
	HB_P_PUSHSYMNEAR, 15,	/* BLOQARQ */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00415 */ HB_P_LINEOFFSET, 26,	/* 35 */
	HB_P_PUSHSYMNEAR, 16,	/* EOF */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPTRUE, 103, 2,	/* 615 (abs: 01037) */
/* 00425 */ HB_P_LINEOFFSET, 27,	/* 36 */
	HB_P_PUSHSYMNEAR, 17,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 18,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 19,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_DOSHORT, 1,
/* 00444 */ HB_P_LINEOFFSET, 28,	/* 37 */
	HB_P_LOCALNEARSETINT, 11, 0, 0,	/* LINHAS 0*/
/* 00450 */ HB_P_LINEOFFSET, 29,	/* 38 */
	HB_P_LOCALNEARSETINT, 12, 0, 0,	/* LINHA 0*/
/* 00456 */ HB_P_LINEOFFSET, 30,	/* 39 */
	HB_P_LOCALNEARSETINT, 13, 0, 0,	/* LIN 0*/
/* 00462 */ HB_P_LINEOFFSET, 31,	/* 40 */
	HB_P_PUSHSYMNEAR, 20,	/* MLCOUNT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 21,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 22,	/* HISTORICO */
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 11,	/* LINHAS */
/* 00477 */ HB_P_LINEOFFSET, 33,	/* 42 */
	HB_P_PUSHSYMNEAR, 8,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'h', 'i', 's', 't', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 13,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00497 */ HB_P_LINEOFFSET, 35,	/* 44 */
	HB_P_PUSHLOCALNEAR, 11,	/* LINHAS */
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 78,	/* 78 (abs: 00581) */
/* 00505 */ HB_P_LINEOFFSET, 36,	/* 45 */
	HB_P_LOCALNEARSETINT, 12, 1, 0,	/* LINHA 1*/
	HB_P_PUSHLOCALNEAR, 12,	/* LINHA */
	HB_P_PUSHLOCALNEAR, 11,	/* LINHAS */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 65,	/* 65 (abs: 00581) */
/* 00518 */ HB_P_LINEOFFSET, 37,	/* 46 */
	HB_P_PUSHSYMNEAR, 23,	/* MEMOLINE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 21,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 22,	/* HISTORICO */
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_PUSHLOCALNEAR, 12,	/* LINHA */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 13,	/* LIN */
/* 00537 */ HB_P_LINEOFFSET, 38,	/* 47 */
	HB_P_PUSHSYMNEAR, 24,	/* ADIREG */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00544 */ HB_P_LINEOFFSET, 39,	/* 48 */
	HB_P_PUSHSYMNEAR, 25,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 26,	/* HIST */
	HB_P_POPALIASEDFIELDNEAR, 27,	/* DATA */
/* 00555 */ HB_P_LINEOFFSET, 40,	/* 49 */
	HB_P_PUSHSYMNEAR, 21,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 28,	/* REGISTRO */
	HB_P_PUSHSYMNEAR, 26,	/* HIST */
	HB_P_POPALIASEDFIELDNEAR, 29,	/* CODCLI */
/* 00565 */ HB_P_LINEOFFSET, 41,	/* 50 */
	HB_P_PUSHLOCALNEAR, 13,	/* LIN */
	HB_P_PUSHSYMNEAR, 26,	/* HIST */
	HB_P_POPALIASEDFIELDNEAR, 30,	/* DESCRICAO */
/* 00573 */ HB_P_LINEOFFSET, 42,	/* 51 */
	HB_P_LOCALNEARADDINT, 12, 1, 0,	/* LINHA 1*/
	HB_P_JUMPNEAR, 188,	/* -68 (abs: 00511) */
/* 00581 */ HB_P_LINEOFFSET, 46,	/* 55 */
	HB_P_LOCALNEARSETINT, 11, 0, 0,	/* LINHAS 0*/
/* 00587 */ HB_P_LINEOFFSET, 47,	/* 56 */
	HB_P_LOCALNEARSETINT, 12, 0, 0,	/* LINHA 0*/
/* 00593 */ HB_P_LINEOFFSET, 48,	/* 57 */
	HB_P_LOCALNEARSETINT, 13, 0, 0,	/* LIN 0*/
/* 00599 */ HB_P_LINEOFFSET, 49,	/* 58 */
	HB_P_PUSHSYMNEAR, 20,	/* MLCOUNT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 21,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 31,	/* PROBINDEN */
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 11,	/* LINHAS */
/* 00614 */ HB_P_LINEOFFSET, 50,	/* 59 */
	HB_P_PUSHLOCALNEAR, 11,	/* LINHAS */
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 98,	/* 98 (abs: 00718) */
/* 00622 */ HB_P_LINEOFFSET, 52,	/* 61 */
	HB_P_PUSHSYMNEAR, 8,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'e', 'x', 'a', 'm', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 13,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00642 */ HB_P_LINEOFFSET, 54,	/* 63 */
	HB_P_LOCALNEARSETINT, 12, 1, 0,	/* LINHA 1*/
	HB_P_PUSHLOCALNEAR, 12,	/* LINHA */
	HB_P_PUSHLOCALNEAR, 11,	/* LINHAS */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 65,	/* 65 (abs: 00718) */
/* 00655 */ HB_P_LINEOFFSET, 55,	/* 64 */
	HB_P_PUSHSYMNEAR, 23,	/* MEMOLINE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 21,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 31,	/* PROBINDEN */
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_PUSHLOCALNEAR, 12,	/* LINHA */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 13,	/* LIN */
/* 00674 */ HB_P_LINEOFFSET, 56,	/* 65 */
	HB_P_PUSHSYMNEAR, 24,	/* ADIREG */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00681 */ HB_P_LINEOFFSET, 57,	/* 66 */
	HB_P_PUSHSYMNEAR, 25,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 32,	/* EXAM */
	HB_P_POPALIASEDFIELDNEAR, 27,	/* DATA */
/* 00692 */ HB_P_LINEOFFSET, 58,	/* 67 */
	HB_P_PUSHSYMNEAR, 21,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 28,	/* REGISTRO */
	HB_P_PUSHSYMNEAR, 32,	/* EXAM */
	HB_P_POPALIASEDFIELDNEAR, 29,	/* CODCLI */
/* 00702 */ HB_P_LINEOFFSET, 59,	/* 68 */
	HB_P_PUSHLOCALNEAR, 13,	/* LIN */
	HB_P_PUSHSYMNEAR, 32,	/* EXAM */
	HB_P_POPALIASEDFIELDNEAR, 30,	/* DESCRICAO */
/* 00710 */ HB_P_LINEOFFSET, 60,	/* 69 */
	HB_P_LOCALNEARADDINT, 12, 1, 0,	/* LINHA 1*/
	HB_P_JUMPNEAR, 188,	/* -68 (abs: 00648) */
/* 00718 */ HB_P_LINEOFFSET, 64,	/* 73 */
	HB_P_LOCALNEARSETINT, 11, 0, 0,	/* LINHAS 0*/
/* 00724 */ HB_P_LINEOFFSET, 65,	/* 74 */
	HB_P_LOCALNEARSETINT, 12, 0, 0,	/* LINHA 0*/
/* 00730 */ HB_P_LINEOFFSET, 66,	/* 75 */
	HB_P_LOCALNEARSETINT, 13, 0, 0,	/* LIN 0*/
/* 00736 */ HB_P_LINEOFFSET, 67,	/* 76 */
	HB_P_PUSHSYMNEAR, 20,	/* MLCOUNT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 21,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 33,	/* DIAGNOSTIC */
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 11,	/* LINHAS */
/* 00751 */ HB_P_LINEOFFSET, 68,	/* 77 */
	HB_P_PUSHLOCALNEAR, 11,	/* LINHAS */
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 98,	/* 98 (abs: 00855) */
/* 00759 */ HB_P_LINEOFFSET, 70,	/* 79 */
	HB_P_PUSHSYMNEAR, 8,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'd', 'i', 'a', 'g', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 13,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00779 */ HB_P_LINEOFFSET, 72,	/* 81 */
	HB_P_LOCALNEARSETINT, 12, 1, 0,	/* LINHA 1*/
	HB_P_PUSHLOCALNEAR, 12,	/* LINHA */
	HB_P_PUSHLOCALNEAR, 11,	/* LINHAS */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 65,	/* 65 (abs: 00855) */
/* 00792 */ HB_P_LINEOFFSET, 73,	/* 82 */
	HB_P_PUSHSYMNEAR, 23,	/* MEMOLINE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 21,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 33,	/* DIAGNOSTIC */
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_PUSHLOCALNEAR, 12,	/* LINHA */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 13,	/* LIN */
/* 00811 */ HB_P_LINEOFFSET, 74,	/* 83 */
	HB_P_PUSHSYMNEAR, 24,	/* ADIREG */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00818 */ HB_P_LINEOFFSET, 75,	/* 84 */
	HB_P_PUSHSYMNEAR, 25,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 34,	/* DIAG */
	HB_P_POPALIASEDFIELDNEAR, 27,	/* DATA */
/* 00829 */ HB_P_LINEOFFSET, 76,	/* 85 */
	HB_P_PUSHSYMNEAR, 21,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 28,	/* REGISTRO */
	HB_P_PUSHSYMNEAR, 34,	/* DIAG */
	HB_P_POPALIASEDFIELDNEAR, 29,	/* CODCLI */
/* 00839 */ HB_P_LINEOFFSET, 77,	/* 86 */
	HB_P_PUSHLOCALNEAR, 13,	/* LIN */
	HB_P_PUSHSYMNEAR, 34,	/* DIAG */
	HB_P_POPALIASEDFIELDNEAR, 30,	/* DESCRICAO */
/* 00847 */ HB_P_LINEOFFSET, 78,	/* 87 */
	HB_P_LOCALNEARADDINT, 12, 1, 0,	/* LINHA 1*/
	HB_P_JUMPNEAR, 188,	/* -68 (abs: 00785) */
/* 00855 */ HB_P_LINEOFFSET, 82,	/* 91 */
	HB_P_LOCALNEARSETINT, 11, 0, 0,	/* LINHAS 0*/
/* 00861 */ HB_P_LINEOFFSET, 83,	/* 92 */
	HB_P_LOCALNEARSETINT, 12, 0, 0,	/* LINHA 0*/
/* 00867 */ HB_P_LINEOFFSET, 84,	/* 93 */
	HB_P_LOCALNEARSETINT, 13, 0, 0,	/* LIN 0*/
/* 00873 */ HB_P_LINEOFFSET, 85,	/* 94 */
	HB_P_PUSHSYMNEAR, 20,	/* MLCOUNT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 21,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 35,	/* PRESC */
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 11,	/* LINHAS */
/* 00888 */ HB_P_LINEOFFSET, 86,	/* 95 */
	HB_P_PUSHLOCALNEAR, 11,	/* LINHAS */
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 98,	/* 98 (abs: 00992) */
/* 00896 */ HB_P_LINEOFFSET, 88,	/* 97 */
	HB_P_PUSHSYMNEAR, 8,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'c', 'o', 'n', 'd', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 13,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00916 */ HB_P_LINEOFFSET, 90,	/* 99 */
	HB_P_LOCALNEARSETINT, 12, 1, 0,	/* LINHA 1*/
	HB_P_PUSHLOCALNEAR, 12,	/* LINHA */
	HB_P_PUSHLOCALNEAR, 11,	/* LINHAS */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 65,	/* 65 (abs: 00992) */
/* 00929 */ HB_P_LINEOFFSET, 91,	/* 100 */
	HB_P_PUSHSYMNEAR, 23,	/* MEMOLINE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 21,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 35,	/* PRESC */
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_PUSHLOCALNEAR, 12,	/* LINHA */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 13,	/* LIN */
/* 00948 */ HB_P_LINEOFFSET, 92,	/* 101 */
	HB_P_PUSHSYMNEAR, 24,	/* ADIREG */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00955 */ HB_P_LINEOFFSET, 93,	/* 102 */
	HB_P_PUSHSYMNEAR, 25,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 36,	/* COND */
	HB_P_POPALIASEDFIELDNEAR, 27,	/* DATA */
/* 00966 */ HB_P_LINEOFFSET, 94,	/* 103 */
	HB_P_PUSHSYMNEAR, 21,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 28,	/* REGISTRO */
	HB_P_PUSHSYMNEAR, 36,	/* COND */
	HB_P_POPALIASEDFIELDNEAR, 29,	/* CODCLI */
/* 00976 */ HB_P_LINEOFFSET, 95,	/* 104 */
	HB_P_PUSHLOCALNEAR, 13,	/* LIN */
	HB_P_PUSHSYMNEAR, 36,	/* COND */
	HB_P_POPALIASEDFIELDNEAR, 30,	/* DESCRICAO */
/* 00984 */ HB_P_LINEOFFSET, 96,	/* 105 */
	HB_P_LOCALNEARADDINT, 12, 1, 0,	/* LINHA 1*/
	HB_P_JUMPNEAR, 188,	/* -68 (abs: 00922) */
/* 00992 */ HB_P_LINEOFFSET, 100,	/* 109 */
	HB_P_PUSHSYMNEAR, 37,	/* DBCOMMITALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00999 */ HB_P_LINEOFFSET, 101,	/* 110 */
	HB_P_PUSHSYMNEAR, 38,	/* DBUNLOCKALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01006 */ HB_P_LINEOFFSET, 103,	/* 112 */
	HB_P_PUSHSYMNEAR, 8,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'l', 'i', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 13,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 1,
/* 01026 */ HB_P_LINEOFFSET, 104,	/* 113 */
	HB_P_PUSHSYMNEAR, 39,	/* DBSKIP */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 149, 253,	/* -619 (abs: 00415) */
/* 01037 */ HB_P_LINEOFFSET, 107,	/* 116 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 01042 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

