*** CON211.PRG: Inclusao de Duplicatas (a pagar)
************************************************
MEMVAR getlist,nivel_acess,mdata_sis,cod_operado,memp_resa,;
       mend_firm,mcid_firm,muf_firm,mfone_firm,minsc_firm,mcgc_firm

FUNCTION con211(mcx)
****************
LOCAL MPRG:='CON211',;
      mtipo,mduplicata,mcod_ven,mtraco,opcao,tela_dupp,mobs,mvalor,mtip:=SPACE(1),;
      mextenso,mlinha,mlin,lin,lba,cba,mnum_banco,mc_c,mtp_pg:=' ',nulo:='NULL',mdescricao:=''

PRIVATE mcod_forn,mvenc,memissao,mnome_vend,mcom_ven,mfornece,mend,mbairro,mcidade,;
        muf,mcgc,mcpf,minsc,mbanco,mnum_nf,mcodconta,;
        mtipo_imp,mimp_tipo:=0,marq:=SPACE(35)

IF ! ver_nivel(mprg,'CONTA APAGAR (INCLUSAO DE DOCUMENTOS)','15',nivel_acess,,'AMBIE')
        RETURN NIL
ENDIF
lba := 20
cba := 78
*------------------------------------------------------------------------------------
IF ! AbriArq('sacforn','forn');RETURN NIL;ENDIF
IF ! AbriArq('sacdupp','dupp');RETURN NIL;ENDIF
IF ! AbriArq('sacdesp','cdesp');RETURN NIL;ENDIF
IF ! AbriArq('insopera','sen');RETURN NIL;ENDIF
IF ! AbriArq('saccaixa','caix');RETURN NIL;ENDIF
*------------------------------------------------------------------------------------
mtraco := REPLI('-',80)
op_tela(05,10,29,110)
WHILE .T.
        limpa(00,00,30,100)
        exibi_prg(mprg)
        IF mcx = NIL
                Wvw_SetTitle( ,' CONTAS A PAGAR - Inclusao de Documentos ')           
                memissao:=mdata_sis
                mvenc   :=CTOD("  /  /  ")
                mtipo   :=SPACE(2)
                mbanco  := SPACE(1)
        ELSE
                Wvw_SetTitle( ,' EMISSAO DE DESPESAS ADMINISTRATIVA ')           
                memissao:=mdata_sis
                mvenc   :=mdata_sis
                mtipo   :='PA'
                mbanco  := 'C'
        ENDIF
*        DEVPOS(1,2);DEVOUT('Codigo da Empresa......:')
        DEVPOS(2,2);DEVOUT('Tipo Documento.........:     <DU>plicata <CH>eques <FR>ete <PA>gamentos <VL>Vales <BN>BNB <DE>Descarrego')
        DEVPOS(3,2);DEVOUT('Numero Banco...........:')
        DEVPOS(3,32);DEVOUT('Conta:')
        DEVPOS(4,2);DEVOUT('Numero Documento.......:')
        DEVPOS(5,2);DEVOUT('Codigo do Fornecedor...:')
        //DEVPOS(6,2);DEVOUT('Tipo de Conta..........:')
        DEVPOS(7,2);DEVOUT('Data de Emissao........:')
        DEVPOS(8,2);DEVOUT('Data de Vencimento.....:')
        DEVPOS(9,2);DEVOUT('Valor Duplicata R$.....:')
        DEVPOS(10,2);DEVOUT('Pag. [C]arteria [B]anco:')
        DEVPOS(11,2);DEVOUT('Tipo de Pagamento......:')
        DEVPOS(12,2);DEVOUT('Numero da Nota Fiscal..:')
        DEVPOS(13,2);DEVOUT('Observacao:')
        mtipo_imp := 'R'
        *****************
        SELE('dupp');ORDSETFOCUS(1)
        *****************
        mc_c := SPACE(10)
        mnum_banco := SPACE(3)
        mfornece := SPACE(40)
        mend := SPACE(35)
        mbairro := mcidade := SPACE(20)
        muf := SPACE(2)
        mcgc := minsc := SPACE(14)
        mcpf := SPACE(11)
        mcod_ven := mcom_ven := mcod_forn := mvalor := 0
        mnome_vend := SPACE(30)
        mduplicata=SPACE(10)
        mnum_nf := SPACE(6)
        mobs := SPACE(60)
        mcodconta := SPACE(4)
        mtp_pg  := ' '
        Mensagem('Digite o Numero da Documento. [ESC] Abandona.')
        @ 2,27 GET mtipo PICT '@!' VALID mtipo $ 'CH,DU,FR,PA,VL,BN,DE'       //WHEN mcx = NIL
        @ 3,27 GET mnum_banco PICT '@!' WHEN mtipo = 'CH'
        @ 3,40 GET mc_c PICT '@!' WHEN mtipo = 'CH'
        @ 4,27 GET mduplicata PICT '@!' VALID IF(EMPTY(mduplicata),.F.,.T.)
        @ 5,27 GET mcod_forn PICT "9999" VALID IF(EMPTY(mcod_forn),.F.,v_fornece(mcod_forn,5,32))
        READ
        IF LASTKEY()=27
                RESTSCREEN(00,00,24,79,tela_dupp)
                wvw_lclosewindow()
                RETURN NIL
        ENDIF
        *****************
        SELE('dupp');ORDSETFOCUS(1)
        GO TOP
        *****************
*       IF dupp->(DBSEEK(mtipo+mduplicata+' '+STRZERO(mcod_forn,4)+DTOS(mvenc)))
        IF dupp->(DBSEEK(mtipo+mduplicata+' '+STRZERO(mcod_forn,4)))
                atencao('Esta Documento ja existe e esta em ABERTO - Valor do Documento:'+TRANSFORM(dupp->valor,'999,999.99'))
                opcao := op_simnao('N','Deseja Incluir mesmo assim ? [S/n]:')
                IF LASTKEY() = 27 .OR. opcao = "N"
                        LOOP
                ENDIF
        ENDIF
        IF dupp->(DBSEEK(mtipo+mduplicata+'B'+STRZERO(mcod_forn,4)))
                atencao('Esta Documento ja existe e ja foi PAGO  - Valor do Documento:'+TRANSFORM(dupp->valor,'999,999.99'))
                opcao := op_simnao('N','Deseja Incluir mesmo assim ? [S/n]:')
                IF LASTKEY() = 27 .OR. opcao = "N"
                        LOOP
                ENDIF
        ENDIF
        Mensagem('Complete os Dados. [ESC] Abandona.')
        mfornece := forn->razao
        mcodconta := forn->tipo
        @ 5,32 GET mfornece PICT "@!"
        //@ 6,27 GET mcodconta PICT '9999' VALID IF(LEN(ALLTRIM(mcodconta))<3,.F.,verdesp(mcodconta,6,34)) .AND. lim_get() WHEN men_get(7,27,'Identifique o Grupo da Conta preenchendo so o primeiro digito da conta, ou preenchendo todo os espaco p/o tipo de conta <F1>Ajuda')
        //@ 6,27 GET mcodconta PICT '@@R X.XX.X' VALID IF(LEN(ALLTRIM(mcodconta))<4,.F.,verdesp(mcodconta,6,32)) .AND. lim_get() WHEN men_get(7,27,'Identifique o Grupo da Conta preenchendo so o primeiro digito da conta, ou preenchendo todo os espaco p/o tipo de conta <F1>Ajuda')
        READ
        IF LASTKEY() = 27;LOOP;ENDIF
        @ 7,27 GET memissao WHEN mcx = NIL
        @ 8,27 GET mvenc VALID vencim(mvenc) WHEN mcx = NIL
        @ 9,27 GET mvalor PICT "999,999,999.99" VALID IF(mvalor<0,.F.,.T.)
        @ 10,27 GET mbanco PICT "@!" VALID mbanco $ 'C,B, ' WHEN mcx = NIL
        @ 11,27 GET mtp_pg PICT "@!" 		//WHEN men_get(2,38,'Deixar em branco ou preencha com o tipo de pagamento que desajar')
        @ 12,27 GET mnum_nf PICT "@!"
        @ 13,14 GET mobs
        READ
        IF LASTKEY()=27
                LOOP
        ENDIF
        opcao := op_simnao('S','Confirma os Dados:')
        IF opcao = "N"
                LOOP
        ENDIF
        IF mtipo = 'VL'
                mdescricao:='VALES'
        ELSEIF mtipo = 'PA'
                mdescricao:='PAGAMENTO'
        ELSEIF mtipo = 'DU'
                mdescricao:='DUPLICATA'
        ELSEIF mtipo = 'CH'
                mdescricao:='CHEQUE'
        ELSEIF mtipo = 'FR'
                mdescricao:='FRETE'
        ENDIF

        mtip := ' '
        IF memissao = mvenc
                opcao := op_simnao('S','Deseja fazer a BAIXA deste documento agora:')
                IF opcao = 'S'
                        mtip := 'S'
                ENDIF
        ENDIF
        sr_getconnection():exec('INSERT INTO sacdupp ('+;
                'tipo      ,'+;//2
                'numero    ,'+;//3
                'c_c       ,'+;//4
                'duplicata ,'+;//5
                'valor_dup ,'+;//6
                'tip_for   ,'+;//7
                'fornec    ,'+;//8
                'cliente   ,'+;//9
                'emissao   ,'+;//10
                'venc      ,'+;//11
                'valor     ,'+;//12
                'vendedor  ,'+;//13
                'num_ped   ,'+;//14
                'tp_pg     ,'+;//15
                'operador  ,'+;//16
                'obs       ,'+;//17
                'datpag    ,'+;//18
                'vlpago    ,'+;//19
                'pago      ,'+;//20
                'banco     ,'+;//21
                'SR_DELETED )'+;
                ' VALUES ('+;
                sr_cdbvalue(mtipo               )+','+; //2
                sr_cdbvalue(mnum_banco          )+','+; //3
                sr_cdbvalue(mc_c                )+','+; //4
                sr_cdbvalue(mduplicata          )+','+; //5
                sr_cdbvalue(mvalor              )+','+; //6
                sr_cdbvalue(mcodconta           )+','+; //7
                sr_cdbvalue(STRZERO(mcod_forn,4))+','+; //8
                sr_cdbvalue(mfornece            )+','+; //9
                sr_cdbvalue(memissao            )+','+; //10
                sr_cdbvalue(mvenc               )+','+; //11
                sr_cdbvalue(mvalor              )+','+; //12
                sr_cdbvalue(cod_operado         )+','+; //13
                sr_cdbvalue(mnum_nf             )+','+; //14
                sr_cdbvalue(mtp_pg              )+','+; //15
                sr_cdbvalue(cod_operado         )+','+; //16
                sr_cdbvalue(mobs                )+','+; //17
                IF(mtip = 'S',sr_cdbvalue(mvenc),nulo)+','+; //18
                IF(mtip = 'S',sr_cdbvalue(mvalor),nulo)+','+; //19
                IF(mtip = 'S',sr_cdbvalue('B'),nulo)+','+; //20
                IF(mtip = 'S',sr_cdbvalue('C'),nulo)+','+; //21
                sr_cdbvalue(' ')+')',,.f.)
        sr_getconnection():exec('COMMIT',,.f.)
                opcao := op_simnao('N','Deseja Imprimir o DOCUMENTO:')
                IF LASTKEY() = 27 .OR. opcao = 'N'
                        LOOP
                ENDIF
                IF ! imp_arq('HTI.REL','R')
                        LOOP
                ENDIF
                imprt(mtipo_imp,'E')
                pitalico(.T.)
                DEVPOS(PROW(),00);DEVOUT(m_set[1,23])
                pitalico(.F.)
                imprt(mtipo_imp,'N')
                DEVPOS(PROW()+1,00);DEVOUT(mend_firm)
                DEVPOS(PROW()+1,00);DEVOUT(mcid_firm)
                DEVPOS(PROW()+1,00);DEVOUT('Fone: '+mfone_firm)
                DEVPOS(PROW()+1,00);DEVOUT('Inscr. '+minsc_firm+'   C.G.C.: '+mcgc_firm)
                @ PROW()+1,00 SAY mtraco
                @ PROW()+1,00 SAY ' '
                @ PROW(),00 SAY 'Despesa:'
                @ PROW(),PCOL()+1 SAY STRZERO(mcod_forn,4)
                @ PROW(),PCOL()+1 SAY mfornece
                @ PROW()+1,00 SAY 'End.: '+mend
                @ PROW()+1,00 SAY 'Bairro: '+RTRIM(mbairro)+'-Cidade: '+RTRIM(mcidade)+'-'+muf
                IF mcgc <> SPACE(14)
                @ PROW()+1,00 SAY 'CNPJ:'
                        DEVPOS(PROW(),PCOL()+1);DEVOUTPICT(mcgc,'@@R 99.999.999/9999-99')
                        DEVPOS(PROW(),PCOL()+1);DEVOUT(' - Insc.: '+minsc)
                ELSEIF mcpf <> SPACE(11)
                        @ PROW()+1,00 SAY 'CPF:'
                        DEVPOS(PROW(),PCOL()+1);DEVOUTPICT(mcpf,'@@R 999.999.999-99')
                ENDIF
                @ PROW()+1,00 SAY mtraco
                imprt(mtipo_imp,'E',1)
                pitalico(.T.)
                @ PROW(),00 SAY 'DUPLICATA A PAGAR No.: '+mtipo+mduplicata
                pitalico(.F.)
                imprt(mtipo_imp,'N')
                @ PROW()+1,00 SAY mtraco
                @ PROW()+1,00 SAY 'Emissao:'
                @ PROW(),09 SAY memissao
                @ PROW(),38 SAY 'Vencimento:'
                @ PROW(),50 SAY mvenc
                @ PROW(),50 SAY mvenc
                @ PROW(),PCOL()+2 SAY 'Cod.:'
                @ PROW(),PCOL()+1 SAY cod_operado
                @ PROW()+1,00 SAY mtraco
                DEVPOS(PROW()+1,00);DEVOUT(PADC('Valor R$: ('+LTRIM(TRANSFORM(mvalor,'99,999,999.99'))+')',60))
                mextenso:= '('+extenso(mvalor,.T.,'real','reais')+')'
*               mextenso:= '('+RTRIM(extenso(mvalor,10))+')'
                mlinha := MLCOUNT(mextenso,80)
                FOR lin = 1 TO mlinha
                        mlin := MEMOLINE(mextenso,80,lin,,10)
                        DEVPOS(PROW()+1,00);DEVOUT(PADR(RTRIM(mlin),80))
                NEXT
                @ PROW()+1,00 SAY mtraco
                DEVPOS(PROW()+1,00);DEVOUT('Obs.: '+mobs)
                @ PROW()+1,00 SAY mtraco
                DEVPOS(PROW()+3,00);DEVOUT(PADC('Em ......../......../........',80))
                DEVPOS(PROW()+1,00);DEVOUT(PADC('Data do Aceite',80))
                DEVPOS(PROW()+2,00);DEVOUT(PADC('.................................           ...............................',80))
                DEVPOS(PROW()+1,00);DEVOUT(PADC('     Assinatura do Emitente                      Assinatura do Sacado',80))
                @ PROW()+1,00 SAY mtraco
                EJECT
                SETPRC(00,00)
                SET DEVI TO SCREEN;SET PRINT TO;SET PRINT OFF
                conf_impressao('HTI.REL')
ENDDO
wvw_lclosewindow()
RETURN NIL
*********************** f i m *************************************
