#include "wvwtools.ch"
#include "inkey.ch"              // constantes de codigos das teclas
#INCLUDE "wingdi.ch"
#INCLUDE "winuser.ch"
#INCLUDE "COMMCTRL.CH"
*** CON251.PRG: Baixa INDIVIDUAL de Duplicatas (Receber)
***             ALTERACAO, ESTORNO E IMPRESSAO
********************************************************
MEMVAR getlist,nivel_acess,mdata_sis,cod_operado,mmens,mcgc_firm,minsc_firm,memp_resa,;
       mend_firm,mcid_firm,mfone_firm

FUNCTION con251(cx,mtp,mtp_)
****************************
LOCAL MPRG:='CON251',oWindow,;
      tela,lin,mcheque,mdatpag,mvlpago,mnota,mtipo_comp,;
      mcod_vend,mforn_aux,opcao,mbanco,lc,cc,lb,cb,mcomissao,mnumero,;
      pconta,mtip_cli,mvalor_dup,mcliente,memissao,mvenc,mnum_ped,mvalor_cont,;
      mdias_atras,mjuros,mmulta,mcont_doc,mtotal_doc,m_dupr:={},m_pos:={},m_dup:={},m_po:={},;
      li,ci,la,ca,tela1,point,mqtd_doc,mqtd_dias,mtraco:=REPLI('=',80),;
      mordem:=0,mcod_ven,mnum_banco,magencia,mc_c,mcorrente,mextenso,mlinha,mlin,;
      mnome_cli := SPACE(40),mtip_pg:='  ',mtela_aut,mtipo_aut,;
      mdoc_tran,mdat_tran,mlimp_cli:=' ',mdescri1:=SPACE(20),mdescri2:=SPACE(20),;
      mmotivo:=SPACE(30),mtel_mot,mlin1,mlin2,mlin3,mlin4,mlin5,;
      lba := 15,cba := 79,mtroco:=0,stop:=' ',cons_cli:={},mtipo_dup:=' ',;
      nulo:='NULL',mdesconto:=0,mperc_desc:=0,mjuros_aux:=0,mtot_juros:=0,aret:={},cComm,mdevedor,nBota,;
      slinhas:='',mcnpj:='',mdata_sen,mdata_aux,mtext :=''

PRIVATE mcod_cli,mtipo,mduplicata,mfornec,mvalor,mcnpjcpf:=SPACE(14),malias,;
        mtipo_imp,mimp_tipo:=0,marq:=SPACE(35),mobs,mobs1,mtp_tp,cons_dupr := {},cons_ped:={},;
        cons_processo:={},mportador,mprevisao
*------------------------------------------------------------------------------------
IF ! AbriArq('insopera','sen');RETURN NIL;ENDIF
*------------------------------------------------------------------------------------
CLEAR GETS
SET KEY -9 TO ctrl_w()
setcor(1)
mtp_tp := mtp_
IF mtp_ = NIL
        IF ! AbriArq('sacdupr','dupr');RETURN NIL;ENDIF
        IF mtp = NIL
                IF cx <> NIL
                        IF ! ver_nivel(mprg+'CX','CONTA A RECEBAR (BAIXA INDIVIDUAL DOCUMENTOS CAIXA)','135',nivel_acess,,'AMBIE')
                                RETURN NIL
                        ENDIF
                ELSE
                        IF ! ver_nivel(mprg+'MV','CONTA A RECEBER (BAIXA INDIVIDUAL DOCUMENTOS MOVIMENTO)','135',nivel_acess,,'AMBIE')
                                RETURN NIL
                        ENDIF
                ENDIF
        ELSEIF mtp = 'S'
                IF ! ver_nivel(mprg+'ES','CONTA A RECEBER (ESTORNO DE DOCUMENTOS RECEBIDO)','135',nivel_acess,,'AMBIE')
                        RETURN NIL
                ENDIF
        ELSEIF mtp = 'E'
                IF ! ver_nivel(mprg+'EX','CONTA A RECEBER (EXCLUSAO DE DOCUMENTOS A RECEBER)','1',nivel_acess,,'AMBIE')
                        RETURN NIL
                ENDIF
        ELSEIF mtp = 'A'
                IF ! ver_nivel(mprg+'AL','CONTA A RECEBER (ALTERACAO DE DOCUMENTOS A RECEBER)','135',nivel_acess,,'AMBIE')
                        RETURN NIL
                ENDIF
        ELSEIF mtp = 'P'
                IF ! ver_nivel(mprg+'PR','CONTA A RECEBER (PROCESSO DE DOCUMENTOS A RECEBER)','135',nivel_acess,,'AMBIE')
                        RETURN NIL
                ENDIF
        ELSEIF mtp = 'I'
                IF ! ver_nivel(mprg+'IMP','CONTA A RECEBER (IMPRESSAO DE DOCUMENTOS A RECEBER)','135',nivel_acess,,'AMBIE')
                        RETURN NIL
                ENDIF
        ENDIF
        malias := 'dupr'
ELSE
        IF ! AbriArq('saccred','cred');RETURN NIL;ENDIF
        IF mtp = NIL
                IF ! ver_nivel(mprg+'MV'+mtp_,'CREDITO CLIENTE (BAIXA INDIVIDUAL DOCUMENTOS MOVIMENTO)','135',nivel_acess,,'AMBIE')
                        RETURN NIL
                ENDIF
        ELSEIF mtp = 'S'
                IF ! ver_nivel(mprg+'ES'+mtp_,'CREDITO CLIENTE (ESTORNO DE DOCUMENTOS RECEBIDO)','135',nivel_acess,,'AMBIE')
                        RETURN NIL
                ENDIF
        ELSEIF mtp = 'E'
                IF ! ver_nivel(mprg+'EX'+mtp_,'CREDITO CLIENTE (EXCLUSAO DE DOCUMENTOS A RECEBER)','1',nivel_acess,,'AMBIE')
                        RETURN NIL
                ENDIF
        ELSEIF mtp = 'A'
                IF ! ver_nivel(mprg+'AL'+mtp_,'CREDITO CLIENTE (ALTERACAO DE DOCUMENTOS A RECEBER)','135',nivel_acess,,'AMBIE')
                        RETURN NIL
                ENDIF
        ENDIF
        malias := 'cred'
ENDIF
lc := 1
cc := 0
lb := 19
cb := 79

li := ci := 0
la := 21
ca := 63

lin=1
mcod_cli := mforn_aux := 0
mduplicata := SPACE(12)
SET KEY 275 TO cons_doc()
IF mtp_ <> NIL
        op_tela(03,10,27,90," CREDITO CLIENTE "+IF(cx<>NIL,' *** CAIXA ***',' *** MOVIMENTO ***'))
ELSEIF mtp = 'S'
        op_tela(03,10,27,90," Estorno de Documentos INDIVIDUAL "+IF(cx<>NIL,' *** CAIXA ***',' *** MOVIMENTO ***'))
ELSEIF mtp = 'E'  
        op_tela(03,10,23,90," Exclusao de Documentos INDIVIDUAL "+IF(cx<>NIL,' *** CAIXA ***',' *** MOVIMENTO ***'),'*')
ELSEIF mtp = NIL
        op_tela(03,10,27,90," Baixa de Documentos INDIVIDUAL "+IF(cx<>NIL,' *** CAIXA ***',' *** MOVIMENTO ***'))
        nBota := wvw_pbCreate(NIL,0,64,1,78,'BAIXA GERAL',NIL,{||con252('*')})
        WVW_PBEnable( NIL, nBota, .T. )
ELSEIF mtp = 'A'
        op_tela(03,10,27,90," Alteracao de Documentos a Receber "+IF(cx<>NIL,' *** CAIXA ***',' *** MOVIMENTO ***'))
ELSEIF mtp = 'P'
        op_tela(01,10,24,90," PROCESSO de Documentos a Receber "+IF(cx<>NIL,' *** CAIXA ***',' *** MOVIMENTO ***'),,'*')
ELSEIF mtp = 'I'
        op_tela(03,10,27,90," IMPRESSAO de Documentos a Receber "+IF(cx<>NIL,' *** CAIXA ***',' *** MOVIMENTO ***'))
ENDIF


WHILE .T.
******** VARIAVEIS DE IMPRESSAO *******************
        mtipo_imp := 'M'
****************************************************
        exibi_prg(mprg)
        *****************
        SELE(malias);ORDSETFOCUS(1)
        *****************
        limpa(lc-1,cc,lb,cb)
        DEVPOS(lc,cc+1);DEVOUT('Numero Documento.........:')
        DEVPOS(lc+1,cc+1);DEVOUT('Codigo Cliente...........:')
        DEVPOS(lc+1,cc+35);DEVOUT('CPF/CNPJ: ')
        DEVPOS(lc+2,cc+1);DEVOUT('Nome FANTASICA...........:')
        DEVPOS(lc+3,cc+1);DEVOUT('Tipo - Numero............:    -')
        //DEVPOS(lc+4,cc+1);DEVOUT('Numero Documento.........:')
        DEVPOS(lc+4,cc+1);DEVOUT('Numero Pedido............:')
        DEVPOS(lc+5,cc+1);DEVOUT('Data Emissao.............:')
        DEVPOS(lc+6,cc+1);DEVOUT('Data Vencimento..........:')
        DEVPOS(lc+6,cc+42);DEVOUT('Venc.Anterior:')
        DEVPOS(lc+7,cc+1);DEVOUT('Dias em Atraso...........:')
        DEVPOS(lc+8,cc+1);DEVOUT('Data Pagamento...........:')
        DEVPOS(lc+9,cc+1);DEVOUT('Valor Documento..........:')
        DEVPOS(lc+10,cc+1);DEVOUT('Multa (%) .............R$:')
        DEVPOS(lc+11,cc+1);DEVOUT('Juros ao dia (%) ......R$:')
        DEVPOS(lc+12,cc+1);DEVOUT('Valor a Pagar............:')
        DEVPOS(lc+13,cc+1);DEVOUT('Tipo de Operacao.........:')
        DEVPOS(lc+14,cc+1);DEVOUT('Numero Cheque............:')
        DEVPOS(lc+15,cc+1);DEVOUT('Pag.[B]anco [C]arteira...:')
        DEVPOS(lc+16,cc+1);DEVOUT('Obs.Incl.:')
        DEVPOS(lc+17,cc+1);DEVOUT('Obs.Baixa:')
        IF mtp = 'I'
                DEVPOS(lc+18,cc+1);DEVOUT('Tipo Dup.[S]istema [P]re-Impressa:')
                DEVPOS(lc+19,cc+1);DEVOUT('Quantidade de Copias.............:')
        ENDIF

        Mensagem('Informe o Cod.do CLIENTE - [F1]p/Consultar Cliente - [ALT+R]Consulta de Documentos - [ENTER]p/informa o tipo de DOCUMENTO - <ESC>p/abandonar')
        mnota := SPACE(8)
        mcnpjcpf := SPACE(14)
        mcliente := SPACE(40)
        mtipo_comp := mtipo := SPACE(2)
        mcod_vend := SPACE(3)
        mduplicata := SPACE(12)
        mcheque=SPACE(8)
        mbanco := SPACE(1)
        mnumero := SPACE(3)
        mobs := mobs1:= SPACE(60)
        mmotivo:=SPACE(30)
        pconta := mlimp_cli := ' '
        mdias_atras := mqtd_dias := mqtd_doc := mvalor_dup := mcomissao := 0
        mtip_pg := '  '
        @ lc+1,cc+28 GET mcod_cli PICT '99999' VALID ver_cli(mcod_cli,lc+1,cc+35,,lc+2,cc+28)
        @ lc+1,cc+45 GET mcnpjcpf PICT '99999999999999' WHEN EMPTY(mcod_cli) VALID v_cnpjcpf(mcnpjcpf)
        READ
        IF ! EMPTY(mcnpjcpf)
                mcod_cli := VAL(cli->cod_cli)
                ver_cli(mcod_cli,lc+1,cc+35,,lc+2,cc+28)
        ENDIF
        @ lc+3,cc+28 GET mtipo PICT '@!' VALID ver_tipdc(mtipo,'*') WHEN EMPTY(mcod_cli)
        @ lc+3,cc+33 GET mnumero PICT '@!' WHEN mtipo <> 'DU' .AND. ! EMPTY(mtipo) .AND.  EMPTY(mcod_cli)
        @ lc+4,cc+28 GET mduplicata PICT '@!' WHEN ! EMPTY(mtipo) .AND.  EMPTY(mcod_cli)
        READ
        IF LASTKEY()=27         // .OR. mduplicata := SPACE(12)
                wvw_lclosewindow()
                RETURN NIL
        ENDIF
        IF ! EMPTY(mcod_cli)
                setcor(3)
                DEVPOS(lc+1,cc+28);DEVOUT(STRZERO(mcod_cli,5))
                setcor(1)
                ver_cli(mcod_cli,lc+1,cc+35,,lc+2,cc+28)
                IF ver_serie()='141237'
                        mordem := '6'
                ELSE
                        mordem := '2'
                        mordem := mensagem1('Tipo de Ordem [2] DOCUMENTO - [6] VENCIMENTO - [3] VALOR:','2','2,6,3')
                ENDIF
                mtotal_doc := mcont_doc := 0
                ASIZE(m_dupr,0)
                ASIZE(m_pos,0)

                mensagem('Aguarde o Coletando dados p/ impressao...')
                ************************************************************
                IF mtp_tp = NIL
                        cComm  := "SELECT * FROM sacdupr WHERE fornec = "+sr_cdbvalue(STRZERO(mcod_cli,5))
                ELSE
                        cComm  := "SELECT * FROM saccred WHERE fornec = "+sr_cdbvalue(STRZERO(mcod_cli,5))
                ENDIF
                
                IF mtp = 'S'
                        ccomm := ccomm + " AND datpag IS NOT NULL"
                ELSEIF mtp = 'A' .OR. mtp = NIL .OR. mtp = 'P' .OR. mtp = 'E' .OR. mtp = 'I'
                        ccomm := ccomm + " AND datpag IS NULL"
                ENDIF
                IF mordem = '6'
                        ccomm := ccomm + " ORDER BY venc,duplicata"
                ELSEIF mordem = '2'
                        ccomm := ccomm + " ORDER BY tipo,duplicata,venc"
                ELSE
                        ccomm := ccomm + " ORDER BY valor,duplicata"
                ENDIF
                aret:={}
                sr_getconnection():exec(ccomm,,.t.,@aret)
                sr_getconnection():exec('COMMIT',,.f.)
                IF LEN(aret) = 0
                        atencao('Nao existe nenhum Documento a ser baixado')
                        LOOP
                ENDIF
                setcor(3)
                DEVPOS(lc+1,cc+28);DEVOUT(STRZERO(mcod_cli,5))
                DEVPOS(lc+1,cc+35);DEVOUT(aret[1,1])
                setcor(1)
                mcliente := aret[1,1]
                mdatpag := mdata_sis
                i := mtot_juros := 0
		FOR i = 1 TO LEN(aret)
                        mjuros  := mmulta := mjuros_aux := 0
                                     //  tipo        duplicata       tip_pg         numero             venc                      valor                             conta                    data_fund                     emp.
                        AADD(m_dupr,' '+aret[i,2]+' '+aret[i,4]+' '+aret[i,26]+'  '+aret[i,3]+'   '+DTOC(aret[i,11])+'   '+TRANSFORM(aret[i,19],'999,999.99')+' '+aret[i,28]+' '+IF(! EMPTY(aret[i,43]),'S/F','   ')+' '+aret[i,1])
                        //AADD(m_pos,aret[i,10])
                        mcont_doc ++
                        mtotal_doc := mtotal_doc + aret[i,19]

                        IF aret[i,28] = '*'
                                mdias_atras := mdatpag - aret[i,11]
                        ELSE
                                mdias_atras := mdatpag - (aret[i,11]+m_set[1,40])
                        ENDIF
                        IF mdias_atras > 0 .AND. mtp_ = NIL
                                mdias_atras := mdatpag - aret[i,11]
                                mmulta := iat(aret[i,19] * ((m_set[1,9])/100),2)
                                mjuros := iat((aret[i,19] * ((mdias_atras*m_set[1,10])/100)),2)
                        ENDIF
			mtot_juros := mtot_juros + (mjuros + mmulta)
                NEXT
                op_tela(05,10,28,70,'Documentos do Cliente: '+STRZERO(mcod_cli,5)+' - '+aret[1,8])
                mensagem('<ESC> Retorna  -  <ENTER> p/Confirmar')
                setcor(3)
                DEVPOS(li+1,ci+01);DEVOUT('Documento')
                DEVPOS(li+1,ci+18);DEVOUT('Op')
                DEVPOS(li+1,ci+21);DEVOUT(' No.')
                DEVPOS(li+1,ci+27);DEVOUT('Vencimento')
                DEVPOS(li+1,ci+44);DEVOUT('Valor')
                DEVPOS(li+1,ci+56);DEVOUT('Emp')
                @ li+2,ci+1 TO li+2,ca-1
                @ la-2,ci+1 TO la-2,ca-1
                DEVPOS(la-1,ci+1);DEVOUT('Quantidade:')
                DEVPOS(la-1,ci+30);DEVOUT('Total.......R$:')
                DEVPOS(la  ,ci+30);DEVOUT('Juros+Multa R$:')
                DEVPOS(la+1,ci+30);DEVOUT('                ------------')
                DEVPOS(la+2,ci+30);DEVOUT('Total Geral R$:')
                setcor(1)
                DEVPOS(la-1,ci+13);DEVOUT(STRZERO(mcont_doc,4))
                DEVPOS(la-1,ci+46);DEVOUT(TRANSFORM(mtotal_doc,'9,999,999.99'))
                setcor(5)
                DEVPOS(la  ,ci+46);DEVOUT(TRANSFORM(mtot_juros,'9,999,999.99'))
                setcor(1)
                DEVPOS(la+2,ci+46);DEVOUT(TRANSFORM(mtotal_doc +mtot_juros,'9,999,999.99'))
                point := ACHOICE(li+3,ci+1,la-3,ca-1,m_dupr,,,point)
                wvw_lclosewindow()
                DO CASE
                        CASE LASTKEY()=27
                                LOOP
                        CASE LASTKEY() = 13
                                mjuros := mmulta := mjuros_aux := 0
                                mdatpag:=mdata_sis
                                mvlpago:=aret[point,19]
                                mbanco := SUBSTR(aret[point,16],1,1)
                                mcomissao := aret[point,32]
                                mobs := aret[point,46]
                                mobs1 := aret[point,47]
                                IF aret[point,28] = '*'
                                        mdias_atras := mdatpag - aret[point,11]
                                ELSE
                                        mdias_atras := mdatpag - (aret[point,11]+m_set[1,40])
                                ENDIF
                                IF mdias_atras > 0 .AND. mtp_ = NIL
                                        mdias_atras := mdatpag - aret[point,11]
                                        mmulta := iat(aret[point,19] * ((m_set[1,9])/100),2)
                                        mjuros := iat((aret[point,19] * ((mdias_atras*m_set[1,10])/100)),2)
                                ENDIF
                                mvlpago := iat(aret[point,19],2)+mjuros+mmulta
                                mduplicata := aret[point,4]
                                mtipo := aret[point,2]
                                setcor(3)
                                WVW_DrawLabel(,lc-1,cc+28,aret[point,4]+aret[point,28],,,,, 'Arial Black',20,20,,,,,)
                                @ lc+1,cc+35 SAY aret[point,8]
                                @ lc+3,cc+28 SAY aret[point,2]
                                @ lc+3,cc+33 SAY aret[point,3]
                                //@ lc+4,cc+28 SAY aret[point,4]+aret[point,28]
                                @ lc+4,cc+28 SAY aret[point,31]
                                @ lc+5,cc+28 SAY aret[point,10]
                                @ lc+6,cc+28 SAY aret[point,11]
                                @ lc+6,cc+57 SAY aret[point,12]
                                @ lc+7,cc+28 SAY IF(mdias_atras<0,TRANSFORM(0,'9999'),TRANSFORM(mdias_atras,'9999'))
                                @ lc+9,cc+28 SAY aret[point,19] PICT "99,999,999.99"
                                @ lc+10,cc+28 SAY mmulta PICT "99,999,999.99"
                                @ lc+11,cc+28 SAY mjuros PICT "99,999,999.99"
                                setcor(1)
                                IF mtp = NIL
                                        IF EMPTY(aret[point,11])
                                                atencao('Favor Verificar o VENCIMENTO deste documento para poder Prossegir...')
                                                LOOP
                                        ENDIF
                                        @ lc+8,cc+28 GET mdatpag WHEN cx = NIL
                                        READ
                                        IF LASTKEY()=27
                                                LOOP
                                        ENDIF
                                        IF mdatpag <> mdata_sis
                                                IF ! ver_nivel('DOC_DATA','CONTA A RECEBER (ALTERACAO DATA BAIXA DE DOCUMENTO)','1',nivel_acess,,'AMBIE')
                                                        LOOP
                                                ENDIF
                                        ENDIF
                                        IF aret[point,28] = '*'
                                                mdias_atras := mdatpag - aret[point,11]
                                        ELSE
                                                mdias_atras := mdatpag - (aret[point,11]+m_set[1,40])
                                        ENDIF
                                        IF mdias_atras > 0 .AND. mtp_ = NIL
                                                mdias_atras := mdatpag-aret[point,11]
                                                mmulta := iat(aret[point,19] * ((m_set[1,9])/100),2)
                                                mjuros := iat((aret[point,19] * ((mdias_atras*m_set[1,10])/100)),2)
                                        ELSEIF mdias_atras < 0
                                                mjuros := mmulta := 0
                                                IF m_set[1,118] > 0
                                                        mperc_desc := (mdias_atras * -1) * m_set[1,118]
                                                        mdesconto := iat((aret[point,19] * (mperc_desc/100)),2)
                                                        botao(lc+8,cc+44,lc+13,cc+73,,'Desconto')
                                                        DEVPOS(lc+9,cc+45);DEVOUT('Dias Antecipados:')
                                                        DEVPOS(lc+10,cc+45);DEVOUT('% Desconto......:')
                                                        DEVPOS(lc+11,cc+45);DEVOUT('Valor Desconto..:')
                                                        DEVPOS(lc+12,cc+45);DEVOUT('Vlr.com Desconto:')
                                                        setcor(3)
                                                        DEVPOS(lc+9,cc+63);DEVOUT(STRZERO(mdias_atras * -1,4))
                                                        DEVPOS(lc+10,cc+63);DEVOUT(TRANSFORM(mperc_desc,'999.99'))
                                                        DEVPOS(lc+11,cc+63);DEVOUT(TRANSFORM(mdesconto,'999,999.99'))
                                                        DEVPOS(lc+12,cc+63);DEVOUT(TRANSFORM(aret[point,19] - mdesconto,'999,999.99'))
                                                        setcor(1)
                                                ENDIF
                                        ELSE
                                                mjuros := mmulta := 0
                                        ENDIF
                                        //mvlpago=iat(aret[point,19]+mjuros+mmulta-mdesconto,2)
                                        mvlpago=iat(aret[point,19]+mjuros+mmulta,2)
                                        setcor(3)
                                        @ lc+7,cc+28 SAY IF(mdias_atras<0,TRANSFORM(0,'9999'),TRANSFORM(mdias_atras,'9999'))
                                        @ lc+10,cc+28 SAY mmulta PICT "99,999,999.99"
                                        @ lc+11,cc+28 SAY mjuros PICT "99,999,999.99"
                                        @ lc+16,cc+12 SAY aret[point,46]
                                        setcor(1)
                                        mjuros_aux := mjuros
                                        IF mjuros > 0 .AND. (ver_serie() = '141490' .OR. ver_serie() = '141491' .OR. ver_serie() = '141492' .OR. ver_serie() = '141493')
                                        //IF mjuros > 0 .AND. (ver_serie() = '141302' .OR. ver_serie() = '141491' .OR. ver_serie() = '141492' .OR. ver_serie() = '141493')
                                                @ lc+11,cc+28 GET mjuros PICT "99,999,999.99" VALID IF(mjuros<0,.F.,.T.)
                                                READ
                                                IF mjuros_aux > mjuros
                                                        IF ! aut_sen('Senha de autorizacao p/dispensa o Juros do documento:','LIB_RECE',,'')
                                                                LOOP
                                                        ENDIF

                                                ENDIF
                                                mvlpago := iat(aret[point,19]+mjuros+mmulta,2)
                                        ENDIF

                                        @ lc+12,cc+28 GET mvlpago PICT "99,999,999.99"
                                        @ lc+13,cc+28 GET mtip_pg PICT '@!'
                                        @ lc+14,cc+28 GET mcheque PICT '99999999'
                                        @ lc+15,cc+28 GET mbanco PICT '@!' VALID mbanco $ 'B,C'
                                        @ lc+17,cc+12 GET mobs1
                                        READ
                                        IF mvlpago < iat(aret[point,19]+mjuros+mmulta,2) .AND. (ver_serie() = '141490' .OR. ver_serie() = '141491' .OR. ver_serie() = '141492' .OR. ver_serie() = '141493')
                                                IF ! aut_sen('Senha de autorizacao: Valor PAGO menor que o valor do Documento','LIB_RECE')
                                                        LOOP
                                                ENDIF
                                        ENDIF
                                        setcor(3)
                                        @ lc+17,cc+12 SAY mobs1
                                        setcor(1)
                                        IF LASTKEY()=27
                                                LOOP
                                        ENDIF
                                        opcao := op_simnao('S','Confirma os Dados ? [S/n]:')
                                        IF opcao = 'N'
                                                LOOP
                                        ENDIF
                                        pconta = ' '
                                        IF mvlpago < aret[point,19]+mjuros+mmulta-mdesconto .AND. ((aret[point,19]+mjuros+mmulta-mdesconto)-mvlpago) > .10
                                                pconta := op_simnao('S','Este Valor vai ser por CONTA [S/n]:')
                                                IF pconta = 'N'
                                                        IF ! aut_sen('Senha de autorizacao p/dispensa o restante do documento:','LIB_RECE')
                                                                LOOP
                                                        ENDIF
                                                ENDIF
                                        ENDIF
/*
                                        IF mvlpago > aret[point,19]+mjuros+mmulta
                                                stop:=' '
                                                setcor(3)
                                                op_tela(19,20,24,70,'TROCO','1')
                                                DEVPOS(00,01);DEVOUT(' T R O C O   R$:')
                                                DEVPOS(05,10);DEVOUT('Pressione qualquer tecla p/continuar...')
                                                WVW_DrawLabel(,01,02,TRANSFORM(mvlpago - (aret[point,19]+mjuros+mmulta),ALLTRIM('@E 999,999.99')),,,,, 'arial black',60,45,,,,,)
                                                @ 40,00 GET stop
                                                READ
                                                setcor(1)
                                                mvlpago := aret[point,19]+mjuros+mmulta
                                                wvw_lclosewindow()
                                        ENDIF
*/
                                        ASIZE(m_dup,0)
                                        ASIZE(m_po,0)
                                        IF mtp_tp = NIL
                                                *********** ATUALIZANDO SACDUPR ***********************
                                                ccomm := "UPDATE sacdupr SET datpag = " + sr_cdbvalue(mdatpag)+",datope = " + sr_cdbvalue(mdata_sis)
                                                IF pconta = 'S'
                                                        ccomm := ccomm + ",valor  = " + sr_cdbvalue(mvlpago)
                                                ENDIF
                                                ccomm := ccomm + ",vlpago = " + sr_cdbvalue(mvlpago)  +;
                                                                ",cheque = " + sr_cdbvalue(mcheque)  +;
                                                                ",pago   = " + sr_cdbvalue('B')  +;
                                                                ",tip_pg = " + sr_cdbvalue(mtip_pg)  +;
                                                                ",operador = " + sr_cdbvalue(cod_operado)+;
                                                                ",obs    = " + sr_cdbvalue(mobs)+;
                                                                ",obs1   = " + sr_cdbvalue(mobs1)+;
                                                                ",banco  = " + sr_cdbvalue(IF(cx <> NIL,'C',mbanco))+;
                                                                ",mov_cx = " + sr_cdbvalue(IF(cx <> NIL,'C','M'))+;
                                                                ",conta  = " + sr_cdbvalue(IF(pconta = 'S','*',''))+;
                                                                ",juros  = " + sr_cdbvalue(IF(pconta <> 'S' .AND. mvlpago>=aret[point,19],mvlpago-aret[point,19],0.00))+;
                                                                ",juros_d= " + sr_cdbvalue(IF(pconta <> 'S' .AND. mvlpago>=aret[point,19],(mmulta+mjuros)-(mvlpago-aret[point,19]),0.00))+;
                                                                ",desconto = " + sr_cdbvalue(mdesconto)+;
                                                                ",hora_bx  = " + sr_cdbvalue(TIME())+;
                                                                " WHERE sr_recno = " + sr_cdbvalue(aret[point,65])
                                                sr_getconnection():exec(ccomm,,.f.)
                                                **************************************************************
                                                IF pconta = 'S'
                                                        sr_getconnection():exec('INSERT INTO sacdupr (empresa,tipo,numero,'+;
                                                                'duplicata,valor_dup,'+;
                                                                'fornec,cliente,'+;
                                                                'tip_cli,emissao,'+;
                                                                'venc1,venc,valor,vendedor,num_ped,conta,'+;
                                                                'banco,comissao,operador,obs,obs1,agencia,c_c,corrente,'+;
                                                                'doc_tran,data_fund,cod_incl,motivo,com_sem,SR_DELETED )'+;
                                                                ' VALUES ('+;
                                                                sr_cdbvalue(aret[point,1])+','+; //1
                                                                sr_cdbvalue(aret[point,2])+','+; //2
                                                                sr_cdbvalue(aret[point,3])+','+; //3
                                                                sr_cdbvalue(aret[point,4])+','+; //4
                                                                sr_cdbvalue(aret[point,5])+','+; //5
                                                                sr_cdbvalue(aret[point,7])+','+; //6
                                                                sr_cdbvalue(aret[point,8])+','+; //7
                                                                sr_cdbvalue(aret[point,6])+','+; //8
                                                                sr_cdbvalue(aret[point,10])+','+;//9
                                                                sr_cdbvalue(IF(! EMPTY(aret[point,12]),aret[point,12],aret[point,11]))+','+;//10
                                                                sr_cdbvalue(IF(! EMPTY(mmulta) .OR. ! EMPTY(mjuros),mdatpag,aret[point,11]))+','+; //11
                                                                sr_cdbvalue((aret[point,19]+mmulta+mjuros)-mvlpago)+','+;//12
                                                                sr_cdbvalue(aret[point,30])+','+;//13
                                                                sr_cdbvalue(aret[point,31])+','+;//14
                                                                sr_cdbvalue('*')+','+;//15
                                                                sr_cdbvalue(mbanco)+','+;//16
                                                                sr_cdbvalue(iat(mcomissao,2))+','+;//17
                                                                sr_cdbvalue(cod_operado)+','+;//18
                                                                sr_cdbvalue(mobs)+','+;//19
                                                                sr_cdbvalue(mobs1)+','+;//20
                                                                sr_cdbvalue(aret[point,17])+','+;//21
                                                                sr_cdbvalue(aret[point,18])+','+;//22
                                                                sr_cdbvalue(aret[point,48])+','+;//23
                                                                sr_cdbvalue(aret[point,37])+','+;//24
                                                                IF(! EMPTY(aret[point,43]),sr_cdbvalue(aret[point,43]),nulo)+','+; //23  sr_cdbvalue(IF(EMPTY(aret[point,43]),nulo,aret[point,43]))+','+;//25
                                                                sr_cdbvalue(aret[point,45])+','+;//26
                                                                sr_cdbvalue(aret[point,44])+','+;//27
                                                                sr_cdbvalue(aret[point,64])+','+;//28
                                                                sr_cdbvalue(' ')+')',,.f.)
                                                ENDIF
                                        ELSE
                                                *********** ATUALIZANDO SACCRED ***********************
                                                ccomm := "UPDATE saccred SET datpag = " + sr_cdbvalue(mdatpag)+",datope = " + sr_cdbvalue(mdata_sis)
                                                IF pconta = 'S'
                                                        ccomm := ccomm + ",valor  = " + sr_cdbvalue(mvlpago)
                                                ENDIF
                                                ccomm := ccomm + ",vlpago = " + sr_cdbvalue(mvlpago)  +;
                                                                ",cheque = " + sr_cdbvalue(mcheque)  +;
                                                                ",pago   = " + sr_cdbvalue('B')  +;
                                                                ",tip_pg = " + sr_cdbvalue(mtip_pg)  +;
                                                                ",operador = " + sr_cdbvalue(cod_operado)+;
                                                                ",obs    = " + sr_cdbvalue(mobs)+;
                                                                ",obs1   = " + sr_cdbvalue(mobs1)+;
                                                                ",banco  = " + sr_cdbvalue(IF(cx <> NIL,'C',mbanco))+;
                                                                ",mov_cx = " + sr_cdbvalue(IF(cx <> NIL,'C','M'))+;
                                                                ",conta  = " + sr_cdbvalue(IF(pconta = 'S','*',''))+;
                                                                ",juros  = " + sr_cdbvalue(IF(pconta <> 'S' .AND. mvlpago>=aret[point,19],mvlpago-aret[point,19],0.00))+;
                                                                ",juros_d= " + sr_cdbvalue(IF(pconta <> 'S' .AND. mvlpago>=aret[point,19],(mmulta+mjuros)-(mvlpago-aret[point,19]),0.00))+;
                                                                " WHERE sr_recno = " + sr_cdbvalue(aret[point,65])
                                                sr_getconnection():exec(ccomm,,.f.)
                                                **************************************************************
                                                IF pconta = 'S'
                                                        sr_getconnection():exec('INSERT INTO saccred (empresa,tipo,numero,'+;
                                                                'duplicata,valor_dup,'+;
                                                                'fornec,cliente,'+;
                                                                'tip_cli,emissao,'+;
                                                                'venc1,venc,valor,vendedor,num_ped,conta,'+;
                                                                'banco,comissao,operador,obs,obs1,agencia,c_c,corrente,'+;
                                                                'doc_tran,com_sem,SR_DELETED )'+;
                                                                ' VALUES ('+;
                                                                sr_cdbvalue(aret[point,1])+','+; //1
                                                                sr_cdbvalue(aret[point,2])+','+; //2
                                                                sr_cdbvalue(aret[point,3])+','+; //3
                                                                sr_cdbvalue(aret[point,4])+','+; //4
                                                                sr_cdbvalue(aret[point,5])+','+; //5
                                                                sr_cdbvalue(aret[point,7])+','+; //6
                                                                sr_cdbvalue(aret[point,8])+','+; //7
                                                                sr_cdbvalue(aret[point,6])+','+; //8
                                                                sr_cdbvalue(aret[point,10])+','+;//9
                                                                sr_cdbvalue(IF(! EMPTY(aret[point,12]),aret[point,12],aret[point,11]))+','+;//10
                                                                sr_cdbvalue(IF(! EMPTY(mmulta) .OR. ! EMPTY(mjuros),mdatpag,aret[point,11]))+','+; //11
                                                                sr_cdbvalue((aret[point,19]+mmulta+mjuros)-mvlpago)+','+;//12
                                                                sr_cdbvalue(aret[point,30])+','+;//13
                                                                sr_cdbvalue(aret[point,31])+','+;//14
                                                                sr_cdbvalue('*')+','+;//15
                                                                sr_cdbvalue(mbanco)+','+;//16
                                                                sr_cdbvalue(iat(mcomissao,2))+','+;//17
                                                                sr_cdbvalue(cod_operado)+','+;//18
                                                                sr_cdbvalue(mobs)+','+;//19
                                                                sr_cdbvalue(mobs1)+','+;//20
                                                                sr_cdbvalue(aret[point,17])+','+;//21
                                                                sr_cdbvalue(aret[point,18])+','+;//22
                                                                sr_cdbvalue(aret[point,48])+','+;//23
                                                                sr_cdbvalue(aret[point,37])+','+;//24
                                                                sr_cdbvalue(aret[point,64])+','+;//28
                                                                sr_cdbvalue(' ')+')',,.f.)

                                                ENDIF
                                        ENDIF
                                        AADD(m_dup,aret[point,7]+' '+aret[point,2]+' '+aret[point,4]+' '+DTOC(aret[point,11])+' '+TRANSFORM(aret[point,19],'999,999.99')+' '+TRANSFORM(mjuros+mmulta,'999,999.99')+' '+TRANSFORM(mvlpago,'999,999.99')+' X')
                                        //AADD(m_po,{RECNO(),'X',(malias)->valor,mjuros+mmulta,mvlpago,'X'})
                                        IF cx <> NIL
                                                cComm  := "SELECT * FROM saccaixa WHERE tipo = "+sr_cdbvalue(mtipo)
                                                ccomm  := ccomm + " AND documento = "+sr_cdbvalue(mduplicata)
                                                ccomm  := ccomm + " AND cod_cli = "+sr_cdbvalue(STRZERO(mcod_cli,5))
                                                c_aret:={}
                                                sr_getconnection():exec(ccomm,,.t.,@c_aret)
                                                sr_getconnection():exec('COMMIT',,.f.)
                                                IF LEN(c_aret) > 0
                                                        mtipo_comp := c_aret[1,11]
                                                        mcod_vend  := c_aret[1,15]
                                                        mdescri1   := c_aret[1,13]
                                                        mdescri2   := c_aret[1,14]
                                                        ccomm := "UPDATE saccaixa SET op_pg = 'P'"
                                                        ccomm := ccomm + " WHERE tipo = "+sr_cdbvalue(mtipo)
                                                        ccomm  := ccomm + " AND documento = "+sr_cdbvalue(mduplicata)
                                                        ccomm  := ccomm + " AND cod_cli = "+sr_cdbvalue(STRZERO(mcod_cli,5))
                                                        sr_getconnection():exec(ccomm,,.f.)
                                                ENDIF
                                                sr_getconnection():exec('INSERT INTO saccaixa ('+;
                                                        'empresa,'+;
                                                        'tipo,'+;
                                                        'nota,'+;
                                                        'num_dup,'+;
                                                        'num_ban,'+;
                                                        'documento,'+;
                                                        'data,'+;
                                                        'descri1,'+;
                                                        'descri2,'+;
                                                        'venci,'+;
                                                        'valor,'+;
                                                        'cod_cli,'+;
                                                        'cod_vend,'+;
                                                        'cod_opera,'+;
                                                        'pg,'+;
                                                        'op_pg,'+;
                                                        'valor_com,'+;
                                                        'comissao,'+;
                                                        'hora,'+;
                                                        'tp_mov,SR_DELETED )'+;
                                                        ' VALUES ('+;
                                                        sr_cdbvalue(aret[point,1] )+','+; //1
                                                        sr_cdbvalue(aret[point,2] )+','+; //2
                                                        sr_cdbvalue('DOC.PG  '    )+','+; //3
                                                        sr_cdbvalue(aret[point,4] )+','+; //4
                                                        sr_cdbvalue(aret[point,3] )+','+; //5
                                                        sr_cdbvalue(aret[point,4] )+','+; //6
                                                        sr_cdbvalue(mdatpag       )+','+; //7
                                                        sr_cdbvalue(mdescri1      )+','+; //8
                                                        sr_cdbvalue(mdescri2      )+','+; //9
                                                        sr_cdbvalue(aret[point,11])+','+; //10
                                                        sr_cdbvalue(mvlpago       )+','+; //11
                                                        sr_cdbvalue(aret[point,7] )+','+; //12
                                                        sr_cdbvalue(mcod_vend     )+','+; //13
                                                        sr_cdbvalue(cod_operado   )+','+; //14
                                                        sr_cdbvalue('*'           )+','+; //15
                                                        sr_cdbvalue('P'           )+','+; //16
                                                        sr_cdbvalue(mvlpago       )+','+; //17
                                                        sr_cdbvalue(iat(mcomissao,5))+','+; //18
                                                        sr_cdbvalue(TIME()        )+','+; //19
                                                        sr_cdbvalue('B'           )+','+; //20
                                                        sr_cdbvalue(' ')+')',,.f.)
                                        ENDIF
                                        sr_getconnection():exec("COMMIT",,.f.)
                                        IF m_set[1,149] = 'R' .OR. m_set[1,149] = 'A'
                                                IF  m_set[1,149] = 'R'
                                                        mtipo_aut := 2
                                                ELSE
                                                        mtipo_aut := 1
                                                ENDIF
                                                op_tela(10,35,12,67,' Opcao de Autenticacoes ')
                                                @ 01,01 PROMPT ' Autenticar'
                                                @ 01,15 PROMPT ' Imprimir Recibo '
                                                SET INTEN ON
                                                MENU TO mtipo_aut
                                                wvw_lclosewindow()
                                                IF  mtipo_aut = 2
                                                        mdevedor:={}
                                                        sr_getconnection():exec("SELECT SUM(valor) FROM sacdupr WHERE fornec = "+sr_cdbvalue(STRZERO(mcod_cli,5)) +" AND datpag IS NULL",,.t.,@mdevedor)
                                                        sr_getconnection():exec('COMMIT',,.f.)
                                                        rec_dupr(m_dup,aret[point,65],1,mjuros+mmulta,mvlpago,mdatpag,mtp,aret[point,19],mdevedor[1,1]) //con252
                                                ENDIF
                                        ENDIF
                                        IF mlimp_cli = '*';mcod_cli:=0;ENDIF
                                        LOOP
                                ELSEIF mtp = 'S'
                                        setcor(3)
                                        @ lc+7,cc+28 SAY IF(mdias_atras<0,TRANSFORM(0,'9999'),TRANSFORM(mdias_atras,'9999'))
                                        @ lc+8,cc+28 SAY aret[point,13]
                                        @ lc+10,cc+28 SAY "             "
                                        @ lc+11,cc+28 SAY aret[point,23] PICT "99,999,999.99"
                                        @ lc+12,cc+28 SAY aret[point,20] PICT "99,999,999.99"
                                        @ lc+13,cc+28 SAY aret[point,26]
                                        @ lc+14,cc+28 SAY aret[point,29]
                                        @ lc+16,cc+12 SAY aret[point,46]
                                        @ lc+16,cc+12 SAY aret[point,47]
                                        setcor(1)
                                        opcao := op_simnao('S','Confirma os Dados:')
                                        IF opcao = "N"
                                                LOOP
                                        ENDIF
                                        IF mtp_tp = NIL
                                                ccomm :="UPDATE sacdupr SET datope = NULL,datpag = NULL,vlpago = "+sr_cdbvalue(0)+",pago = NULL,juros = "+sr_cdbvalue(0)+",cheque = "+sr_cdbvalue(SPACE(8))+",operador = "+sr_cdbvalue(cod_operado)+",obs = "+sr_cdbvalue(mobs)+" WHERE SR_RECNO = "+sr_cdbvalue(aret[point,65])
                                        ELSE
                                                ccomm :="UPDATE saccred SET datope = NULL,datpag = NULL,vlpago = "+sr_cdbvalue(0)+",pago = NULL,juros = "+sr_cdbvalue(0)+",cheque = "+sr_cdbvalue(SPACE(8))+",operador = "+sr_cdbvalue(cod_operado)+",obs = "+sr_cdbvalue(mobs)+" WHERE SR_RECNO = "+sr_cdbvalue(aret[point,65])
                                        ENDIF
                                        sr_getconnection():exec(ccomm,,.f.)
                                        IF aret[point,2] = 'CH'
                                                IF ! EMPTY(aret[point,39]) .AND. 'S' = op_simnao('N','Deseja Estorna a BAIXA PARCIAL:') .AND. mtp_tp = NIL
	                                                ccomm :="UPDATE sacdupr SET baix_parc = NULL,cod_forn = NULL,forn_desp = '' WHERE SR_RECNO = "+sr_cdbvalue(aret[point,65])
		                                        sr_getconnection():exec(ccomm,,.f.)
                                                ENDIF
                                        ENDIF
                                        IF aret[point,27] = 'C'
                                                sr_getconnection():exec("DELETE FROM saccaixa WHERE tipo = "+sr_cdbvalue(aret[point,2])+" AND num_dup = "+sr_cdbvalue(aret[point,4])+" AND cod_cli = "+sr_cdbvalue(aret[point,7])+" AND pg = '*'",,.f.)
                                                sr_getconnection():exec("DELETE FROM saccaixa WHERE SR_DELETED = 'T'",,.f.)
                                        ENDIF
                                        sr_getconnection():exec("COMMIT",,.f.)
                                        LOOP
                                ELSEIF mtp = 'E'
                                        setcor(3)
                                        @ lc+7,cc+28 SAY IF(mdias_atras<0,TRANSFORM(0,'9999'),TRANSFORM(mdias_atras,'9999'))
                                        @ lc+8,cc+28 SAY aret[point,13]
                                        @ lc+10,cc+28 SAY "             "
                                        @ lc+11,cc+28 SAY aret[point,23] PICT "99,999,999.99"
                                        @ lc+12,cc+28 SAY aret[point,20] PICT "99,999,999.99"
                                        @ lc+13,cc+28 SAY aret[point,26]
                                        @ lc+14,cc+28 SAY aret[point,29]
                                        @ lc+16,cc+12 SAY aret[point,46]
                                        @ lc+16,cc+12 SAY aret[point,47]

                                        setcor(1)
                                        opcao := op_simnao('N','Confirma a EXCLUSAO do Documento:')
                                        IF opcao = "N"
                                                LOOP
                                        ENDIF
                                        IF mtp_tp = NIL
                                                ccomm :="DELETE FROM sacdupr WHERE SR_RECNO = "+sr_cdbvalue(aret[point,65])
                                        ELSE
                                                ccomm :="DELETE FROM saccred WHERE SR_RECNO = "+sr_cdbvalue(aret[point,65])
                                        ENDIF
                                        sr_getconnection():exec(ccomm,,.f.)
                                        sr_getconnection():exec('INSERT INTO saclog (data_sis,data,hora,tipo,documento,aut_oper,cod_oper,modulo,descri,cod_aut,terminal,cod_cli,valor1,valor2,venc1,venc2'+;
                                                ',SR_DELETED )'+;
                                                ' VALUES ('+;
                                                sr_cdbvalue(DATE()       )+','+; //1
                                                sr_cdbvalue(mdata_sis    )+','+; //2
                                                sr_cdbvalue(TIME()       )+','+; //3
                                                sr_cdbvalue('EXCL_DUPLI')+','+; //4
                                                sr_cdbvalue(mduplicata)+','+; //5
                                                sr_cdbvalue(cod_operado  )+','+; //7
                                                sr_cdbvalue(cod_operado  )+','+; //8
                                                sr_cdbvalue('CON212'     )+','+;//9
                                                sr_cdbvalue('EXCLUSAO DE DUPLICATA')+','+;//10
                                                sr_cdbvalue(cod_operado  )+','+; //11
                                                sr_cdbvalue(LEFT(NETNAME(),15))+','+; //12
                                                sr_cdbvalue(STRZERO(mcod_cli,5))+','+; //12
                                                sr_cdbvalue(aret[point,19])+','+; //12
                                                sr_cdbvalue(aret[point,19])+','+; //12
                                                sr_cdbvalue(aret[point,11])+','+; //12
                                                sr_cdbvalue(aret[point,11])+','+; //12
                                                sr_cdbvalue(' ')+')',,.f.)
                                        sr_getconnection():exec("COMMIT",,.f.)
                                        LOOP
                                ELSEIF mtp = 'I'
                                        mqtd_cop := 1
                                        mtipo_dup := 'S'
                                        setcor(1)
                                        @ lc+18,cc+36 GET mtipo_dup PICT "@!" VALID mtipo_dup $ 'S,P'
                                        @ lc+19,cc+36 GET mqtd_cop PICT "9" VALID IF(EMPTY(mqtd_cop),.F.,.T.)
                                        READ
                                        IF LASTKEY() = 27 
                                                LOOP
                                        ENDIF
                                        opcao := op_simnao('N','Confirma a IMPRESSAO do Documento:')
                                        IF opcao = "N"
                                                LOOP
                                        ENDIF
                                        IF ! imp_arq('DUPLICATA.REL','D');LOOP;ENDIF
                                        cons_cli:={}
                                        sr_getconnection():exec("SELECT * FROM saccli WHERE cod_cli = "+sr_cdbvalue(aret[point,7]),,.t.,@cons_cli)
                                        sr_getconnection():exec('COMMIT',,.f.)
                                        IF mtipo_dup = 'P'
                                                IF ver_serie() = '141236' // SOTINTAS
                                                        dup_sot(mdata_sis,VAL(aret[point,30]),aret[point,19],aret[point,4],aret[point,11],cons_cli[1,3],aret[point,7],cons_cli[1,21],;
                                                                cons_cli[1,22],cons_cli[1,24],cons_cli[1,25],cons_cli[1,26],cons_cli[1,32],cons_cli[1,33],cons_cli[1,34],aret[point,16])
                                                ELSE
                                                        imprt(mtipo_imp,'C')
                                                        @ PROW()+10,21 SAY aret[point,4]
                                                        DEVPOS(PROW(),40);DEVOUT(TRANSFORM(iat(aret[point,19],2),'99,999,999.99'))
                                                        @ PROW(),60 SAY aret[point,4]
                                                        DEVPOS(PROW(),80);DEVOUT(TRANSFORM(iat(aret[point,19],2),'99,999,999.99'))
                                                        @ PROW(),99 SAY aret[point,11]
                                                        @ PROW()+3,65 SAY STRZERO(aret[point,11]-mdata_sis,3)+' dias'
                                                        @ PROW()+3,60 SAY cons_cli[1,2]
                                                        @ PROW(),PCOL()+1 SAY cons_cli[1,3]
                                                        @ PROW()+1,60 SAY cons_cli[1,21]
                                                        @ PROW()+1,60 SAY RTRIM(cons_cli[1,22])+'-Cidade: '+RTRIM(cons_cli[1,24])
                                                        @ PROW(),110 SAY cons_cli[1,25]
                                                        @ PROW()+1,60 SAY 'Cobranca Bancaria'
                                                        IF cons_cli[1,32] <> SPACE(14)
                                                                DEVPOS(PROW()+1,60);DEVOUTPICT(cons_cli[1,32],'@@R 99.999.999/9999-99')
                                                                DEVPOS(PROW(),100);DEVOUT(cons_cli[1,33])
                                                        ELSEIF cons_cli[1,34] <> SPACE(11)
                                                                DEVPOS(PROW()+1,60);DEVOUTPICT(cons_cli[1,34],'@@R 999.999.999-99')
                                                        ELSE
                                                                DEVPOS(PROW()+1,00);DEVOUT(' ')
                                                        ENDIF
                                                        mextenso:= '('+RTRIM(extenso(iat(aret[point,19],2),.T.,'real','reais'))+')'
                                                        mlinha := MLCOUNT(mextenso,50)
                                                        DEVPOS(PROW()+1,00);DEVOUT(' ')
                                                        FOR lin = 1 TO mlinha
                                                                mlin := MEMOLINE(mextenso,50,lin,,10)
                                                                DEVPOS(PROW()+1,60);DEVOUT(PADR(RTRIM(mlin),50))
                                                        NEXT
                                                        imprt(mtipo_imp,'N')
                                                ENDIF
                                        ELSE
                                                FOR i = 1 TO mqtd_cop
                                                        dup_sis(cons_cli[1,2],cons_cli[1,3],cons_cli[1,21],cons_cli[1,22],cons_cli[1,24],cons_cli[1,25],cons_cli[1,26],cons_cli[1,29],;
                                                                cons_cli[1,32],cons_cli[1,33],cons_cli[1,34],cons_cli[1,100],cons_cli[1,101],cons_cli[1,102],cons_cli[1,103],cons_cli[1,104],cons_cli[1,105],;
                                                                aret[point,2],aret[point,4],aret[point,10],aret[point,11],VAL(aret[point,30]),aret[point,19],cons_cli[1,4],'          ',aret[point,19])
                                                NEXT
                                        ENDIF
                                        SETPRC(00,00)
                                        SET DEVI TO SCREEN;SET PRINT TO;SET PRINT OFF

                                        conf_impressao('DUPLICATA.REL')
                                        LOOP
                                ELSEIF mtp = 'A' .OR. mtp = 'P'
                                        lba := 22
                                        cba := 79
                                        IF mtp = 'A'
                                                op_tela(00,10,21,89," ALTERACAO DE DOCUMENTO (Contas a Receber) ",,'*')
                                        ELSE
                                                op_tela(00,10,35,89," PROCESSO DE DOCUMENTO (Contas a Receber) ")
                                                mportador := SPACE(20)
                                                mprevisao := CTOD('  /  /  ')
                                        ENDIF
                                        DEVPOS(1,2);DEVOUT('Codigo da Empresa......:')
                                        DEVPOS(2,2);DEVOUT('Tipo Documentos........:')
                                        DEVPOS(3,2);DEVOUT('No.Banco/Cod.Cartao....:')
                                        DEVPOS(3,32);DEVOUT('Agencia:')
                                        DEVPOS(3,51);DEVOUT('C/C:')
                                        DEVPOS(4,2);DEVOUT('Numero Documentos......:')
                                        DEVPOS(5,2);DEVOUT('Codigo do Cliente......:')
                                        DEVPOS(6,2);DEVOUT('Data de Emissao........:')
                                        DEVPOS(7,2);DEVOUT('Data de Vencimento.....:')
                                        DEVPOS(8,2);DEVOUT('Valor Documento R$.....:')
                                        DEVPOS(9,2);DEVOUT('Pag. [C]arteria [B]anco:')
                                        DEVPOS(10,2);DEVOUT('Codigo do Vendedor.....:')
                                        DEVPOS(11,2);DEVOUT('Numero do Pedido/NF....:')
                                        DEVPOS(12,2);DEVOUT('% de Comissao .........:')
                                        DEVPOS(13,2);DEVOUT('Nome do Correntista....:')
                                        DEVPOS(14,2);DEVOUT('Tipo de Operacao.......:')
                                        DEVPOS(15,2);DEVOUT('OBS.:')
                                        DEVPOS(16,2);DEVOUT('Processo:')
                                        mfornec=VAL(aret[point,7])
                                        mnome_cli := aret[point,8]
                                        memissao=aret[point,10]
                                        mvenc=aret[point,11]
                                        mvalor=aret[point,19]
                                        mtipo=aret[point,2]
                                        mcod_ven := VAL(aret[point,30])
                                        mnum_ped := VAL(aret[point,31])
                                        mbanco := SUBSTR(aret[point,16],1,1)
                                        mnum_banco := VAL(aret[point,3])
                                        mcomissao := aret[point,32] * 100
                                        magencia := aret[point,17]
                                        mc_c := aret[point,18]
                                        mcorrente := aret[point,48]
                                        mobs := aret[point,46]
                                        mtip_pg := aret[point,26]
                                        mlin1 := aret[point,58]
                                        mlin2 := aret[point,59]
                                        mlin3 := aret[point,60]
                                        mlin4 := aret[point,61]
                                        mlin5 := aret[point,62]
                                        mensagem('Complete os Dados. [ESC] Abandona.')
                                        IF RTRIM(mnome_cli) = 'DIVERSOS'
                                                mnome_cli := aret[point,8]
                                                setcor(3)
                                                DEVPOS(5,32);DEVOUT(mnome_cli)
                                                setcor(1)
                                        ENDIF
                                        @ 2,27 GET mtipo PICT '@!' VALID IF(EMPTY(mtipo),.F.,ver_tipdc(mtipo,'*')) WHEN mtp <> 'P'
                                        @ 3,27 GET mnum_banco PICT '999' WHEN (mtipo = 'CH' .AND. mtp <> 'P') .OR. ver_serie() = '141235'
                                        @ 3,41 GET magencia PICT '@!' WHEN mtipo = 'CH' .AND. mtp <> 'P'
                                        @ 3,56 GET mc_c PICT '@!' VALID qtd_chq(mfornec,STRZERO(mnum_banco,3),magencia,mc_c) WHEN mtp <> 'P' .AND. mtipo = 'CH'
                                        @ 4,27 GET mduplicata PICT '@!' WHEN mtp <> 'P'
                                        @ 5,27 GET mfornec PICT "99999" VALID mcli(mfornec,5,27) WHEN mtp <> 'P'
                                        READ
                                        IF LASTKEY()=27
                                                wvw_lclosewindow()
                                                LOOP
                                        ENDIF

                                        IF RTRIM(mnome_cli) = 'DIVERSOS'
                                                mnome_cli := aret[point,8]
                                                @ 5,32 GET mnome_cli PICT '@!' WHEN mtp <> 'P'
                                        ELSE
                                                mnome_cli := cli->razao
                                        ENDIF
                                        @ 6,27 GET memissao WHEN mtp <> 'P'
                                        @ 7,27 GET mvenc VALID IF(EMPTY(mvenc),.F.,.T.) WHEN mtp <> 'P'
                                        @ 8,27 GET mvalor PICT "@E 99,999,999,999.99" VALID mvalor>0 WHEN mtp <> 'P'
                                        @ 9,27 GET mbanco PICT "@!" VALID mbanco $ 'C,B' .AND. lim_get() WHEN mtp <> 'P' .AND. men_get(10,31,'Digite [C] para pagamento em CARTEIRA [B] para pagamento em BANCO"')
                                        @ 10,27 GET mcod_ven PICT "999" VALID ven(mcod_ven,10,31) .AND. lim_get() WHEN mtp <> 'P' .AND. men_get(11,31,'Informe o Cod. do vendedor "CAMPO NAO OBRIGATORIO"')
                                        @ 11,27 GET mnum_ped PICT "999999" VALID lim_get() WHEN mtp <> 'P' .AND. men_get(12,31,'Informe o No.do pedido que corresponde a este documento "CAMPO NAO OBRIGATORIO"')
                                        @ 12,27 GET mcomissao PICT "999.99" VALID lim_get() WHEN mtp <> 'P' .AND. men_get(13,31,'Informe o percentual de comissao do vendedor para este documento')
                                        @ 13,27 GET mcorrente PICT "@!" VALID lim_get() WHEN mtp <> 'P' .AND. men_get(14,31,'Informe o nome do correntista')
                                        @ 14,27 GET mtip_pg PICT "@!" VALID lim_get() WHEN mtp <> 'P' .AND. men_get(15,31,'Informe o Tipo de Operacao')
                                        @ 15,07 GET mobs WHEN mtp <> 'P'
                                        READ
                                        setcor(3)
                                        @ lc+15,cc+07 SAY mobs
                                        setcor(1)
                                        @ 16,11 GET mlin1 WHEN mtp <> 'P'
                                        @ 17,11 GET mlin2 WHEN mtp <> 'P'
                                        @ 18,11 GET mlin3 WHEN mtp <> 'P'
                                        @ 19,11 GET mlin4 WHEN mtp <> 'P'
                                        @ 20,11 GET mlin5 WHEN mtp <> 'P'
                                        READ
                                        IF LASTKEY()=27
                                                wvw_lclosewindow()
                                                LOOP
                                        ENDIF
                                        IF mtp = 'A'
                                                IF EMPTY(mvenc)
                                                        atencao('Favor Verificar o VENCIMENTO deste documento para poder Prossegir...')
                                                        LOOP
                                                ENDIF
                                                opcao := op_simnao('S','Confirma os Dados:')
                                                IF opcao = "N"
                                                        wvw_lclosewindow()
                                                        LOOP
                                                ENDIF
                                                IF mtp_tp = NIL
                                                        sr_getconnection():exec("UPDATE sacdupr SET tipo    = " + sr_cdbvalue(mtipo)+;
                                                                ",numero  = " + sr_cdbvalue(IF((EMPTY(mnum_banco) .OR. mtipo = 'DU') .AND. ver_serie() <> '141235',' ',STRZERO(mnum_banco,3)))+;
                                                                ",agencia = " + sr_cdbvalue(magencia)  +;
                                                                ",c_c = " + sr_cdbvalue(mc_c)  +;
                                                                ",duplicata   = " + sr_cdbvalue(mduplicata)  +;
                                                                ",tip_cli = " + sr_cdbvalue(cli->tipo)  +;
                                                                ",fornec = " + sr_cdbvalue(STRZERO(mfornec,5))+;
                                                                ",cliente  = " + sr_cdbvalue(mnome_cli)+;
                                                                ",emissao   = " + sr_cdbvalue(memissao)+;
                                                                ",venc  = " + sr_cdbvalue(mvenc)+;
                                                                ",valor_dup = " + sr_cdbvalue(mvalor)+;
                                                                ",valor  = " + sr_cdbvalue(mvalor)+;
                                                                ",vendedor  = " + sr_cdbvalue(STRZERO(mcod_ven,3))+;
                                                                ",num_ped= " + sr_cdbvalue(STRZERO(mnum_ped,6))+;
                                                                ",banco= " + sr_cdbvalue(mbanco)+;
                                                                ",comissao= " + sr_cdbvalue(mcomissao/100)+;
                                                                ",corrente= " + sr_cdbvalue(mcorrente)+;
                                                                ",tip_pg= " + sr_cdbvalue(mtip_pg)+;
                                                                ",alt_oper= " + sr_cdbvalue(cod_operado)+;
                                                                ",obs= " + sr_cdbvalue(mobs)+;
                                                                ",lin1= " + sr_cdbvalue(mlin1)+;
                                                                ",lin2= " + sr_cdbvalue(mlin2)+;
                                                                ",lin3= " + sr_cdbvalue(mlin3)+;
                                                                ",lin4= " + sr_cdbvalue(mlin4)+;
                                                                ",lin5= " + sr_cdbvalue(mlin5)+;
                                                                ",operador= " + sr_cdbvalue(cod_operado)+;
                                                                ",mov_cx = " + sr_cdbvalue(IF(cx <> NIL,'C','M'))+;
                                                                " WHERE sr_recno = " + sr_cdbvalue(aret[point,65]),,.f.)
                                                        sr_getconnection():exec('INSERT INTO saclog (data_sis,data,hora,tipo,documento,aut_oper,cod_oper,modulo,descri,cod_aut,terminal,cod_cli,valor1,valor2,venc1,venc2'+;
                                                                ',SR_DELETED )'+;
                                                                ' VALUES ('+;
                                                                sr_cdbvalue(DATE()       )+','+; //1
                                                                sr_cdbvalue(mdata_sis    )+','+; //2
                                                                sr_cdbvalue(TIME()       )+','+; //3
                                                                sr_cdbvalue('ALT_DUPLI')+','+; //4
                                                                sr_cdbvalue(mduplicata)+','+; //5
                                                                sr_cdbvalue(cod_operado  )+','+; //7
                                                                sr_cdbvalue(cod_operado  )+','+; //8
                                                                sr_cdbvalue('CON212'     )+','+;//9
                                                                sr_cdbvalue('ALTERACAO DE DUPLICATA No.: '+aret[point,4])+','+;//10
                                                                sr_cdbvalue(cod_operado  )+','+; //11
                                                                sr_cdbvalue(LEFT(NETNAME(),15))+','+; //12
                                                                sr_cdbvalue(STRZERO(mfornec,5))+','+; //12
                                                                sr_cdbvalue(aret[point,19])+','+; //12
                                                                sr_cdbvalue(mvalor)+','+; //12
                                                                IF(EMPTY(aret[point,11]),'NULL',sr_cdbvalue(aret[point,11]))+','+; //12
                                                                sr_cdbvalue(mvenc)+','+; //12
                                                                sr_cdbvalue(' ')+')',,.f.)
                                                        sr_getconnection():exec("COMMIT",,.f.)
                                                ELSE
                                                        sr_getconnection():exec("UPDATE saccred SET tipo    = " + sr_cdbvalue(mtipo)+;
                                                                ",numero  = " + sr_cdbvalue(IF((EMPTY(mnum_banco) .OR. mtipo = 'DU') .AND. ver_serie() <> '141235',' ',STRZERO(mnum_banco,3)))+;
                                                                ",agencia = " + sr_cdbvalue(magencia)  +;
                                                                ",c_c = " + sr_cdbvalue(mc_c)  +;
                                                                ",duplicata   = " + sr_cdbvalue(mduplicata)  +;
                                                                ",tip_cli = " + sr_cdbvalue(cli->tipo)  +;
                                                                ",fornec = " + sr_cdbvalue(STRZERO(mfornec,5))+;
                                                                ",cliente  = " + sr_cdbvalue(mnome_cli)+;
                                                                ",emissao   = " + sr_cdbvalue(memissao)+;
                                                                ",venc  = " + sr_cdbvalue(mvenc)+;
                                                                ",valor_dup = " + sr_cdbvalue(mvalor)+;
                                                                ",valor  = " + sr_cdbvalue(mvalor)+;
                                                                ",vendedor  = " + sr_cdbvalue(STRZERO(mcod_ven,3))+;
                                                                ",num_ped= " + sr_cdbvalue(STRZERO(mnum_ped,6))+;
                                                                ",banco= " + sr_cdbvalue(mbanco)+;
                                                                ",comissao= " + sr_cdbvalue(mcomissao/100)+;
                                                                ",corrente= " + sr_cdbvalue(mcorrente)+;
                                                                ",tip_pg= " + sr_cdbvalue(mtip_pg)+;
                                                                ",alt_oper= " + sr_cdbvalue(cod_operado)+;
                                                                ",obs= " + sr_cdbvalue(mobs)+;
                                                                ",lin1= " + sr_cdbvalue(mlin1)+;
                                                                ",lin2= " + sr_cdbvalue(mlin2)+;
                                                                ",lin3= " + sr_cdbvalue(mlin3)+;
                                                                ",lin4= " + sr_cdbvalue(mlin4)+;
                                                                ",lin5= " + sr_cdbvalue(mlin5)+;
                                                                ",operador= " + sr_cdbvalue(cod_operado)+;
                                                                ",mov_cx = " + sr_cdbvalue(IF(cx <> NIL,'C','M'))+;
                                                                " WHERE sr_recno = " + sr_cdbvalue(aret[point,65]),,.f.)
                                                        sr_getconnection():exec("COMMIT",,.f.)
                                                ENDIF
                                        ELSEIF mtp = 'P'
                                                mportador := SPACE(20)
                                                mprevisao := CTOD('  /  /  ')
                                                op_tela(19,00,31,100,' PROCESSO DO DOCUMENTO: '+mtipo+mduplicata,,'*')
                                                setcor(3)
                                                DEVPOS(00,00);DEVOUT('  Data    Assunto                                                       Portador           Previsao')
                                                @ 01,00 TO 01,100
                                                setcor(1)
                                                WHILE .T.
                                                        m_hist  := {}
                                                        m_ponto := {}
                                                        cComm  := "SELECT * FROM saccliproce WHERE documento = "+sr_cdbvalue(mduplicata)+" AND tipo = "+sr_cdbvalue(mtipo)+" AND codcli = " + sr_cdbvalue(STRZERO(mfornec,5))
                                                        ccomm := ccomm + " ORDER BY data"
                                                        cons_processo:={}
                                                        sr_getconnection():exec(ccomm,,.t.,@cons_processo)
                                                        sr_getconnection():exec('COMMIT',,.f.)
                                                        IF LEN(cons_processo) > 0
                                                                AADD(m_hist,DTOC(cons_processo[1,1])+' '+cons_processo[1,6]+' '+cons_processo[1,7]+' '+DTOC(cons_processo[1,8]))
                                                                AADD(m_ponto,cons_processo[1,10])
                                                                mdata_con := cons_processo[1,1]
                                                                i:=0
                                                                FOR i = 2 TO LEN(cons_processo)
                                                                        IF mdata_con = cons_processo[i,1]
                                                                                AADD(m_hist,'         '+cons_processo[i,6]+' '+cons_processo[i,7]+' '+DTOC(cons_processo[i,8]))
                                                                                AADD(m_ponto,cons_processo[i,10])
                                                                        ELSE
                                                                                AADD(m_hist,REPLI('-',100))
                                                                                AADD(m_ponto,0)
                                                                                AADD(m_hist,DTOC(cons_processo[i,1])+' '+cons_processo[i,6]+' '+cons_processo[i,7]+' '+DTOC(cons_processo[i,8]))
                                                                                AADD(m_ponto,cons_processo[i,10])
                                                                                mdata_con := cons_processo[i,1]
                                                                        ENDIF
                                                                NEXT
                                                                AADD(m_hist,PADC('****************************  F  I  M  ****************************',100))
                                                                AADD(m_ponto,0)
                                                                mponto := LEN(m_hist)
                                                                Mensagem('<ENTER> p/alterar ou <ESC>p/Inclusao')
                                                                mponto := ACHOICE(02,00,14,99,m_hist,,,mponto)
                                                                IF LASTKEY() = 13
                                                                        IF m_ponto[mponto] = 0
                                                                                LOOP
                                                                        ENDIF
                                                                        mlin1 := cons_processo[mponto,6]
                                                                        mdata_con := cons_processo[mponto,1]
                                                                        mportador := cons_processo[mponto,7]
                                                                        mprevisao := cons_processo[mponto,8]
                                                                        op_tela(10,10,13,90,' ALTERACAO PROCESSO ')
                                                                        setcor(1)
                                                                        DEVPOS(01,01);DEVOUT('Protador:')
                                                                        DEVPOS(02,01);DEVOUT('Previsao:')
                                                                        DEVPOS(03,01);DEVOUT('Data....:')
                                                                        DEVPOS(03,19);DEVOUT('-')
                                                                        mensagem('Preencha a Data ou <ESC> p/Abandonar')
                                                                        @ 01,11 GET mportador PICT '@!'
                                                                        @ 02,11 GET mprevisao
                                                                        @ 03,11 GET mdata_con
                                                                        @ 03,21 GET mlin1
                                                                        READ
                                                                        IF LASTKEY() = 27
                                                                                wvw_lclosewindow()
                                                                                EXIT
                                                                        ENDIF
                                                                        IF EMPTY(mlin1)
                                                                                opcao := op_simnao('N','Confirma a Exclusao:')
                                                                                IF LASTKEY() = 27 .OR. opcao = 'N'
                                                                                        wvw_lclosewindow()
                                                                                        LOOP
                                                                                ENDIF
                                                                                sr_getconnection():exec("DELETE FROM saccliproce WHERE SR_RECNO = "+sr_cdbvalue(cons_processo[mponto,10]),,.f.)
                                                                                sr_getconnection():exec("COMMIT",,.f.)
                                                                        ELSE
                                                                                opcao := op_simnao('S','Confirma a Alteracao:')
                                                                                IF opcao = 'N'
                                                                                        wvw_lclosewindow()
                                                                                        LOOP
                                                                                ENDIF
                                                                                ccomm := "UPDATE saccliproce SET data = "+sr_cdbvalue(mdata_con)
                                                                                ccomm := ccomm + ",descricao = "+sr_cdbvalue(mlin1)
                                                                                ccomm := ccomm + ",portador = "+sr_cdbvalue(mportador)
                                                                                ccomm := ccomm + ",previsao = "+IF(! EMPTY(mprevisao),sr_cdbvalue(mprevisao),'NULL')
                                                                                ccomm := ccomm + ",operador = "+sr_cdbvalue(cod_operado)
                                                                                ccomm := ccomm + " WHERE SR_RECNO = "+sr_cdbvalue(cons_processo[mponto,10])
                                                                                sr_getconnection():exec(ccomm,,.f.)
                                                                                sr_getconnection():exec("COMMIT",,.f.)

                                                                        ENDIF
                                                                        wvw_lclosewindow()
                                                                        LOOP
                                                                ELSE
                                                                        mlin1 := SPACE(60)
                                                                        mdata_con := mdata_sis
                                                                        mportador := SPACE(20)
                                                                        mprevisao := CTOD('  /  /  ')
                                                                        op_tela(10,10,23,90,' INCLUSAO PROCESSO ')
                                                                        setcor(1)
                                                                        DEVPOS(01,01);DEVOUT('Protador:')
                                                                        DEVPOS(02,01);DEVOUT('Previsao:')
                                                                        DEVPOS(03,01);DEVOUT('Data....:')
                                                                        DEVPOS(03,19);DEVOUT('-')
                                                                        mensagem('Preencha a Data ou <ESC> p/Abandonar')
                                                                        @ 01,11 GET mportador PICT '@!'
                                                                        @ 02,11 GET mprevisao
                                                                        @ 03,11 GET mdata_con
                                                                        READ
                                                                        IF LASTKEY() = 27
                                                                                wvw_lclosewindow()
                                                                                EXIT
                                                                        ENDIF
                                                                        Mensagem('Descrevar e tecle <F10>p/Gravar ou <ESC>p/abandonar')
                                                                        setcor(3)
                                                                        mlin1 := MEMOEDIT(mlin2,03,21,22,89,,,,,,)
                                                                        setcor(1)
                                                                        IF LASTKEY() = 27
                                                                                wvw_lclosewindow()
                                                                                LOOP
                                                                        ENDIF
                                                                        i := 0
                                                                        linhas := MLCOUNT(mlin1,60)
                                                                        FOR i = 1 TO  linhas
                                                                                mlin3 := MEMOLINE(mlin1,60,i,,)
                                                                                sr_getconnection():exec('INSERT INTO saccliproce ('+;
                                                                                        'data,'+;
                                                                                        'hora,'+;
                                                                                        'codcli,'+;
                                                                                        'tipo,'+;
                                                                                        'documento,'+;
                                                                                        'descricao,'+;
                                                                                        'portador,'+;
                                                                                        'previsao,'+;
                                                                                        'operador,'+;
                                                                                        'SR_DELETED )'+;
                                                                                        ' VALUES ('+;
                                                                                        sr_cdbvalue(mdata_con)+','+; //1
                                                                                        sr_cdbvalue(TIME()   )+','+; //2
                                                                                        sr_cdbvalue(STRZERO(mfornec,5))+','+; //3
                                                                                        sr_cdbvalue(mtipo)+','+; //4
                                                                                        sr_cdbvalue(mduplicata)+','+; //5
                                                                                        sr_cdbvalue(mlin3)+','+; //6
                                                                                        sr_cdbvalue(mportador)+','+; //6
                                                                                        IF(! EMPTY(mprevisao),sr_cdbvalue(mprevisao),'NULL')+','+; //7
                                                                                        sr_cdbvalue(cod_operado)+','+; //6
                                                                                        sr_cdbvalue(' ')+')',,.f.)
                                                                        NEXT
                                                                        sr_getconnection():exec("COMMIT",,.f.)
                                                                        wvw_lclosewindow()
                                                                ENDIF
                                                        ELSE
                                                                mlin1 := mlin2 := SPACE(60)
                                                                mdata_con := mdata_sis
                                                                mportador := SPACE(20)
                                                                mprevisao := CTOD('  /  /  ')
                                                                op_tela(10,10,23,90,' INCLUSAO PROCESSO ')
                                                                DEVPOS(01,01);DEVOUT('Protador:')
                                                                DEVPOS(02,01);DEVOUT('Previsao:')
                                                                DEVPOS(03,01);DEVOUT('Data....:')
                                                                DEVPOS(03,19);DEVOUT('-')
                                                                mensagem('Preencha a Data ou <ESC> p/Abandonar')
                                                                @ 01,11 GET mportador PICT '@!'
                                                                @ 02,11 GET mprevisao
                                                                @ 03,11 GET mdata_con
                                                                READ
                                                                IF LASTKEY() = 27
                                                                        wvw_lclosewindow()
                                                                        EXIT
                                                                ENDIF
                                                                Mensagem('Descrevar e tecle <F10>p/Gravar ou <ESC>p/abandonar')
                                                                setcor(3)
                                                                mlin1 := MEMOEDIT(mlin2,03,21,22,89,,,,,,)
                                                                setcor(1)
                                                                IF LASTKEY() = 27
                                                                        wvw_lclosewindow()
                                                                        LOOP
                                                                ENDIF
                                                                i := 0
                                                                linhas := MLCOUNT(mlin1,60)
                                                                FOR i = 1 TO  linhas
                                                                        mlin3 := MEMOLINE(mlin1,60,i,,)
                                                                        sr_getconnection():exec('INSERT INTO saccliproce ('+;
                                                                                'data,'+;
                                                                                'hora,'+;
                                                                                'codcli,'+;
                                                                                'tipo,'+;
                                                                                'documento,'+;
                                                                                'descricao,'+;
                                                                                'portador,'+;
                                                                                'previsao,'+;
                                                                                'operador,'+;
                                                                                'SR_DELETED )'+;
                                                                                ' VALUES ('+;
                                                                                sr_cdbvalue(mdata_con)+','+; //1
                                                                                sr_cdbvalue(TIME()   )+','+; //2
                                                                                sr_cdbvalue(STRZERO(mfornec,5))+','+; //3
                                                                                sr_cdbvalue(mtipo)+','+; //4
                                                                                sr_cdbvalue(mduplicata)+','+; //5
                                                                                sr_cdbvalue(mlin3)+','+; //6
                                                                                sr_cdbvalue(mportador)+','+; //6
                                                                                IF(! EMPTY(mprevisao),sr_cdbvalue(mprevisao),'NULL')+','+; //7
                                                                                sr_cdbvalue(cod_operado)+','+; //6
                                                                                sr_cdbvalue(' ')+')',,.f.)
                                                                NEXT
                                                                sr_getconnection():exec("COMMIT",,.f.)
                                                                wvw_lclosewindow()
                                                        ENDIF
                                                ENDDO
                                                wvw_lclosewindow()
                                        ENDIF
                                        IF memissao = mvenc .AND. mtp = 'A'
                                                opcao := op_simnao('S','Deseja fazer a BAIXA deste documento agora [S/n]:')
                                                IF opcao = 'S'
                                                        sr_getconnection():exec("UPDATE sacdupr SET datope = " + sr_cdbvalue(mdata_sis)  +;
                                                                ",datpag  = " + sr_cdbvalue(mvenc)+;
                                                                ",vlpago= " + sr_cdbvalue(mvalor)+;
                                                                ",banco= " + sr_cdbvalue('C')+;
                                                                ",pago= " + sr_cdbvalue('B')+;
                                                                ",hora_bx  = " + sr_cdbvalue(TIME())+;
                                                                " WHERE sr_recno = " + sr_cdbvalue(aret[point,65]),,.f.)
                                                        sr_getconnection():exec("COMMIT",,.f.)
                                                ENDIF
                                        ENDIF
                                        *****************
                                        SELE(malias);ORDSETFOCUS(1)
                                        *****************
                                        //DBUNLOCKALL()
                                        //DBCOMMITALL()
                                        IF mtp = 'P'
                                                wvw_lclosewindow()
                                                LOOP
                                        ENDIF
                                        IF ver_serie() = '975976'
                                                opcao := op_simnao('S','Deseja Imprimir o RECIBO [S/n]:')
                                                IF opcao = 'N'
                                                        wvw_lclosewindow()
                                                        LOOP
                                                ENDIF
                                                sac63(mnome_cli,mvalor,mvenc)
                                                LOOP
                                        ENDIF
                                        IF ! imp_arq('ALT_DUPR.REL','D')
                                                wvw_lclosewindow()
                                                LOOP
                                        ENDIF
                                        IF ver_serie() = '141236'
                                                dup_sot(aret[point,10],aret[point,35],aret[point,5],aret[point,4],aret[point,11],;
                                                        aret[point,8],mfornec,cli->endereco,cli->bairro,cli->cidade,;
                                                        cli->uf,cli->cep,cli->cgc,cli->insc,cli->cpf)
                                        ELSE
                                                dup_sis(aret[point,8],mfornec,cli->endereco,cli->bairro,cli->cidade,cli->uf,cli->cep,cli->tel1,;
                                                        cli->cgc,cli->insc,cli->cpf,cli->end_cob,cli->bairro_cob,cli->cidade_cob,cli->uf_cob,cli->cep_cob,cli->fone_cob,;
                                                        mtipo,aret[point,4],aret[point,10],aret[point,11],VAL(aret[point,35]),aret[point,5],cli->nome)
                                        ENDIF
                                        SETPRC(00,00)
                                        SET DEVI TO SCREEN;SET PRINT TO;SET PRINT OFF
                                        conf_impressao('ALT_DUPR.REL')
                                        wvw_lclosewindow()
                                ENDIF
                ENDCASE
        ELSE
                IF ver_serie()='141237'
                        mordem := '6'
                ELSE
                        mordem := '2'
                        mordem := mensagem1('Tipo de Ordem [2] DOCUMENTO - [6] VENCIMENTO - [3] VALOR:','2','2,6,3')
                ENDIF
                mtotal_doc := mcont_doc := 0
                ASIZE(m_dupr,0)
                ASIZE(m_pos,0)
                IF mtp = NIL .OR. mtp = 'A' .OR. mtp = 'P' .OR. mtp = 'E'
                        cComm  := "SELECT * FROM "+IF(mtp_tp = NIL,"sacdupr","saccred")+" WHERE tipo = "+sr_cdbvalue(mtipo)
                        IF ! EMPTY(mnumero)
                                cComm  := ccomm + " AND numero = "+sr_cdbvalue(mnumero)
                        ENDIF
                        cComm  := ccomm + " AND duplicata LIKE "+sr_cdbvalue(ALLTRIM(mduplicata)+'%')
                        cComm  := ccomm + " AND datpag IS NULL"
                        IF mordem = '6'
                                ccomm := ccomm + " ORDER BY venc,duplicata"
                        ELSEIF mordem = '2'
                                ccomm := ccomm + " ORDER BY tipo,duplicata,venc"
                        ELSE
                                ccomm := ccomm + " ORDER BY valor,duplicata"
                        ENDIF
                        aret:={}
                        sr_getconnection():exec(ccomm,,.t.,@aret)
                        sr_getconnection():exec('COMMIT',,.f.)
                        IF LEN(aret) = 0
                                atencao('Nao existe nenhum Documento a ser baixado')
                                LOOP
                        ENDIF
                ELSEIF mtp = 'S'
                        cComm  := "SELECT * FROM "+IF(mtp_tp = NIL,"sacdupr","saccred")+" WHERE tipo = "+sr_cdbvalue(mtipo)
                        IF ! EMPTY(mnumero)
                                cComm  := ccomm + " AND numero = "+sr_cdbvalue(mnumero)
                        ENDIF
                        cComm  := ccomm + " AND duplicata LIKE "+sr_cdbvalue(ALLTRIM(mduplicata)+'%')
                        cComm  := ccomm + " AND datpag IS NOT NULL"
                        IF mordem = '6'
                                ccomm := ccomm + " ORDER BY venc,duplicata"
                        ELSEIF mordem = '2'
                                ccomm := ccomm + " ORDER BY tipo,duplicata,venc"
                        ELSE
                                ccomm := ccomm + " ORDER BY valor,duplicata"
                        ENDIF
                        aret:={}
                        sr_getconnection():exec(ccomm,,.t.,@aret)
                        sr_getconnection():exec('COMMIT',,.f.)
                        IF LEN(aret) = 0
                                atencao('Documento nao Cadastrado ou NAO FOI PAGO !!!')
                                LOOP
                        ENDIF
                ENDIF

                mensagem('Aguarde o Coletando dados p/ impressao...')
                ************************************************************
                setcor(3)
                DEVPOS(lc+1,cc+28);DEVOUT(STRZERO(mcod_cli,5))
                DEVPOS(lc+1,cc+35);DEVOUT(aret[1,1])
                setcor(1)
                mcliente := aret[1,1]
                FOR i = 1 TO LEN(aret)
                                     //  cod.cli           nome cli           tipo        duplicata       tip_pg         numero             venc                      valor                             conta                    data_fund                     emp.
                        AADD(m_dupr,' '+aret[i,7]+' '+LEFT(aret[i,8],25)+' '+aret[i,2]+' '+aret[i,4]+' '+aret[i,26]+'  '+aret[i,3]+'   '+DTOC(aret[i,11])+'   '+TRANSFORM(aret[i,19],'999,999.99')+' '+aret[i,28]+' '+IF(! EMPTY(aret[i,43]),'S/F','   ')+' '+aret[i,1])
                        //AADD(m_pos,aret[i,10])
                        mcont_doc ++
                        mtotal_doc := mtotal_doc + aret[i,19]
                NEXT

                op_tela(li,ci,la+2,ca+35,'Documentos do Cliente')
                mensagem('<ESC> Retorna  -  <ENTER> p/Confirmar')
                setcor(3)
                DEVPOS(li+1,ci+01);DEVOUT('Cliente')
                DEVPOS(li+1,ci+34);DEVOUT('Documento')
                DEVPOS(li+1,ci+51);DEVOUT('Op')
                DEVPOS(li+1,ci+54);DEVOUT(' No.')
                DEVPOS(li+1,ci+60);DEVOUT('Vencimento')
                DEVPOS(li+1,ci+77);DEVOUT('Valor')
                DEVPOS(li+1,ci+89);DEVOUT('Emp')
                @ li+2,ci+1 TO li+2,ca+30
                @ la-2,ci+1 TO la-2,ca+30
                DEVPOS(la-1,ci+1);DEVOUT('Quantidade:')
                DEVPOS(la-1,ci+24);DEVOUT('Total:')
                setcor(1)
                DEVPOS(la-1,ci+13);DEVOUT(STRZERO(mcont_doc,4))
                DEVPOS(la-1,ci+31);DEVOUT(TRANSFORM(mtotal_doc,'9,999,999.99'))
                point := ACHOICE(li+3,ci+1,la-3,ca+29,m_dupr,,,point)
                wvw_lclosewindow()
                DO CASE
                        CASE LASTKEY()=27
                                LOOP
                        CASE LASTKEY() = 13
                                mjuros := mmulta := 0
                                mdatpag:=mdata_sis
                                mvlpago:=aret[point,19]
                                mbanco := SUBSTR(aret[point,16],1,1)
                                mcomissao := aret[point,32]
                                mobs := aret[point,46]
                                mobs1 := aret[point,47]
                                IF aret[point,28] = '*'
                                        mdias_atras := mdatpag - aret[point,11]
                                ELSE
                                        mdias_atras := mdatpag - (aret[point,11]+m_set[1,40])
                                ENDIF
                                IF mdias_atras > 0 .AND. mtp_ = NIL
                                        mdias_atras := mdatpag - aret[point,11]
                                        mmulta := iat(aret[point,19] * ((m_set[1,9])/100),2)
                                        mjuros := iat((aret[point,19] * ((mdias_atras*m_set[1,10])/100)),2)
                                ENDIF
                                mvlpago := iat(aret[point,19],2)+mjuros+mmulta
                                mduplicata := aret[point,4]
                                mtipo := aret[point,2]
                                setcor(3)
                                WVW_DrawLabel(,lc-1,cc+28,aret[point,4]+aret[point,28],,,,, 'Arial Black',20,20,,,,,)
                                @ lc+1,cc+28 SAY aret[point,7]
                                @ lc+1,cc+35 SAY aret[point,8]
                                @ lc+3,cc+28 SAY aret[point,2]
                                @ lc+3,cc+33 SAY aret[point,3]
                                //@ lc+4,cc+28 SAY aret[point,4]+aret[point,28]
                                @ lc+4,cc+28 SAY aret[point,31]
                                @ lc+5,cc+28 SAY aret[point,10]
                                @ lc+6,cc+28 SAY aret[point,11]
                                @ lc+6,cc+57 SAY aret[point,12]
                                @ lc+7,cc+28 SAY IF(mdias_atras<0,TRANSFORM(0,'9999'),TRANSFORM(mdias_atras,'9999'))
                                @ lc+9,cc+28 SAY aret[point,19] PICT "99,999,999.99"
                                @ lc+10,cc+28 SAY mmulta PICT "99,999,999.99"
                                @ lc+11,cc+28 SAY mjuros PICT "99,999,999.99"
                                setcor(1)
                                IF mtp = NIL
                                        @ lc+8,cc+28 GET mdatpag WHEN cx = NIL
                                        READ
                                        IF LASTKEY()=27
                                                LOOP
                                        ENDIF
                                        IF mdatpag <> mdata_sis
                                                IF ! ver_nivel('DOC_DATA','CONTA A RECEBER (ALTERACAO DATA BAIXA DE DOCUMENTO)','1',nivel_acess,,'AMBIE')
                                                        LOOP
                                                ENDIF
                                        ENDIF
                                        IF aret[point,28] = '*'
                                                mdias_atras := mdatpag-aret[point,11]
                                        ELSE
                                                mdias_atras := mdatpag-(aret[point,11]+m_set[1,40])
                                        ENDIF
                                        IF mdias_atras > 0 .AND. mtp_ = NIL
                                                mdias_atras := mdatpag-aret[point,11]
                                                mmulta := iat(aret[point,19] * ((m_set[1,9])/100),2)
                                                mjuros := iat((aret[point,19] * ((mdias_atras*m_set[1,10])/100)),2)
                                        ELSE
                                                mjuros := mmulta := 0
                                        ENDIF
                                        mvlpago=iat(aret[point,19]+mjuros+mmulta,2)
                                        setcor(3)
                                        @ lc+7,cc+28 SAY IF(mdias_atras<0,TRANSFORM(0,'9999'),TRANSFORM(mdias_atras,'9999'))
                                        @ lc+10,cc+28 SAY mmulta PICT "99,999,999.99"
                                        //IF mjuros > 0
                                                @ lc+11,cc+28 SAY mjuros PICT "99,999,999.99"
                                        //ENDIF
                                        @ lc+16,cc+12 SAY aret[point,46]
                                        setcor(1)
/*
                                        IF mjuros = 0
                                                @ lc+11,cc+28 GET mjuros PICT "99,999,999.99" VALID IF(mjuros<0,.F.,.T.)
                                                READ
                                                mvlpago := iat(aret[point,19]+mjuros+mmulta,2)
                                        ENDIF
*/
                                        @ lc+12,cc+28 GET mvlpago PICT "99,999,999.99"
                                        @ lc+13,cc+28 GET mtip_pg PICT '@!'
                                        @ lc+14,cc+28 GET mcheque PICT '99999999'
                                        @ lc+15,cc+28 GET mbanco PICT '@!' VALID mbanco $ 'B,C'
                                        @ lc+17,cc+12 GET mobs1
                                        READ
                                        setcor(3)
                                        @ lc+17,cc+12 SAY mobs1
                                        setcor(1)
                                        IF LASTKEY()=27
                                                LOOP
                                        ENDIF
                                        opcao := op_simnao('S','Confirma os Dados ? [S/n]:')
                                        IF opcao = 'N'
                                                LOOP
                                        ENDIF
                                        pconta = ' '
                                        IF mvlpago < aret[point,19]+mjuros+mmulta .AND. ((aret[point,19]+mjuros+mmulta)-mvlpago) > .10
                                                pconta := op_simnao('S','Este Valor vai ser por CONTA [S/n]:')
                                                IF pconta = 'N'
                                                        IF ! aut_sen('Senha de autorizacao p/dispensa o restante do documento:','LIB_RECE')
                                                                LOOP
                                                        ENDIF
                                                ENDIF
                                        ENDIF
/*
                                        IF mvlpago > aret[point,19]+mjuros+mmulta
                                                stop:=' '
                                                setcor(3)
                                                op_tela(19,20,24,70,'TROCO','1')
                                                DEVPOS(00,01);DEVOUT(' T R O C O   R$:')
                                                DEVPOS(05,10);DEVOUT('Pressione qualquer tecla p/continuar...')
                                                WVW_DrawLabel(,01,02,TRANSFORM(mvlpago - (aret[point,19]+mjuros+mmulta),ALLTRIM('@E 999,999.99')),,,,, 'arial black',60,45,,,,,)
                                                @ 40,00 GET stop
                                                READ
                                                setcor(1)
                                                mvlpago := aret[point,19]+mjuros+mmulta
                                                wvw_lclosewindow()
                                        ENDIF
*/
                                        ASIZE(m_dup,0)
                                        ASIZE(m_po,0)

                                        IF EMPTY(aret[point,11])
                                                atencao('Favor Verificar o VENCIMENTO deste documento para poder Prossegir...')
                                                LOOP
                                        ENDIF

                                        IF mtp_tp = NIL
                                                *********** ATUALIZANDO SACDUPR ***********************
                                                ccomm := "UPDATE sacdupr SET datpag = " + sr_cdbvalue(mdatpag)+",datope = " + sr_cdbvalue(mdata_sis)
                                                IF pconta = 'S'
                                                        ccomm := ccomm + ",valor  = " + sr_cdbvalue(mvlpago)
                                                ENDIF
                                                ccomm := ccomm + ",vlpago = " + sr_cdbvalue(mvlpago)  +;
                                                                ",cheque = " + sr_cdbvalue(mcheque)  +;
                                                                ",pago   = " + sr_cdbvalue('B')  +;
                                                                ",tip_pg = " + sr_cdbvalue(mtip_pg)  +;
                                                                ",operador = " + sr_cdbvalue(cod_operado)+;
                                                                ",obs    = " + sr_cdbvalue(mobs)+;
                                                                ",obs1   = " + sr_cdbvalue(mobs1)+;
                                                                ",banco  = " + sr_cdbvalue(IF(cx <> NIL,'C',mbanco))+;
                                                                ",mov_cx = " + sr_cdbvalue(IF(cx <> NIL,'C','M'))+;
                                                                ",conta  = " + sr_cdbvalue(IF(pconta = 'S','*',''))+;
                                                                ",juros  = " + sr_cdbvalue(IF(pconta <> 'S' .AND. mvlpago>=aret[point,19],mvlpago-aret[point,19],0.00))+;
                                                                ",juros_d= " + sr_cdbvalue(IF(pconta <> 'S' .AND. mvlpago>=aret[point,19],(mmulta+mjuros)-(mvlpago-aret[point,19]),0.00))+;
                                                                ",hora_bx  = " + sr_cdbvalue(TIME())+;
                                                                " WHERE sr_recno = " + sr_cdbvalue(aret[point,65])
                                                sr_getconnection():exec(ccomm,,.f.)
                                                **************************************************************
                                                IF pconta = 'S'
                                                        sr_getconnection():exec('INSERT INTO sacdupr (empresa,tipo,numero,'+;
                                                                'duplicata,valor_dup,'+;
                                                                'fornec,cliente,'+;
                                                                'tip_cli,emissao,'+;
                                                                'venc1,venc,valor,vendedor,num_ped,conta,'+;
                                                                'banco,comissao,operador,obs,obs1,agencia,c_c,corrente,'+;
                                                                'doc_tran,data_fund,cod_incl,motivo,com_sem,SR_DELETED )'+;
                                                                ' VALUES ('+;
                                                                sr_cdbvalue(aret[point,1])+','+; //1
                                                                sr_cdbvalue(aret[point,2])+','+; //2
                                                                sr_cdbvalue(aret[point,3])+','+; //3
                                                                sr_cdbvalue(aret[point,4])+','+; //4
                                                                sr_cdbvalue(aret[point,5])+','+; //5
                                                                sr_cdbvalue(aret[point,7])+','+; //6
                                                                sr_cdbvalue(aret[point,8])+','+; //7
                                                                sr_cdbvalue(aret[point,6])+','+; //8
                                                                sr_cdbvalue(aret[point,10])+','+;//9
                                                                sr_cdbvalue(IF(! EMPTY(aret[point,12]),aret[point,12],aret[point,11]))+','+;//10
                                                                sr_cdbvalue(IF(! EMPTY(mmulta) .OR. ! EMPTY(mjuros),mdatpag,aret[point,11]))+','+; //11
                                                                sr_cdbvalue((aret[point,19]+mmulta+mjuros)-mvlpago)+','+;//12
                                                                sr_cdbvalue(aret[point,30])+','+;//13
                                                                sr_cdbvalue(aret[point,31])+','+;//14
                                                                sr_cdbvalue('*')+','+;//15
                                                                sr_cdbvalue(mbanco)+','+;//16
                                                                sr_cdbvalue(iat(mcomissao,2))+','+;//17
                                                                sr_cdbvalue(cod_operado)+','+;//18
                                                                sr_cdbvalue(mobs)+','+;//19
                                                                sr_cdbvalue(mobs1)+','+;//20
                                                                sr_cdbvalue(aret[point,17])+','+;//21
                                                                sr_cdbvalue(aret[point,18])+','+;//22
                                                                sr_cdbvalue(aret[point,48])+','+;//23
                                                                sr_cdbvalue(aret[point,37])+','+;//24
                                                                IF(! EMPTY(aret[point,43]),sr_cdbvalue(aret[point,43]),nulo)+','+; //23  sr_cdbvalue(IF(EMPTY(aret[point,43]),nulo,aret[point,43]))+','+;//25
                                                                sr_cdbvalue(aret[point,45])+','+;//26
                                                                sr_cdbvalue(aret[point,44])+','+;//27
                                                                sr_cdbvalue(aret[point,64])+','+;//28
                                                                sr_cdbvalue(' ')+')',,.f.)
                                                ENDIF
                                                sr_getconnection():exec("COMMIT",,.f.)
                                        ELSE
                                                *********** ATUALIZANDO SACDUPR ***********************
                                                ccomm := "UPDATE saccred SET datpag = " + sr_cdbvalue(mdatpag)+",datope = " + sr_cdbvalue(mdata_sis)
                                                IF pconta = 'S'
                                                        ccomm := ccomm + ",valor  = " + sr_cdbvalue(mvlpago)
                                                ENDIF
                                                ccomm := ccomm + ",vlpago = " + sr_cdbvalue(mvlpago)  +;
                                                                ",cheque = " + sr_cdbvalue(mcheque)  +;
                                                                ",pago   = " + sr_cdbvalue('B')  +;
                                                                ",tip_pg = " + sr_cdbvalue(mtip_pg)  +;
                                                                ",operador = " + sr_cdbvalue(cod_operado)+;
                                                                ",obs    = " + sr_cdbvalue(mobs)+;
                                                                ",obs1   = " + sr_cdbvalue(mobs1)+;
                                                                ",banco  = " + sr_cdbvalue(IF(cx <> NIL,'C',mbanco))+;
                                                                ",mov_cx = " + sr_cdbvalue(IF(cx <> NIL,'C','M'))+;
                                                                ",conta  = " + sr_cdbvalue(IF(pconta = 'S','*',''))+;
                                                                ",juros  = " + sr_cdbvalue(IF(pconta <> 'S' .AND. mvlpago>=aret[point,19],mvlpago-aret[point,19],0.00))+;
                                                                ",juros_d= " + sr_cdbvalue(IF(pconta <> 'S' .AND. mvlpago>=aret[point,19],(mmulta+mjuros)-(mvlpago-aret[point,19]),0.00))+;
                                                                " WHERE sr_recno = " + sr_cdbvalue(aret[point,65])
                                                sr_getconnection():exec(ccomm,,.f.)
                                                **************************************************************
                                                IF pconta = 'S'
                                                        sr_getconnection():exec('INSERT INTO saccred (empresa,tipo,numero,'+;
                                                                'duplicata,valor_dup,'+;
                                                                'fornec,cliente,'+;
                                                                'tip_cli,emissao,'+;
                                                                'venc1,venc,valor,vendedor,num_ped,conta,'+;
                                                                'banco,comissao,operador,obs,obs1,agencia,c_c,corrente,'+;
                                                                'doc_tran,SR_DELETED )'+;
                                                                ' VALUES ('+;
                                                                sr_cdbvalue(aret[point,1])+','+; //1
                                                                sr_cdbvalue(aret[point,2])+','+; //2
                                                                sr_cdbvalue(aret[point,3])+','+; //3
                                                                sr_cdbvalue(aret[point,4])+','+; //4
                                                                sr_cdbvalue(aret[point,5])+','+; //5
                                                                sr_cdbvalue(aret[point,7])+','+; //6
                                                                sr_cdbvalue(aret[point,8])+','+; //7
                                                                sr_cdbvalue(aret[point,6])+','+; //8
                                                                sr_cdbvalue(aret[point,10])+','+;//9
                                                                sr_cdbvalue(IF(! EMPTY(aret[point,12]),aret[point,12],aret[point,11]))+','+;//10
                                                                sr_cdbvalue(IF(! EMPTY(mmulta) .OR. ! EMPTY(mjuros),mdatpag,aret[point,11]))+','+; //11
                                                                sr_cdbvalue((aret[point,19]+mmulta+mjuros)-mvlpago)+','+;//12
                                                                sr_cdbvalue(aret[point,30])+','+;//13
                                                                sr_cdbvalue(aret[point,31])+','+;//14
                                                                sr_cdbvalue('*')+','+;//15
                                                                sr_cdbvalue(mbanco)+','+;//16
                                                                sr_cdbvalue(iat(mcomissao,2))+','+;//17
                                                                sr_cdbvalue(cod_operado)+','+;//18
                                                                sr_cdbvalue(mobs)+','+;//19
                                                                sr_cdbvalue(mobs1)+','+;//20
                                                                sr_cdbvalue(aret[point,17])+','+;//21
                                                                sr_cdbvalue(aret[point,18])+','+;//22
                                                                sr_cdbvalue(aret[point,48])+','+;//23
                                                                sr_cdbvalue(aret[point,37])+','+;//24
                                                                sr_cdbvalue(' ')+')',,.f.)
                                                ENDIF
                                                sr_getconnection():exec("COMMIT",,.f.)
                                        ENDIF
                                        AADD(m_dup,aret[point,7]+' '+aret[point,2]+' '+aret[point,4]+' '+DTOC(aret[point,11])+' '+TRANSFORM(aret[point,19],'999,999.99')+' '+TRANSFORM(mjuros+mmulta,'999,999.99')+' '+TRANSFORM(mvlpago,'999,999.99')+' X')
                                        //AADD(m_po,{RECNO(),'X',(malias)->valor,mjuros+mmulta,mvlpago,'X'})

                                        IF cx <> NIL
                                                ******************
                                                SELE('caix');ORDSETFOCUS(3)
                                                GO TOP
                                                *****************
                                                IF mtipo = 'DU'
                                                        IF caix->(DBSEEK(mtipo + mduplicata + STRZERO(mcod_cli,5)))
*                                                               mnota := caix->nota
                                                                mtipo_comp := caix->tipo_comp
                                                                mcod_vend := caix->cod_vend
                                                                mdescri1  := caix->descri1
                                                                mdescri2  := caix->descri2
                                                                IF BLOQREG()
                                                                        caix->op_pg := 'P'
                                                                        DBCOMMIT()
                                                                        DBUNLOCK()
                                                                ENDIF
                                                        ENDIF
                                                ENDIF
                                                IF ADIREG()
                                                        caix-> empresa := aret[point,1]
                                                        caix-> tipo := aret[point,2]
                                                        caix-> nota := 'DOC.PG  '
                                                        caix-> num_dup := aret[point,4]
                                                        caix-> num_ban := aret[point,3]
                                                        caix-> documento := aret[point,4]
                                                        caix-> data := mdatpag
                                                        caix-> descri1:= mdescri1
                                                        caix-> descri2:= mdescri2
                                                        caix-> venci := aret[point,11]
                                                        caix-> valor := mvlpago
                                                        caix-> cod_cli := aret[point,7]
                                                        caix-> cod_vend := mcod_vend
                                                        caix-> cod_opera := cod_operado
                                                        caix-> pg := '*'
                                                        caix-> op_pg := 'P'
                                                        caix-> valor_com := mvlpago
                                                        caix-> comissao := mcomissao
                                                        caix-> hora     := TIME()
                                                        caix-> tp_mov   := 'B'
                                                        DBCOMMIT()
                                                        DBUNLOCK()
                                                ELSE
                                                        atencao('Nao foi possivel acessar o Arquivo !!!')
                                                        LOOP
                                                ENDIF
                                        ENDIF
                                        IF m_set[1,149] = 'R' .OR. m_set[1,149] = 'A'
                                                IF  m_set[1,149] = 'R'
                                                        mtipo_aut := 2
                                                ELSE
                                                        mtipo_aut := 1
                                                ENDIF
                                                op_tela(10,35,12,67,' Opcao de Autenticacoes ')
                                                @ 01,01 PROMPT ' Autenticar'
                                                @ 01,15 PROMPT ' Imprimir Recibo '
                                                SET INTEN ON
                                                MENU TO mtipo_aut
                                                wvw_lclosewindow()
                                                IF  mtipo_aut = 2
                                                        mdevedor:={}
                                                        sr_getconnection():exec("SELECT SUM(valor) FROM sacdupr WHERE fornec = "+sr_cdbvalue(STRZERO(mcod_cli,5)) +" AND datpag IS NULL",,.t.,@mdevedor)
                                                        sr_getconnection():exec('COMMIT',,.f.)
                                                        rec_dupr(m_dup,aret[point,65],1,mjuros+mmulta,mvlpago,mdatpag,mtp,aret[point,19],mdevedor[1,1]) //con252
                                                ENDIF
                                        ENDIF
                                        IF mlimp_cli = '*';mcod_cli:=0;ENDIF
                                        LOOP
                                ELSEIF mtp = 'S'
                                        setcor(3)
                                        @ lc+7,cc+28 SAY IF(mdias_atras<0,TRANSFORM(0,'9999'),TRANSFORM(mdias_atras,'9999'))
                                        @ lc+8,cc+28 SAY aret[point,13]
                                        @ lc+10,cc+28 SAY "             "
                                        @ lc+11,cc+28 SAY aret[point,23] PICT "99,999,999.99"
                                        @ lc+12,cc+28 SAY aret[point,20] PICT "99,999,999.99"
                                        @ lc+13,cc+28 SAY aret[point,26]
                                        @ lc+14,cc+28 SAY aret[point,29]
                                        @ lc+16,cc+12 SAY aret[point,46]
                                        @ lc+16,cc+12 SAY aret[point,47]
                                        setcor(1)
                                        opcao := op_simnao('S','Confirma os Dados:')
                                        IF opcao = "N"
                                                LOOP
                                        ENDIF
                                        IF mtp_tp = NIL
                                                ccomm :="UPDATE sacdupr SET datope = NULL,datpag = NULL,vlpago = "+sr_cdbvalue(0)+",pago = NULL,juros = "+sr_cdbvalue(0)+",cheque = "+sr_cdbvalue(SPACE(8))+",operador = "+sr_cdbvalue(cod_operado)+",obs = "+sr_cdbvalue(mobs)+" WHERE SR_RECNO = "+sr_cdbvalue(aret[point,65])
                                        ELSE
                                                ccomm :="UPDATE saccred SET datope = NULL,datpag = NULL,vlpago = "+sr_cdbvalue(0)+",pago = NULL,juros = "+sr_cdbvalue(0)+",cheque = "+sr_cdbvalue(SPACE(8))+",operador = "+sr_cdbvalue(cod_operado)+",obs = "+sr_cdbvalue(mobs)+" WHERE SR_RECNO = "+sr_cdbvalue(aret[point,65])
                                        ENDIF
                                        sr_getconnection():exec(ccomm,,.f.)
                                        sr_getconnection():exec("COMMIT",,.f.)
                                        IF aret[point,27] = 'C'
                                                ******************
                                                SELE('caix');ORDSETFOCUS(3)
                                                GO TOP
                                                *****************
                                                IF caix->(DBSEEK(aret[point,2] + aret[point,4] + aret[point,7] + '*'))
                                                        BLOQREG()
                                                        DELE
                                                        DBUNLOCK()
                                                        DBCOMMIT()
                                                        sr_getconnection():exec("DELETE FROM saccaixa WHERE SR_DELETED = 'T'",,.f.)
                                                        sr_getconnection():exec("COMMIT",,.f.)
                                                ENDIF
                                        ENDIF
                                        LOOP
                                ELSEIF mtp = 'E'
                                        setcor(3)
                                        @ lc+7,cc+28 SAY IF(mdias_atras<0,TRANSFORM(0,'9999'),TRANSFORM(mdias_atras,'9999'))
                                        @ lc+8,cc+28 SAY aret[point,13]
                                        @ lc+10,cc+28 SAY "             "
                                        @ lc+11,cc+28 SAY aret[point,23] PICT "99,999,999.99"
                                        @ lc+12,cc+28 SAY aret[point,20] PICT "99,999,999.99"
                                        @ lc+13,cc+28 SAY aret[point,26]
                                        @ lc+14,cc+28 SAY aret[point,29]
                                        @ lc+16,cc+12 SAY aret[point,46]
                                        @ lc+16,cc+12 SAY aret[point,47]
                                        setcor(1)
                                        opcao := op_simnao('N','Confirma a EXCLUSAO do Documento:')
                                        IF opcao = "N"
                                                LOOP
                                        ENDIF
                                        IF mtp_tp = NIL
                                                ccomm :="DELETE FROM sacdupr WHERE SR_RECNO = "+sr_cdbvalue(aret[point,65])
                                        ELSE
                                                ccomm :="DELETE FROM saccred WHERE SR_RECNO = "+sr_cdbvalue(aret[point,65])
                                        ENDIF
                                        sr_getconnection():exec(ccomm,,.f.)
                                        sr_getconnection():exec("COMMIT",,.f.)
                                        LOOP
                                ELSEIF mtp = 'I'
                                        mqtd_cop := 1
                                        mtipo_dup := 'S'
                                        setcor(1)
                                        @ lc+18,cc+36 GET mtipo_dup PICT "@!" VALID mtipo_dup $ 'S,P'
                                        @ lc+19,cc+36 GET mqtd_cop PICT "9" VALID IF(EMPTY(mqtd_cop),.F.,.T.)
                                        READ
                                        IF LASTKEY() = 27
                                                LOOP
                                        ENDIF
                                        opcao := op_simnao('N','Confirma a IMPRESSAO do Documento:')
                                        IF opcao = "N"
                                                LOOP
                                        ENDIF
                                        IF ! imp_arq('DUPLICATA.REL','D');LOOP;ENDIF
                                        cons_cli:={}
                                        sr_getconnection():exec("SELECT * FROM saccli WHERE cod_cli = "+sr_cdbvalue(aret[point,7]),,.t.,@cons_cli)
                                        sr_getconnection():exec('COMMIT',,.f.)
                                        IF mtipo_dup = 'P'
                                                IF ver_serie() = '141236' // SOTINTAS
                                                        dup_sot(mdata_sis,VAL(aret[point,30]),aret[point,19],aret[point,4],aret[point,11],cons_cli[1,3],aret[point,7],cons_cli[1,21],;
                                                                cons_cli[1,22],cons_cli[1,24],cons_cli[1,25],cons_cli[1,26],cons_cli[1,32],cons_cli[1,33],cons_cli[1,34],aret[point,16])
                                                ELSE
                                                        imprt(mtipo_imp,'C')
                                                        @ PROW()+10,21 SAY aret[point,4]
                                                        DEVPOS(PROW(),40);DEVOUT(TRANSFORM(iat(aret[point,19],2),'99,999,999.99'))
                                                        @ PROW(),60 SAY aret[point,4]
                                                        DEVPOS(PROW(),80);DEVOUT(TRANSFORM(iat(aret[point,19],2),'99,999,999.99'))
                                                        @ PROW(),99 SAY aret[point,11]
                                                        @ PROW()+3,65 SAY STRZERO(aret[point,11]-mdata_sis,3)+' dias'
                                                        @ PROW()+3,60 SAY cons_cli[1,2]
                                                        @ PROW(),PCOL()+1 SAY cons_cli[1,3]
                                                        @ PROW()+1,60 SAY cons_cli[1,21]
                                                        @ PROW()+1,60 SAY RTRIM(cons_cli[1,22])+'-Cidade: '+RTRIM(cons_cli[1,24])
                                                        @ PROW(),110 SAY cons_cli[1,25]
                                                        @ PROW()+1,60 SAY 'Cobranca Bancaria'
                                                        IF cons_cli[1,32] <> SPACE(14)
                                                                DEVPOS(PROW()+1,60);DEVOUTPICT(cons_cli[1,32],'@@R 99.999.999/9999-99')
                                                                DEVPOS(PROW(),100);DEVOUT(cons_cli[1,33])
                                                        ELSEIF cons_cli[1,34] <> SPACE(11)
                                                                DEVPOS(PROW()+1,60);DEVOUTPICT(cons_cli[1,34],'@@R 999.999.999-99')
                                                        ELSE
                                                                DEVPOS(PROW()+1,00);DEVOUT(' ')
                                                        ENDIF
                                                        mextenso:= '('+RTRIM(extenso(iat(aret[point,19],2),.T.,'real','reais'))+')'
                                                        mlinha := MLCOUNT(mextenso,50)
                                                        DEVPOS(PROW()+1,00);DEVOUT(' ')
                                                        FOR lin = 1 TO mlinha
                                                                mlin := MEMOLINE(mextenso,50,lin,,10)
                                                                DEVPOS(PROW()+1,60);DEVOUT(PADR(RTRIM(mlin),50))
                                                        NEXT
                                                        imprt(mtipo_imp,'N')
                                                ENDIF
                                        ELSE
                                                FOR i = 1 TO mqtd_cop
                                                        dup_sis(cons_cli[1,2],cons_cli[1,3],cons_cli[1,21],cons_cli[1,22],cons_cli[1,24],cons_cli[1,25],cons_cli[1,26],cons_cli[1,29],;
                                                                cons_cli[1,32],cons_cli[1,33],cons_cli[1,34],cons_cli[1,100],cons_cli[1,101],cons_cli[1,102],cons_cli[1,103],cons_cli[1,104],cons_cli[1,105],;
                                                                aret[point,2],aret[point,4],aret[point,10],aret[point,11],VAL(aret[point,30]),aret[point,19],cons_cli[1,4],'          ',aret[point,19])
                                                NEXT
                                        ENDIF
                                        SETPRC(00,00)
                                        SET DEVI TO SCREEN;SET PRINT TO;SET PRINT OFF
                                        conf_impressao('DUPLICATA.REL')
                                        LOOP
                                ELSEIF mtp = 'A' .OR. mtp = 'P'
                                        lba := 22
                                        cba := 79
                                        op_tela(0,0,lba,cba," ALTERACAO DE DOCUMENTO (Contas a Receber) ")
                                        DEVPOS(1,2);DEVOUT('Codigo da Empresa......:')
                                        DEVPOS(2,2);DEVOUT('Tipo Documentos........:')
                                        DEVPOS(3,2);DEVOUT('No.Banco/Cod.Cartao....:')
                                        DEVPOS(3,32);DEVOUT('Agencia:')
                                        DEVPOS(3,51);DEVOUT('C/C:')
                                        DEVPOS(4,2);DEVOUT('Numero Documentos......:')
                                        DEVPOS(5,2);DEVOUT('Codigo do Cliente......:')
                                        DEVPOS(6,2);DEVOUT('Data de Emissao........:')
                                        DEVPOS(7,2);DEVOUT('Data de Vencimento.....:')
                                        DEVPOS(8,2);DEVOUT('Valor Documento R$.....:')
                                        DEVPOS(9,2);DEVOUT('Pag. [C]arteria [B]anco:')
                                        DEVPOS(10,2);DEVOUT('Codigo do Vendedor.....:')
                                        DEVPOS(11,2);DEVOUT('Numero do Pedido/NF....:')
                                        DEVPOS(12,2);DEVOUT('% de Comissao .........:')
                                        DEVPOS(13,2);DEVOUT('Nome do Correntista....:')
                                        DEVPOS(14,2);DEVOUT('Tipo de Operacao.......:')
                                        DEVPOS(15,2);DEVOUT('OBS.:')
                                        DEVPOS(16,2);DEVOUT('Processo:')
                                        mfornec=VAL(aret[point,7])
                                        mnome_cli := aret[point,8]
                                        memissao=aret[point,10]
                                        mvenc=aret[point,11]
                                        mvalor=aret[point,19]
                                        mtipo=aret[point,2]
                                        mcod_ven := VAL(aret[point,30])
                                        mnum_ped := VAL(aret[point,31])
                                        mbanco := SUBSTR(aret[point,16],1,1)
                                        mnum_banco := VAL(aret[point,3])
                                        mcomissao := aret[point,32] * 100
                                        magencia := aret[point,17]
                                        mc_c := aret[point,18]
                                        mcorrente := aret[point,48]
                                        mobs := aret[point,46]
                                        mtip_pg := aret[point,26]
                                        mlin1 := aret[point,58]
                                        mlin2 := aret[point,59]
                                        mlin3 := aret[point,60]
                                        mlin4 := aret[point,61]
                                        mlin5 := aret[point,62]
                                        mensagem('Complete os Dados. [ESC] Abandona.')
                                        IF RTRIM(mnome_cli) = 'DIVERSOS'
                                                mnome_cli := aret[point,8]
                                                setcor(3)
                                                DEVPOS(5,32);DEVOUT(mnome_cli)
                                                setcor(1)
                                        ENDIF
                                        @ 2,27 GET mtipo PICT '@!' VALID IF(EMPTY(mtipo),.F.,ver_tipdc(mtipo,'*')) WHEN mtp <> 'P'
                                        @ 3,27 GET mnum_banco PICT '999' WHEN (mtipo = 'CH' .AND. mtp <> 'P') .OR. ver_serie() = '141235'
                                        @ 3,41 GET magencia PICT '@!' WHEN mtipo = 'CH' .AND. mtp <> 'P'
                                        @ 3,56 GET mc_c PICT '@!' VALID qtd_chq(mfornec,STRZERO(mnum_banco,3),magencia,mc_c) WHEN mtp <> 'P' .AND. mtipo = 'CH'
                                        @ 4,27 GET mduplicata PICT '@!' WHEN mtp <> 'P'
                                        @ 5,27 GET mfornec PICT "99999" VALID mcli(mfornec,5,27) WHEN mtp <> 'P'
                                        READ
                                        IF LASTKEY()=27
                                                wvw_lclosewindow()
                                                LOOP
                                        ENDIF

                                        IF RTRIM(mnome_cli) = 'DIVERSOS'
                                                mnome_cli := aret[point,8]
                                                @ 5,32 GET mnome_cli PICT '@!' WHEN mtp <> 'P'
                                        ELSE
                                                mnome_cli := cli->razao
                                        ENDIF
                                        @ 6,27 GET memissao WHEN mtp <> 'P'
                                        @ 7,27 GET mvenc VALID IF(EMPTY(mvenc),.F.,.T.) WHEN mtp <> 'P'
                                        @ 8,27 GET mvalor PICT "@E 99,999,999,999.99" VALID mvalor>0 WHEN mtp <> 'P'
                                        @ 9,27 GET mbanco PICT "@!" VALID mbanco $ 'C,B' .AND. lim_get() WHEN mtp <> 'P' .AND. men_get(10,31,'Digite [C] para pagamento em CARTEIRA [B] para pagamento em BANCO"')
                                        @ 10,27 GET mcod_ven PICT "999" VALID ven(mcod_ven,10,31) .AND. lim_get() WHEN mtp <> 'P' .AND. men_get(11,31,'Informe o Cod. do vendedor "CAMPO NAO OBRIGATORIO"')
                                        @ 11,27 GET mnum_ped PICT "999999" VALID lim_get() WHEN mtp <> 'P' .AND. men_get(12,31,'Informe o No.do pedido que corresponde a este documento "CAMPO NAO OBRIGATORIO"')
                                        @ 12,27 GET mcomissao PICT "999.99" VALID lim_get() WHEN mtp <> 'P' .AND. men_get(13,31,'Informe o percentual de comissao do vendedor para este documento')
                                        @ 13,27 GET mcorrente PICT "@!" VALID lim_get() WHEN mtp <> 'P' .AND. men_get(14,31,'Informe o nome do correntista')
                                        @ 14,27 GET mtip_pg PICT "@!" VALID lim_get() WHEN mtp <> 'P' .AND. men_get(15,31,'Informe o Tipo de Operacao')
                                        @ 15,07 GET mobs WHEN mtp <> 'P'
                                        READ
                                        setcor(3)
                                        @ lc+15,cc+07 SAY mobs
                                        setcor(1)
                                        @ 16,11 GET mlin1
                                        @ 17,11 GET mlin2
                                        @ 18,11 GET mlin3
                                        @ 19,11 GET mlin4
                                        @ 20,11 GET mlin5
                                        READ
                                        IF LASTKEY()=27
                                                wvw_lclosewindow()
                                                LOOP
                                        ENDIF
                                        opcao := op_simnao('S','Confirma os Dados:')
                                        IF opcao = "N"
                                                wvw_lclosewindow()
                                                LOOP
                                        ENDIF
                                        IF mtp = 'A'
                                                IF mtp_tp = NIL
                                                        IF EMPTY(mvenc)
                                                                atencao('Favor Verificar o VENCIMENTO deste documento para poder Prossegir...')
                                                                LOOP
                                                        ENDIF
                                                        sr_getconnection():exec("UPDATE sacdupr SET tipo    = " + sr_cdbvalue(mtipo)+;
                                                                ",numero  = " + sr_cdbvalue(IF((EMPTY(mnum_banco) .OR. mtipo = 'DU') .AND. ver_serie() <> '141235',' ',STRZERO(mnum_banco,3)))+;
                                                                ",agencia = " + sr_cdbvalue(magencia)  +;
                                                                ",c_c = " + sr_cdbvalue(mc_c)  +;
                                                                ",duplicata   = " + sr_cdbvalue(mduplicata)  +;
                                                                ",tip_cli = " + sr_cdbvalue(cli->tipo)  +;
                                                                ",fornec = " + sr_cdbvalue(STRZERO(mfornec,5))+;
                                                                ",cliente  = " + sr_cdbvalue(mnome_cli)+;
                                                                ",emissao   = " + sr_cdbvalue(memissao)+;
                                                                ",venc  = " + sr_cdbvalue(mvenc)+;
                                                                ",valor_dup = " + sr_cdbvalue(mvalor)+;
                                                                ",valor  = " + sr_cdbvalue(mvalor)+;
                                                                ",vendedor  = " + sr_cdbvalue(STRZERO(mcod_ven,3))+;
                                                                ",num_ped= " + sr_cdbvalue(STRZERO(mnum_ped,6))+;
                                                                ",banco= " + sr_cdbvalue(mbanco)+;
                                                                ",comissao= " + sr_cdbvalue(mcomissao/100)+;
                                                                ",corrente= " + sr_cdbvalue(mcorrente)+;
                                                                ",tip_pg= " + sr_cdbvalue(mtip_pg)+;
                                                                ",alt_oper= " + sr_cdbvalue(cod_operado)+;
                                                                ",obs= " + sr_cdbvalue(mobs)+;
                                                                ",lin1= " + sr_cdbvalue(mlin1)+;
                                                                ",lin2= " + sr_cdbvalue(mlin2)+;
                                                                ",lin3= " + sr_cdbvalue(mlin3)+;
                                                                ",lin4= " + sr_cdbvalue(mlin4)+;
                                                                ",lin5= " + sr_cdbvalue(mlin5)+;
                                                                ",operador= " + sr_cdbvalue(cod_operado)+;
                                                                ",mov_cx = " + sr_cdbvalue(IF(cx <> NIL,'C','M'))+;
                                                                " WHERE sr_recno = " + sr_cdbvalue(aret[point,65]),,.f.)
                                                        sr_getconnection():exec("COMMIT",,.f.)
                                                ELSE
                                                        sr_getconnection():exec("UPDATE saccred SET tipo    = " + sr_cdbvalue(mtipo)+;
                                                                ",numero  = " + sr_cdbvalue(IF((EMPTY(mnum_banco) .OR. mtipo = 'DU') .AND. ver_serie() <> '141235',' ',STRZERO(mnum_banco,3)))+;
                                                                ",agencia = " + sr_cdbvalue(magencia)  +;
                                                                ",c_c = " + sr_cdbvalue(mc_c)  +;
                                                                ",duplicata   = " + sr_cdbvalue(mduplicata)  +;
                                                                ",tip_cli = " + sr_cdbvalue(cli->tipo)  +;
                                                                ",fornec = " + sr_cdbvalue(STRZERO(mfornec,5))+;
                                                                ",cliente  = " + sr_cdbvalue(mnome_cli)+;
                                                                ",emissao   = " + sr_cdbvalue(memissao)+;
                                                                ",venc  = " + sr_cdbvalue(mvenc)+;
                                                                ",valor_dup = " + sr_cdbvalue(mvalor)+;
                                                                ",valor  = " + sr_cdbvalue(mvalor)+;
                                                                ",vendedor  = " + sr_cdbvalue(STRZERO(mcod_ven,3))+;
                                                                ",num_ped= " + sr_cdbvalue(STRZERO(mnum_ped,6))+;
                                                                ",banco= " + sr_cdbvalue(mbanco)+;
                                                                ",comissao= " + sr_cdbvalue(mcomissao/100)+;
                                                                ",corrente= " + sr_cdbvalue(mcorrente)+;
                                                                ",tip_pg= " + sr_cdbvalue(mtip_pg)+;
                                                                ",alt_oper= " + sr_cdbvalue(cod_operado)+;
                                                                ",obs= " + sr_cdbvalue(mobs)+;
                                                                ",lin1= " + sr_cdbvalue(mlin1)+;
                                                                ",lin2= " + sr_cdbvalue(mlin2)+;
                                                                ",lin3= " + sr_cdbvalue(mlin3)+;
                                                                ",lin4= " + sr_cdbvalue(mlin4)+;
                                                                ",lin5= " + sr_cdbvalue(mlin5)+;
                                                                ",operador= " + sr_cdbvalue(cod_operado)+;
                                                                ",mov_cx = " + sr_cdbvalue(IF(cx <> NIL,'C','M'))+;
                                                                " WHERE sr_recno = " + sr_cdbvalue(aret[point,65]),,.f.)
                                                        sr_getconnection():exec("COMMIT",,.f.)
                                                ENDIF
                                        ELSEIF mtp = 'P'
                                                sr_getconnection():exec("UPDATE sacdupr SET lin1= " + sr_cdbvalue(mlin1)+;
                                                        ",lin2= " + sr_cdbvalue(mlin2)+;
                                                        ",lin3= " + sr_cdbvalue(mlin3)+;
                                                        ",lin4= " + sr_cdbvalue(mlin4)+;
                                                        ",lin5= " + sr_cdbvalue(mlin5)+;
                                                        ",operador= " + sr_cdbvalue(cod_operado)+;
                                                        " WHERE sr_recno = " + sr_cdbvalue(aret[point,65]),,.f.)
                                                sr_getconnection():exec("COMMIT",,.f.)
                                        ENDIF
                                        IF memissao = mvenc .AND. mtp = 'A'
                                                opcao := op_simnao('S','Deseja fazer a BAIXA deste documento agora [S/n]:')
                                                IF opcao = 'S'
                                                        sr_getconnection():exec("UPDATE sacdupr SET datope = " + sr_cdbvalue(mdata_sis)  +;
                                                                ",datpag  = " + sr_cdbvalue(mvenc)+;
                                                                ",vlpago= " + sr_cdbvalue(mvalor)+;
                                                                ",banco= " + sr_cdbvalue('C')+;
                                                                ",pago= " + sr_cdbvalue('B')+;
                                                                ",hora_bx  = " + sr_cdbvalue(TIME())+;
                                                                " WHERE sr_recno = " + sr_cdbvalue(aret[point,65]),,.f.)
                                                        sr_getconnection():exec("COMMIT",,.f.)
                                                ENDIF
                                        ENDIF
                                        *****************
                                        SELE(malias);ORDSETFOCUS(1)
                                        *****************
                                        DBUNLOCKALL()
                                        DBCOMMITALL()
                                        IF mtp = 'P'
                                                wvw_lclosewindow()
                                                LOOP
                                        ENDIF
                                        IF ver_serie() = '975976'
                                                opcao := op_simnao('S','Deseja Imprimir o RECIBO [S/n]:')
                                                IF opcao = 'N'
                                                        wvw_lclosewindow()
                                                        LOOP
                                                ENDIF
                                                sac63(mnome_cli,mvalor,mvenc)
                                                LOOP
                                        ENDIF
                                        IF ! imp_arq('ALT_DUPR.REL','D')
                                                wvw_lclosewindow()
                                                LOOP
                                        ENDIF
                                        IF ver_serie() = '141236'
                                                dup_sot(aret[point,10],aret[point,35],aret[point,5],aret[point,4],aret[point,11],;
                                                        aret[point,8],mfornec,cli->endereco,cli->bairro,cli->cidade,;
                                                        cli->uf,cli->cep,cli->cgc,cli->insc,cli->cpf)
                                        ELSE
                                                dup_sis(aret[point,8],mfornec,cli->endereco,cli->bairro,cli->cidade,cli->uf,cli->cep,cli->tel1,;
                                                        cli->cgc,cli->insc,cli->cpf,cli->end_cob,cli->bairro_cob,cli->cidade_cob,cli->uf_cob,cli->cep_cob,cli->fone_cob,;
                                                        mtipo,aret[point,4],aret[point,10],aret[point,11],VAL(aret[point,35]),aret[point,5],cli->nome)
                                        ENDIF
                                        SETPRC(00,00)
                                        SET DEVI TO SCREEN;SET PRINT TO;SET PRINT OFF
                                        conf_impressao('ALT_DUPR.REL')
                                        wvw_lclosewindow()
                                ENDIF
                ENDCASE
        ENDIF
ENDDO
wvw_lclosewindow()
RETURN NIL
