*-----------------------------------------------------
USE sacsen INDEX sen_sen,sen_cod ALIAS sen SHARED NEW
*-----------------------------------------------------
USE sacicm INDEX icmdat,icmdoc ALIAS icm SHARED NEW
*----------------------------------------------
USE sacmerc INDEX merc_cod,merc_gru,merc_mer,merc_fab ALIAS cad SHARED NEW
*------------------------------------------------------------------
USE sacforn INDEX sacforn1,sacforn2 ALIAS forn SHARED NEW
*--------------------------------------------------
USE sacrep INDEX rep_cod,rep_nome ALIAS rep SHARED NEW
*---------------------------------------------------------------------
USE saccli INDEX saccli1,saccli2,saccli3,saccli4 ALIAS cli SHARED NEW
*---------------------------------------------------------------------
USE sacbanco INDEX bancos ALIAS ban SHARED NEW
*-----------------------------------------------
USE sacnota INDEX nota_num ALIAS nota SHARED NEW
*---------------------------------------------
USE sacped_e INDEX pede_num,pede_cod ALIAS ped_e SHARED NEW
*--------------------------------------
USE sacped_s INDEX peds_num,peds_dat,peds_pag ALIAS ped_s SHARED NEW
*--------------------------------------
USE sacmov INDEX mov_data,mov_cod,mov_vend,mov_doc ALIAS mov SHARED NEW
*-----------------------------------------------
USE sacfofb INDEX sacfofb ALIAS fof SHARED NEW
*-----------------------------------------------
USE sacrefb INDEX sacrefb ALIAS ref SHARED NEW
*-----------------------------------------------
USE saccarta INDEX cartao ALIAS car SHARED NEW
*---------------------------------------------
USE sacuf INDEX sacuf ALIAS tabuf SHARED NEW
*-------------------------------------------
USE saccaixa INDEX caixa1,caixa2,caixa3,caixa4,caixa5 ALIAS caix SHARED NEW
*-----------------------------------------------------
USE saccheq INDEX cheq_cli,cheq_num ALIAS cheq SHARED NEW
*-----------------------------------------------------
USE sacrec INDEX sacrec ALIAS rec SHARED NEW
*-------------------------------------------
USE sacdupr INDEX sacdupr1,sacdupr2,sacdupr3,sacdupr4,sacdupr5 ALIAS dupr SHARED NEW
*------------------------------------------------------------------------------------
USE sacdupp INDEX sacdupp1,sacdupp2,sacdupp3,sacdupp4,sacdupp5 ALIAS dupp SHARED NEW
*------------------------------------------------------------------------
USE sacpag INDEX sacpag ALIAS pag SHARED NEW
*-----------------------------------------------
USE sacfluxo INDEX fluxo ALIAS flux SHARED NEW
*---------------------------------------

