/*
 * xHarbour build 0.99.70 Intl. (SimpLex)
 * Generated C source code from <errorsys.prg>
 * Command: C:\xHarbour997\bin\harbour.exe C:\HTI\SISMED\errorsys.prg /q /oC:\HTI\SISMED\errorsys.c /M /N -DxHB -DXHB_0990 -DXHB_0991 -DXHB_0992 -DXHB_0993 -DXHB_0994 -DXHB_09941 -DXHB_09950 -DXHB_09951a -DXHB_09951 -DXHB_09951b -DXHB_0996 -DXHB_09960 -DXHB_09961 -DXHB_09961B -DXHB_0997 -DXHB_09970 
 * Created: 2023.10.18 11:23:23 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "errorsys.prg"

HB_FUNC( ERRORSYS );
HB_FUNC_STATIC( DEFERROR );
HB_FUNC( ERRORMESSAGE );
HB_FUNC_STATIC( ERRORPREVIEW );
HB_FUNC_EXTERN( ERRORBLOCK );
HB_FUNC_EXTERN( DTOS );
HB_FUNC_EXTERN( DATE );
HB_FUNC_EXTERN( STRTRAN );
HB_FUNC_EXTERN( TIME );
HB_FUNC_EXTERN( OP_TELA );
HB_FUNC_EXTERN( DEVPOS );
HB_FUNC_EXTERN( DEVOUT );
HB_FUNC_EXTERN( INKEY );
HB_FUNC_EXTERN( WVW_LCLOSEWINDOW );
HB_FUNC_EXTERN( SR_ADDCONNECTION );
HB_FUNC_EXTERN( ALLTRIM );
HB_FUNC_EXTERN( LASTKEY );
HB_FUNC_EXTERN( NETERR );
HB_FUNC_EXTERN( EMPTY );
HB_FUNC_EXTERN( LTRIM );
HB_FUNC_EXTERN( STR );
HB_FUNC_EXTERN( PROCNAME );
HB_FUNC_EXTERN( PROCFILE );
HB_FUNC_EXTERN( PROCLINE );
HB_FUNC_EXTERN( REPLICATE );
HB_FUNC_EXTERN( DTOC );
HB_FUNC_EXTERN( HB_CMDARGARGV );
HB_FUNC_EXTERN( NETNAME );
HB_FUNC_EXTERN( MEMORY );
HB_FUNC_EXTERN( DISKSPACE );
HB_FUNC_EXTERN( CURDIR );
HB_FUNC_EXTERN( OS );
HB_FUNC_EXTERN( HB_ISNULL );
HB_FUNC_EXTERN( MEMOWRIT );
HB_FUNC_EXTERN( ATENCAO );
HB_FUNC_EXTERN( __QUIT );
HB_FUNC_EXTERN( HB_ISSTRING );
HB_FUNC_EXTERN( HB_ISNUMERIC );
HB_FUNC_EXTERN( SPACE );
HB_FUNC_EXTERN( __MVPRIVATE );
HB_FUNC_EXTERN( SET );
HB_FUNC_EXTERN( IMP_ARQ );
HB_FUNC_EXTERN( IMPRT );
HB_FUNC_EXTERN( MEMOLINE );
HB_FUNC_EXTERN( MEMOREAD );
HB_FUNC_EXTERN( MLCOUNT );
HB_FUNC_EXTERN( PROW );
HB_FUNC_EXTERN( FCLOSE );
HB_FUNC_EXTERN( MYRUN );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 7

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_ERRORSYS )
{ "ERRORSYS", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( ERRORSYS )}, NULL },
{ "ERRORBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERRORBLOCK )}, NULL },
{ "DEFERROR", {HB_FS_STATIC | HB_FS_LOCAL}, {HB_FUNCNAME( DEFERROR )}, NULL },
{ "DTOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DTOS )}, NULL },
{ "DATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DATE )}, NULL },
{ "STRTRAN", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRTRAN )}, NULL },
{ "TIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( TIME )}, NULL },
{ "GENCODE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OSCODE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OP_TELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_TELA )}, NULL },
{ "DEVPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVPOS )}, NULL },
{ "DEVOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUT )}, NULL },
{ "INKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( INKEY )}, NULL },
{ "WVW_LCLOSEWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_LCLOSEWINDOW )}, NULL },
{ "NCNN", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SR_ADDCONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ADDCONNECTION )}, NULL },
{ "CONNECT_FIREBIRD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "ALLTRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( ALLTRIM )}, NULL },
{ "M_CFG", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LASTKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( LASTKEY )}, NULL },
{ "NETERR", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETERR )}, NULL },
{ "CANDEFAULT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "ERRORMESSAGE", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( ERRORMESSAGE )}, NULL },
{ "EMPTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EMPTY )}, NULL },
{ "LTRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( LTRIM )}, NULL },
{ "STR", {HB_FS_PUBLIC}, {HB_FUNCNAME( STR )}, NULL },
{ "PROCNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( PROCNAME )}, NULL },
{ "PROCFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PROCFILE )}, NULL },
{ "PROCLINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PROCLINE )}, NULL },
{ "REPLICATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( REPLICATE )}, NULL },
{ "DTOC", {HB_FS_PUBLIC}, {HB_FUNCNAME( DTOC )}, NULL },
{ "M_SET", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SISTEMA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVERSAO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "COD_OPERADO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "HB_CMDARGARGV", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_CMDARGARGV )}, NULL },
{ "NETNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETNAME )}, NULL },
{ "MEMORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( MEMORY )}, NULL },
{ "DISKSPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DISKSPACE )}, NULL },
{ "CURDIR", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURDIR )}, NULL },
{ "OS", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS )}, NULL },
{ "HB_ISNULL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ISNULL )}, NULL },
{ "MEMOWRIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MEMOWRIT )}, NULL },
{ "MDEFCAM_IMP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "ATENCAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATENCAO )}, NULL },
{ "ERRORPREVIEW", {HB_FS_STATIC | HB_FS_LOCAL}, {HB_FUNCNAME( ERRORPREVIEW )}, NULL },
{ "__QUIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( __QUIT )}, NULL },
{ "SEVERITY", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "HB_ISSTRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ISSTRING )}, NULL },
{ "SUBSYSTEM", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "HB_ISNUMERIC", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ISNUMERIC )}, NULL },
{ "SUBCODE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DESCRIPTION", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "FILENAME", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OPERATION", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTIPO_IMP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MIMP_TIPO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MARQ", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPACE )}, NULL },
{ "__MVPRIVATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVPRIVATE )}, NULL },
{ "SET", {HB_FS_PUBLIC}, {HB_FUNCNAME( SET )}, NULL },
{ "IMP_ARQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( IMP_ARQ )}, NULL },
{ "IMPRT", {HB_FS_PUBLIC}, {HB_FUNCNAME( IMPRT )}, NULL },
{ "MEMOLINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( MEMOLINE )}, NULL },
{ "MEMOREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( MEMOREAD )}, NULL },
{ "MLCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MLCOUNT )}, NULL },
{ "PROW", {HB_FS_PUBLIC}, {HB_FUNCNAME( PROW )}, NULL },
{ "FCLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FCLOSE )}, NULL },
{ "MYRUN", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYRUN )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_ERRORSYS )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_ERRORSYS
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_ERRORSYS = hb_vm_SymbolInit_ERRORSYS;
   #pragma data_seg()
#endif

HB_FUNC( ERRORSYS )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 37, 0,	/* 37 */
	HB_P_PUSHSYMNEAR, 1,	/* ERRORBLOCK */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 15, 0,	/* 15 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 2,	/* DEFERROR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_DOSHORT, 1,
/* 00023 */ HB_P_LINEOFFSET, 1,	/* 38 */
	HB_P_ENDPROC
/* 00026 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( DEFERROR )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 4, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 42, 0,	/* 42 */
	HB_P_PUSHSYMNEAR, 3,	/* DTOS */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 4,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSYMNEAR, 5,	/* STRTRAN */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 6,	/* TIME */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	':', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'_', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'.', 'l', 'o', 'g', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 4,	/* CLOGFILE */
/* 00045 */ HB_P_LINEOFFSET, 17,	/* 59 */
	HB_P_MESSAGE, 7, 0,	/* GENCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00064) */
/* 00059 */ HB_P_LINEOFFSET, 18,	/* 60 */
	HB_P_ZERO,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00064 */ HB_P_LINEOFFSET, 21,	/* 63 */
	HB_P_MESSAGE, 8, 0,	/* OSCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 64,	/* 64 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSE, 2, 1,	/* 258 (abs: 00334) */
/* 00079 */ HB_P_LINEOFFSET, 22,	/* 64 */
	HB_P_PUSHSYMNEAR, 9,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHBYTE, 80,	/* 80 */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'A', 't', 'e', 'n', 231, 227, 'o', 0, 
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 7,
/* 00106 */ HB_P_LINEOFFSET, 23,	/* 65 */
	HB_P_PUSHSYMNEAR, 10,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 11,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 70,	/* 70 */
	'T', 'e', 'r', 'm', 'i', 'n', 'a', 'l', ' ', 'f', 'o', 'i', ' ', 'd', 'e', 's', 'c', 'o', 'n', 'e', 'c', 't', 'a', 'd', 'o', ' ', 'd', 'o', ' ', 'S', 'E', 'R', 'V', 'I', 'D', 'O', 'R', '.', ' ', 'T', 'e', 'n', 't', 'a', 'r', ' ', 'n', 'o', 'v', 'a', 'm', 'e', 'n', 't', 'e', ' ', 'e', 'm', ' ', '2', ' ', 's', 'e', 'g', 'u', 'n', 'd', 'o', 's', 0, 
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 2,
/* 00195 */ HB_P_LINEOFFSET, 24,	/* 66 */
	HB_P_PUSHSYMNEAR, 12,	/* INKEY */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 1,
/* 00204 */ HB_P_LINEOFFSET, 25,	/* 67 */
	HB_P_PUSHSYMNEAR, 13,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00211 */ HB_P_LINEOFFSET, 26,	/* 68 */
	HB_P_PUSHVARIABLE, 14, 0,	/* NCNN */
	HB_P_ZERO,
	HB_P_LESS,
	HB_P_JUMPFALSENEAR, 86,	/* 86 (abs: 00304) */
/* 00220 */ HB_P_LINEOFFSET, 27,	/* 69 */
	HB_P_PUSHSYMNEAR, 15,	/* SR_ADDCONNECTION */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 16, 0,	/* CONNECT_FIREBIRD */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'F', 'I', 'R', 'E', 'B', 'I', 'R', 'D', '=', 0, 
	HB_P_PUSHSYMNEAR, 17,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 18, 0,	/* M_CFG */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 44,	/* 44 */
	';', 'u', 'i', 'd', '=', 'S', 'Y', 'S', 'D', 'B', 'A', ';', 'p', 'w', 'd', '=', 'm', 'a', 's', 't', 'e', 'r', 'k', 'e', 'y', ';', 'c', 'h', 'a', 'r', 's', 'e', 't', '=', 'I', 'S', 'O', '8', '8', '5', '9', '_', '1', 0, 
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 14, 0,	/* NCNN */
/* 00304 */ HB_P_LINEOFFSET, 29,	/* 71 */
	HB_P_PUSHSYMNEAR, 19,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 15,	/* 15 (abs: 00329) */
/* 00316 */ HB_P_LINEOFFSET, 30,	/* 72 */
	HB_P_PUSHSYMNEAR, 20,	/* NETERR */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_DOSHORT, 1,
/* 00324 */ HB_P_LINEOFFSET, 31,	/* 73 */
	HB_P_FALSE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00329 */ HB_P_LINEOFFSET, 33,	/* 75 */
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00334 */ HB_P_LINEOFFSET, 37,	/* 79 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_MESSAGE, 7, 0,	/* GENCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 13,	/* 13 (abs: 00361) */
	HB_P_POP,
	HB_P_MESSAGE, 8, 0,	/* OSCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 10,	/* 10 (abs: 00371) */
	HB_P_POP,
	HB_P_MESSAGE, 21, 0,	/* CANDEFAULT */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_JUMPFALSENEAR, 15,	/* 15 (abs: 00386) */
/* 00373 */ HB_P_LINEOFFSET, 38,	/* 80 */
	HB_P_PUSHSYMNEAR, 20,	/* NETERR */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_DOSHORT, 1,
/* 00381 */ HB_P_LINEOFFSET, 39,	/* 81 */
	HB_P_FALSE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00386 */ HB_P_LINEOFFSET, 42,	/* 84 */
	HB_P_FALSE,
	HB_P_MESSAGE, 7, 0,	/* GENCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 10,	/* 10 (abs: 00409) */
	HB_P_POP,
	HB_P_MESSAGE, 21, 0,	/* CANDEFAULT */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_JUMPFALSENEAR, 15,	/* 15 (abs: 00424) */
/* 00411 */ HB_P_LINEOFFSET, 43,	/* 85 */
	HB_P_PUSHSYMNEAR, 20,	/* NETERR */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_DOSHORT, 1,
/* 00419 */ HB_P_LINEOFFSET, 44,	/* 86 */
	HB_P_FALSE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00424 */ HB_P_LINEOFFSET, 46,	/* 88 */
	HB_P_PUSHSYMNEAR, 22,	/* ERRORMESSAGE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00435 */ HB_P_LINEOFFSET, 47,	/* 89 */
	HB_P_PUSHSYMNEAR, 23,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 8, 0,	/* OSCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 43,	/* 43 (abs: 00492) */
/* 00451 */ HB_P_LINEOFFSET, 48,	/* 90 */
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'(', 'D', 'O', 'S', ' ', 'E', 'r', 'r', 'o', 'r', ' ', 0, 
	HB_P_PUSHSYMNEAR, 24,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 25,	/* STR */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 8, 0,	/* OSCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	')', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 3,	/* CDOSERROR */
/* 00492 */ HB_P_LINEOFFSET, 71,	/* 113 */
	HB_P_PUSHSYMNEAR, 23,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 8, 0,	/* OSCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 16,	/* 16 (abs: 00522) */
/* 00508 */ HB_P_LINEOFFSET, 72,	/* 114 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PUSHLOCALNEAR, 3,	/* CDOSERROR */
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00522 */ HB_P_LINEOFFSET, 74,	/* 116 */
	HB_P_LOCALNEARSETINT, 5, 2, 0,	/* N 2*/
/* 00528 */ HB_P_LINEOFFSET, 75,	/* 117 */
	HB_P_PUSHSYMNEAR, 23,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 26,	/* PROCNAME */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 79,	/* 79 (abs: 00621) */
/* 00544 */ HB_P_LINEOFFSET, 76,	/* 118 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	13, 10, 'F', 'u', 'n', 'c', 'o', 'e', 's', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 27,	/* PROCFILE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'-', '>', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 26,	/* PROCNAME */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'(', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 17,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 25,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 28,	/* PROCLINE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_LOCALNEARADDINT, 5, 1, 0,	/* N 1*/
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	')', 0, 
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_JUMPNEAR, 165,	/* -91 (abs: 00528) */
/* 00621 */ HB_P_LINEOFFSET, 79,	/* 121 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	13, 10, 0, 
	HB_P_PUSHSYMNEAR, 29,	/* REPLICATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_PUSHBYTE, 120,	/* 120 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00645 */ HB_P_LINEOFFSET, 80,	/* 122 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'D', 'a', 't', 'a', ' ', 'e', ' ', 'H', 'o', 'r', 'a', '.', '.', '.', '.', '.', '.', '.', '.', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 30,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 4,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '-', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 6,	/* TIME */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00702 */ HB_P_LINEOFFSET, 81,	/* 123 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'E', 'm', 'p', 'r', 'e', 's', 'a', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', ':', ' ', 0, 
	HB_P_PUSHMEMVAR, 31, 0,	/* M_SET */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 23,	/* 23 */
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00744 */ HB_P_LINEOFFSET, 82,	/* 124 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'S', 'i', 's', 't', 'e', 'm', 'a', '/', 'A', 't', 'u', 'a', 'l', 'i', 'z', 'a', 'c', 'a', 'o', ':', ' ', 0, 
	HB_P_PUSHVARIABLE, 32, 0,	/* SISTEMA */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '-', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 33, 0,	/* MVERSAO */
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00792 */ HB_P_LINEOFFSET, 83,	/* 125 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'U', 's', 'u', 'a', 'r', 'i', 'o', ' ', 'd', 'o', ' ', 'S', 'i', 's', 't', 'e', 'm', 'a', '.', ':', ' ', 0, 
	HB_P_PUSHVARIABLE, 34, 0,	/* COD_OPERADO */
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00829 */ HB_P_LINEOFFSET, 84,	/* 126 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'N', 'o', 'm', 'e', ' ', 'd', 'o', ' ', 'E', 'x', 'e', 'c', 'u', 't', 'a', 'v', 'e', 'l', '.', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 35,	/* HB_CMDARGARGV */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00868 */ HB_P_LINEOFFSET, 85,	/* 127 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'N', 'o', 'm', 'e', ' ', 'd', 'o', ' ', 'M', 'i', 'c', 'r', 'o', '.', '.', '.', '.', '.', '.', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 36,	/* NETNAME */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	' ', '-', ' ', 'N', 'o', 'm', 'e', ' ', 'T', 'e', 'r', 'm', 'i', 'n', 'a', 'l', ':', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 36,	/* NETNAME */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00936 */ HB_P_LINEOFFSET, 86,	/* 128 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'M', 'e', 'm', 'o', 'r', 'i', 'a', ' ', 'D', 'i', 's', 'p', 'o', 'n', 'i', 'v', 'e', 'l', '.', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 17,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 25,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 37,	/* MEMORY */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 25,	/* 25 */
	' ', '-', ' ', 'E', 's', 'p', 'a', 231, 'o', ' ', 'e', 'm', ' ', 'D', 'i', 's', 'c', 'o', '.', '.', '.', '.', ':', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 17,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 25,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 38,	/* DISKSPACE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 01030 */ HB_P_LINEOFFSET, 87,	/* 129 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'P', 'a', 's', 't', 'a', ' ', 'd', 'e', ' ', 'D', 'i', 'r', 'e', 't', 'o', 'r', 'i', 'o', '.', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 39,	/* CURDIR */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 01069 */ HB_P_LINEOFFSET, 88,	/* 130 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'S', 'i', 's', 't', 'e', 'm', 'a', ' ', 'O', 'p', 'e', 'r', 'a', 'c', 'i', 'o', 'n', 'a', 'l', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 40,	/* OS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 01108 */ HB_P_LINEOFFSET, 89,	/* 131 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'C', 'a', 'm', 'i', 'n', 'h', 'o', ' ', 'd', 'o', ' ', 'B', 'a', 'n', 'c', 'o', '.', '.', '.', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 41,	/* HB_ISNULL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 18, 0,	/* M_CFG */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 10,	/* 10 (abs: 01156) */
	HB_P_PUSHMEMVAR, 18, 0,	/* M_CFG */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPUSH,
	HB_P_JUMPNEAR, 5,	/* 5 (abs: 01159) */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 01163 */ HB_P_LINEOFFSET, 92,	/* 134 */
	HB_P_PUSHSYMNEAR, 42,	/* MEMOWRIT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 43, 0,	/* MDEFCAM_IMP */
	HB_P_PUSHLOCALNEAR, 4,	/* CLOGFILE */
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_DOSHORT, 2,
/* 01178 */ HB_P_LINEOFFSET, 93,	/* 135 */
	HB_P_PUSHSYMNEAR, 44,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_DOSHORT, 1,
/* 01187 */ HB_P_LINEOFFSET, 94,	/* 136 */
	HB_P_PUSHSYMNEAR, 45,	/* ERRORPREVIEW */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHLOCALNEAR, 4,	/* CLOGFILE */
	HB_P_DOSHORT, 2,
/* 01198 */ HB_P_LINEOFFSET, 96,	/* 138 */
	HB_P_PUSHSYMNEAR, 46,	/* __QUIT */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01205 */ HB_P_LINEOFFSET, 97,	/* 139 */
	HB_P_FALSE,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 01210 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( ERRORMESSAGE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 143, 0,	/* 143 */
	HB_P_MESSAGE, 47, 0,	/* SEVERITY */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_ONE,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 12,	/* 12 (abs: 00027) */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'E', 'r', 'r', 'o', 'r', 0, 
	HB_P_JUMPNEAR, 12,	/* 12 (abs: 00037) */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'W', 'a', 'r', 'n', 'i', 'n', 'g', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00044 */ HB_P_LINEOFFSET, 1,	/* 144 */
	HB_P_PUSHSYMNEAR, 48,	/* HB_ISSTRING */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 49, 0,	/* SUBSYSTEM */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00076) */
/* 00060 */ HB_P_LINEOFFSET, 2,	/* 145 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_MESSAGE, 49, 0,	/* SUBSYSTEM */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_JUMPNEAR, 15,	/* 15 (abs: 00089) */
/* 00076 */ HB_P_LINEOFFSET, 4,	/* 147 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'?', '?', '?', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00089 */ HB_P_LINEOFFSET, 6,	/* 149 */
	HB_P_PUSHSYMNEAR, 50,	/* HB_ISNUMERIC */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 51, 0,	/* SUBCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 33,	/* 33 (abs: 00136) */
/* 00105 */ HB_P_LINEOFFSET, 7,	/* 150 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'/', 0, 
	HB_P_PUSHSYMNEAR, 24,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 25,	/* STR */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 51, 0,	/* SUBCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_JUMPNEAR, 16,	/* 16 (abs: 00150) */
/* 00136 */ HB_P_LINEOFFSET, 9,	/* 152 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'/', '?', '?', '?', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00150 */ HB_P_LINEOFFSET, 11,	/* 154 */
	HB_P_PUSHSYMNEAR, 48,	/* HB_ISSTRING */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 52, 0,	/* DESCRIPTION */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 22,	/* 22 (abs: 00186) */
/* 00166 */ HB_P_LINEOFFSET, 12,	/* 155 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	' ', ' ', 0, 
	HB_P_MESSAGE, 52, 0,	/* DESCRIPTION */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00186 */ HB_P_LINEOFFSET, 15,	/* 158 */
	HB_P_PUSHSYMNEAR, 23,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 53, 0,	/* FILENAME */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 24,	/* 24 (abs: 00224) */
/* 00202 */ HB_P_LINEOFFSET, 16,	/* 159 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	':', ' ', 0, 
	HB_P_MESSAGE, 53, 0,	/* FILENAME */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_JUMPNEAR, 38,	/* 38 (abs: 00260) */
/* 00224 */ HB_P_LINEOFFSET, 17,	/* 160 */
	HB_P_PUSHSYMNEAR, 23,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 54, 0,	/* OPERATION */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 22,	/* 22 (abs: 00260) */
/* 00240 */ HB_P_LINEOFFSET, 18,	/* 161 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	':', ' ', 0, 
	HB_P_MESSAGE, 54, 0,	/* OPERATION */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00260 */ HB_P_LINEOFFSET, 20,	/* 163 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00266 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( ERRORPREVIEW )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 7, 2,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 168, 0,	/* 168 */
	HB_P_LOCALNEARSETINT, 3, 0, 0,	/* POINT 0*/
	HB_P_LOCALNEARSETSTR, 7, 2, 0,	/* OPCAO 2*/
	' ', 0, 
	HB_P_LOCALNEARSETSTR, 8, 1, 0,	/* MSUBJECT 1*/
	0, 
	HB_P_LOCALNEARSETSTR, 9, 1, 0,	/* MLINHA1 1*/
	0, 
/* 00026 */ HB_P_LINEOFFSET, 1,	/* 169 */
	HB_P_ZERO,
	HB_P_PUSHSYMNEAR, 58,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 35,	/* 35 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSYMNEAR, 59,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 55,	/* MTIPO_IMP */
	HB_P_PUSHSYMNEAR, 56,	/* MIMP_TIPO */
	HB_P_PUSHSYMNEAR, 57,	/* MARQ */
	HB_P_DOSHORT, 3,
	HB_P_POPVARIABLE, 57, 0,	/* MARQ */
	HB_P_POPVARIABLE, 56, 0,	/* MIMP_TIPO */
/* 00053 */ HB_P_LINEOFFSET, 3,	/* 171 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'M', 0, 
	HB_P_POPVARIABLE, 55, 0,	/* MTIPO_IMP */
/* 00062 */ HB_P_LINEOFFSET, 5,	/* 173 */
	HB_P_PUSHSYMNEAR, 60,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'S', 'C', 'R', 'E', 'E', 'N', 0, 
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 60,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 60,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 23,	/* 23 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'O', 'F', 'F', 0, 
	HB_P_DOSHORT, 2,
/* 00103 */ HB_P_LINEOFFSET, 23,	/* 191 */
	HB_P_PUSHSYMNEAR, 61,	/* IMP_ARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'E', 'R', 'R', 'O', 'S', 'Y', 'S', '.', 'R', 'E', 'L', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'R', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPFALSE, 116, 1,	/* 372 (abs: 00500) */
/* 00131 */ HB_P_LINEOFFSET, 24,	/* 192 */
	HB_P_PUSHSYMNEAR, 62,	/* IMPRT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 55, 0,	/* MTIPO_IMP */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'C', 0, 
	HB_P_DOSHORT, 2,
/* 00145 */ HB_P_LINEOFFSET, 25,	/* 193 */
	HB_P_PUSHSYMNEAR, 63,	/* MEMOLINE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 64,	/* MEMOREAD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 43, 0,	/* MDEFCAM_IMP */
	HB_P_PUSHLOCALNEAR, 2,	/* CARQ */
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 120,	/* 120 */
	HB_P_ONE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 4,	/* LIN */
/* 00170 */ HB_P_LINEOFFSET, 26,	/* 194 */
	HB_P_LOCALNEARSETINT, 6, 0, 0,	/* LINHA 0*/
	HB_P_PUSHLOCALNEAR, 6,	/* LINHA */
	HB_P_POPLOCALNEAR, 5,	/* LINHAS */
/* 00180 */ HB_P_LINEOFFSET, 27,	/* 195 */
	HB_P_PUSHSYMNEAR, 65,	/* MLCOUNT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 64,	/* MEMOREAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 17,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 43, 0,	/* MDEFCAM_IMP */
	HB_P_PUSHLOCALNEAR, 2,	/* CARQ */
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 120,	/* 120 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 5,	/* LINHAS */
/* 00207 */ HB_P_LINEOFFSET, 28,	/* 196 */
	HB_P_LOCALNEARSETINT, 6, 1, 0,	/* LINHA 1*/
	HB_P_PUSHLOCALNEAR, 6,	/* LINHA */
	HB_P_PUSHLOCALNEAR, 5,	/* LINHAS */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 69,	/* 69 (abs: 00287) */
/* 00220 */ HB_P_LINEOFFSET, 29,	/* 197 */
	HB_P_PUSHSYMNEAR, 63,	/* MEMOLINE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 64,	/* MEMOREAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 17,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 43, 0,	/* MDEFCAM_IMP */
	HB_P_PUSHLOCALNEAR, 2,	/* CARQ */
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 120,	/* 120 */
	HB_P_PUSHLOCALNEAR, 6,	/* LINHA */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 4,	/* LIN */
/* 00251 */ HB_P_LINEOFFSET, 30,	/* 198 */
	HB_P_PUSHSYMNEAR, 10,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 66,	/* PROW */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 11,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 17,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* LIN */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 1,
/* 00279 */ HB_P_LINEOFFSET, 31,	/* 199 */
	HB_P_LOCALNEARADDINT, 6, 1, 0,	/* LINHA 1*/
	HB_P_JUMPNEAR, 184,	/* -72 (abs: 00213) */
/* 00287 */ HB_P_LINEOFFSET, 32,	/* 200 */
	HB_P_PUSHSYMNEAR, 62,	/* IMPRT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 55, 0,	/* MTIPO_IMP */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_DOSHORT, 2,
/* 00301 */ HB_P_LINEOFFSET, 33,	/* 201 */
	HB_P_PUSHSYMNEAR, 60,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'S', 'C', 'R', 'E', 'E', 'N', 0, 
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 60,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 60,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 23,	/* 23 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'O', 'F', 'F', 0, 
	HB_P_DOSHORT, 2,
/* 00342 */ HB_P_LINEOFFSET, 34,	/* 202 */
	HB_P_PUSHVARIABLE, 56, 0,	/* MIMP_TIPO */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 73,	/* 73 (abs: 00423) */
/* 00352 */ HB_P_LINEOFFSET, 35,	/* 203 */
	HB_P_PUSHSYMNEAR, 67,	/* FCLOSE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'H', 'T', 'I', '.', 'R', 'E', 'L', 0, 
	HB_P_DOSHORT, 1,
/* 00369 */ HB_P_LINEOFFSET, 36,	/* 204 */
	HB_P_PUSHSYMNEAR, 68,	/* MYRUN */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 23,	/* 23 */
	'D', 'O', 'S', 'P', 'R', 'I', 'N', 'T', 'E', 'R', ' ', '/', 'S', 'E', 'L', '2', ' ', '/', 'D', 'E', 'L', ' ', 0, 
	HB_P_PUSHSYMNEAR, 17,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'H', 'T', 'I', '.', 'R', 'E', 'L', 0, 
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_JUMPNEAR, 79,	/* 79 (abs: 00500) */
/* 00423 */ HB_P_LINEOFFSET, 37,	/* 205 */
	HB_P_PUSHVARIABLE, 56, 0,	/* MIMP_TIPO */
	HB_P_ONE,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 70,	/* 70 (abs: 00500) */
/* 00432 */ HB_P_LINEOFFSET, 38,	/* 206 */
	HB_P_PUSHSYMNEAR, 67,	/* FCLOSE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'H', 'T', 'I', '.', 'R', 'E', 'L', 0, 
	HB_P_DOSHORT, 1,
/* 00449 */ HB_P_LINEOFFSET, 39,	/* 207 */
	HB_P_PUSHSYMNEAR, 68,	/* MYRUN */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 22,	/* 22 */
	'D', 'O', 'S', 'P', 'R', 'I', 'N', 'T', 'E', 'R', ' ', '/', 'S', 'E', 'L', ' ', '/', 'D', 'E', 'L', ' ', 0, 
	HB_P_PUSHSYMNEAR, 17,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'H', 'T', 'I', '.', 'R', 'E', 'L', 0, 
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
/* 00500 */ HB_P_LINEOFFSET, 42,	/* 210 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00505 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

