*#include "SIXCDX.CH"
#INCLUDE "wingdi.ch"
#INCLUDE "winuser.ch"
MEMVAR getlist
*****************************
* CONFIGURACAO DE TERMINAIS
*****************************
FUNCTION saccfg(mnao)
***************
LOCAL mnum_term:='   '
op_tela(10,0,35,120,'CONFIGURACAO INDIVIDUAL DO TERMINAL',,'*')
m_cfg[1] := m_cfg[1] + SPACE(10)
m_cfg[4] := m_cfg[4] + SPACE(10)
IF EMPTY(m_cfg[6])
        m_cfg[6] := ' '
ENDIF
WHILE .T.
	m_bkp := {}
	lin := MEMOLINE(MEMOREAD('SACBKP.INI'),210,1,,)
	linhas := linha := 0
	linhas := MLCOUNT(MEMOREAD('SACBKP.INI'),210)
	FOR linha = 1 TO  linhas
	        lin := MEMOLINE(MEMOREAD('SACBKP.INI'),210,linha,,)
	        IF SUBSTR(lin,5,1) = 'C'
	                AADD(m_bkp,ALLTRIM(SUBSTR(lin,30))+SPACE(120-LEN(ALLTRIM(SUBSTR(lin,30)))))
	        ELSE
	                AADD(m_bkp,VAL(SUBSTR(lin,30)))
	        ENDIF
	NEXT
	fclose('sacbkp.ini')

        IF mnao # NIL
                m_cfg:={}
                AADD(m_cfg,{NETNAME(),'T',SPACE(20),SPACE(20),mversao,' '})
        ENDIF
        //mnum_term := ver_ini()
        DEVPOS(1,1);DEVOUT('Terminal.................:')
        DEVPOS(2,1);DEVOUT('Tipo[S]ervidor [T]erminal:')
        DEVPOS(3,1);DEVOUT('Caminho BANCO DE DADOS...:')
        DEVPOS(4,1);DEVOUT('Tipo de Configura da Tela:')
        @ 5,0 TO 5,120
        DEVPOS(6,1);DEVOUT('  CONFIGURACAO BACKUP')
        @ 7,0 TO 7,120
        DEVPOS(8,1 );DEVOUT('EXECUTAVEL..............:')
        DEVPOS(9,1 );DEVOUT('NOME DO ARQUIVO.........:')
        DEVPOS(10,1);DEVOUT('ARQUIVOS P/COMPACTAR....:')
        DEVPOS(11,1);DEVOUT('1 -CAMINHO P/ BACKUP....:')
        DEVPOS(12,1);DEVOUT('   QTD DIAS ARQUIVADO...:')
        DEVPOS(13,1);DEVOUT('2 -CAMINHO P/ BACKUP....:')
        DEVPOS(14,1);DEVOUT('   QTD DIAS ARQUIVADO...:')
        DEVPOS(15,1);DEVOUT('3 -CAMINHO P/ BACKUP....:')
        DEVPOS(16,1);DEVOUT('   QTD DIAS ARQUIVADO...:')
        DEVPOS(17,1);DEVOUT('4 -CAMINHO P/ BACKUP....:')
        DEVPOS(18,1);DEVOUT('   QTD DIAS ARQUIVADO...:')
        DEVPOS(19,1);DEVOUT('5 -CAMINHO P/ BACKUP....:')
        DEVPOS(20,1);DEVOUT('   QTD DIAS ARQUIVADO...:')
        DEVPOS(21,1);DEVOUT('6 -CAMINHO P/ BACKUP....:')
        DEVPOS(22,1);DEVOUT('   QTD DIAS ARQUIVADO...:')

        @ 1,28 GET m_cfg[1] PICT '@!'
        @ 2,28 GET m_cfg[2] PICT '@!'
        @ 3,28 GET m_cfg[4] PICT '@!S40'
        @ 4,28 GET m_cfg[6] PICT '@!'

        @ 8,28 GET m_bkp[1] PICT '@!S90'
        @ 9,28 GET m_bkp[2] PICT '@!S90'
        @ 10,28 GET m_bkp[3] PICT '@!S90'
        @ 11,28 GET m_bkp[4] PICT '@!S90'
        @ 12,28 GET m_bkp[5] PICT '9999'
        @ 13,28 GET m_bkp[6] PICT '@!S90'
        @ 14,28 GET m_bkp[7] PICT '9999'
        @ 15,28 GET m_bkp[8] PICT '@!S90'
        @ 16,28 GET m_bkp[9] PICT '9999'
        @ 17,28 GET m_bkp[10] PICT '@!S90'
        @ 18,28 GET m_bkp[11] PICT '9999'
        @ 19,28 GET m_bkp[12] PICT '@!S90'
        @ 20,28 GET m_bkp[13] PICT '9999'
        @ 21,28 GET m_bkp[14] PICT '@!S90'
        @ 22,28 GET m_bkp[15] PICT '9999'
        READ
        IF LASTKEY() = 27 .OR. 'N' = op_simnao('S','Confirma as Configuracoes:')
                EXIT
        ENDIF
        FCLOSE('saccfg.ini')
	MYRUN('REN saccfg.ini saccfg01.ini')
        mArq        := fcreate("saccfg.ini" )
        sLinhas := '001 C Estacao               ='+m_cfg[1]     +m_qp+ ;
                   '002 C Tipo de Terminal      ='+m_cfg[2]     +m_qp+ ;
                   '003 C md5                   ='+m_md5       +m_qp+ ;
                   '004 C Caminho Banco Dados   ='+m_cfg[4]    +m_qp+ ;
                   '005 C Versao do Sistema     ='+m_cfg[5]    +m_qp+ ;
                   '006 C Tipo de Tela          ='+m_cfg[6]    +m_qp+ ;
                   '007 C Codigo da Empresa     ='+m_cfg[7]
        fwrite( mArq, @sLinhas, len( sLinhas ) )
        FCLOSE(mArq)

        FCLOSE('sacbkp.ini')
	MYRUN('REN sacbkp.ini sacbkp01.ini')
        //FCREATE('saccfg.ini' )
        mArq        := fcreate("sacbkp.ini" )
        sLinhas := '001 C EXECUTAVEL            ='+m_bkp[1]    +m_qp+ ;
                   '002 C NOME DO ARQUIVO       ='+m_bkp[2]    +m_qp+ ;
                   '003 C ARQUIVOS P/COMPACTAR  ='+m_bkp[3]    +m_qp+ ;
                   '004 C 1 -CAMINHO P/ BACKUP  ='+m_bkp[4]    +m_qp+ ;
                   '005 N QTD DIAS ARQUIVADO    ='+STRZERO(m_bkp[5],4)    +m_qp+ ;
                   '006 C 2 -CAMINHO P/ BACKUP  ='+m_bkp[6]    +m_qp+ ;
                   '007 N QTD DIAS ARQUIVADO    ='+STRZERO(m_bkp[7],4)    +m_qp+ ;
                   '008 C 3 -CAMINHO P/ BACKUP  ='+m_bkp[8]    +m_qp+ ;
                   '009 N QTD DIAS ARQUIVADO    ='+STRZERO(m_bkp[9],4)    +m_qp+ ;
                   '010 C 4 -CAMINHO P/ BACKUP  ='+m_bkp[10]    +m_qp+ ;
                   '011 N QTD DIAS ARQUIVADO    ='+STRZERO(m_bkp[11],4)    +m_qp+ ;
                   '012 C 5 -CAMINHO P/ BACKUP  ='+m_bkp[12]    +m_qp+ ;
                   '013 N QTD DIAS ARQUIVADO    ='+STRZERO(m_bkp[13],4)    +m_qp+ ;
                   '014 C 6 -CAMINHO P/ BACKUP  ='+m_bkp[14]    +m_qp+ ;
                   '015 N QTD DIAS ARQUIVADO    ='+STRZERO(m_bkp[15],4)
        fwrite( mArq, @sLinhas, len( sLinhas ) )
        FCLOSE(mArq)
        EXIT
ENDDO
wvw_lclosewindow()
RETURN .T.
************************* F I M ***********************************
* CONFIGURACAO DE TERMINAIS
*****************************
FUNCTION sacbkp(mnao)
***************
fclose('HTIBKP.INI')
MYRUN('DEL HTIBKP.INI')
SET DEVI TO PRINT;SET PRINT ON
SET PRINT TO ('HTIBKP.INI')
DEVPOS(PROW()  ,00);DEVOUT('001 C EXECUTAVEL            =2')
DEVPOS(PROW()+1,00);DEVOUT('002 C NOME DO ARQUIVO       =HTIBKP')
DEVPOS(PROW()+1,00);DEVOUT('003 C ARQUIVOS P/COMPACTAR  =SISMED.GDB SISMED.EXE *.DLL *.INI')
DEVPOS(PROW()+1,00);DEVOUT('004 C 1 -CAMINHO P/ BACKUP  =C:\SISCFG\')
DEVPOS(PROW()+1,00);DEVOUT('005 N QTD DIAS ARQUIVADO    =7')
DEVPOS(PROW()+1,00);DEVOUT('006 C 2 -CAMINHO P/ BACKUP  =')
DEVPOS(PROW()+1,00);DEVOUT('007 N QTD DIAS ARQUIVADO    =')
DEVPOS(PROW()+1,00);DEVOUT('008 C 3 -CAMINHO P/ BACKUP  =')
DEVPOS(PROW()+1,00);DEVOUT('009 N QTD DIAS ARQUIVADO    =')
DEVPOS(PROW()+1,00);DEVOUT('010 C 4 -CAMINHO P/ BACKUP  =')
DEVPOS(PROW()+1,00);DEVOUT('011 N QTD DIAS ARQUIVADO    =')
DEVPOS(PROW()+1,00);DEVOUT('012 C 5 -CAMINHO P/ BACKUP  =')
DEVPOS(PROW()+1,00);DEVOUT('013 N QTD DIAS ARQUIVADO    =')
DEVPOS(PROW()+1,00);DEVOUT('014 C 6 -CAMINHO P/ BACKUP  =')
DEVPOS(PROW()+1,00);DEVOUT('015 N QTD DIAS ARQUIVADO    =')
SETPRC(00,00)
SET PRINT TO;SET PRINT OFF;SET DEVI TO SCREEN
RETURN .T.
************************* F I M ***********************************


