/*
 * xHarbour build 0.99.70 Intl. (SimpLex)
 * Generated C source code from <SMED311.PRG>
 * Command: C:\xHarbour997\bin\harbour.exe C:\HTI\SISMED\SMED311.PRG /q /oC:\HTI\SISMED\SMED311.c /M /N -DxHB -DXHB_0990 -DXHB_0991 -DXHB_0992 -DXHB_0993 -DXHB_0994 -DXHB_09941 -DXHB_09950 -DXHB_09951a -DXHB_09951 -DXHB_09951b -DXHB_0996 -DXHB_09960 -DXHB_09961 -DXHB_09961B -DXHB_0997 -DXHB_09970 
 * Created: 2023.06.14 08:58:42 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "SMED311.PRG"

HB_FUNC( SMED311 );
HB_FUNC( DATA_PRO );
HB_FUNC_EXTERN( __MVPRIVATE );
HB_FUNC_EXTERN( VER_NIVEL );
HB_FUNC_EXTERN( OP_TELA );
HB_FUNC_EXTERN( EXIBI_PRG );
HB_FUNC_EXTERN( ASIZE );
HB_FUNC_EXTERN( SPACE );
HB_FUNC_EXTERN( CTOD );
HB_FUNC_EXTERN( MENSAGEM );
HB_FUNC_EXTERN( SETCOR );
HB_FUNC_EXTERN( DISPBOX );
HB_FUNC_EXTERN( SCROLL );
HB_FUNC_EXTERN( SETPOS );
HB_FUNC_EXTERN( DEVPOS );
HB_FUNC_EXTERN( DEVOUT );
HB_FUNC_EXTERN( STR );
HB_FUNC_EXTERN( INT );
HB_FUNC_EXTERN( DATE );
HB_FUNC_EXTERN( __ATPROMPT );
HB_FUNC_EXTERN( COL );
HB_FUNC_EXTERN( SET );
HB_FUNC_EXTERN( __MENUTO );
HB_FUNC_EXTERN( PCOUNT );
HB_FUNC_EXTERN( SAVESCREEN );
HB_FUNC_EXTERN( LASTKEY );
HB_FUNC_EXTERN( DBSELECTAREA );
HB_FUNC_EXTERN( ORDSETFOCUS );
HB_FUNC_EXTERN( HISTORICO1 );
HB_FUNC_EXTERN( HISTORICO2 );
HB_FUNC_EXTERN( HISTORICO3 );
HB_FUNC_EXTERN( HISTORICO4 );
HB_FUNC_EXTERN( OP_SIMNAO );
HB_FUNC_EXTERN( BLOQREG );
HB_FUNC_EXTERN( DBCOMMIT );
HB_FUNC_EXTERN( DBUNLOCK );
HB_FUNC_EXTERN( ADIREG );
HB_FUNC_EXTERN( ATENCAO );
HB_FUNC_EXTERN( RELATORI );
HB_FUNC_EXTERN( SMED700 );
HB_FUNC_EXTERN( DBUNLOCKALL );
HB_FUNC_EXTERN( WVW_LCLOSEWINDOW );
HB_FUNC_EXTERN( EMPTY );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 7

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_SMED311 )
{ "SMED311", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( SMED311 )}, NULL },
{ "MREG", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MNOME", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MCCONV", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MCPF", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "M_HIST", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "M_PONTO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__MVPRIVATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVPRIVATE )}, NULL },
{ "VER_NIVEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( VER_NIVEL )}, NULL },
{ "NIVEL_ACESS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MCONSULTA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OP_TELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_TELA )}, NULL },
{ "EXIBI_PRG", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXIBI_PRG )}, NULL },
{ "ASIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ASIZE )}, NULL },
{ "SPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPACE )}, NULL },
{ "CTOD", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTOD )}, NULL },
{ "CLI", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "CPF", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MENSAGEM", {HB_FS_PUBLIC}, {HB_FUNCNAME( MENSAGEM )}, NULL },
{ "REGISTRO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CODCONV", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "NOME", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SETCOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETCOR )}, NULL },
{ "DISPBOX", {HB_FS_PUBLIC}, {HB_FUNCNAME( DISPBOX )}, NULL },
{ "SCROLL", {HB_FS_PUBLIC}, {HB_FUNCNAME( SCROLL )}, NULL },
{ "SETPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETPOS )}, NULL },
{ "DEVPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVPOS )}, NULL },
{ "DEVOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUT )}, NULL },
{ "STR", {HB_FS_PUBLIC}, {HB_FUNCNAME( STR )}, NULL },
{ "INT", {HB_FS_PUBLIC}, {HB_FUNCNAME( INT )}, NULL },
{ "DATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DATE )}, NULL },
{ "DATANS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MRSOC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "ESTCIVIL", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "ULT_MEST1", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "ULT_MEST2", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "ULT_MEST3", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "ULT_MEST4", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "ULT_MEST5", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PRO_NASC1", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PRO_NASC2", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PRO_NASC3", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PRO_NASC4", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PRO_NASC5", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DAT_NASC1", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DAT_NASC2", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DAT_NASC3", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DAT_NASC4", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DAT_NASC5", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SETESQ", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SETDIR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__ATPROMPT", {HB_FS_PUBLIC}, {HB_FUNCNAME( __ATPROMPT )}, NULL },
{ "COL", {HB_FS_PUBLIC}, {HB_FUNCNAME( COL )}, NULL },
{ "SET", {HB_FS_PUBLIC}, {HB_FUNCNAME( SET )}, NULL },
{ "__MENUTO", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MENUTO )}, NULL },
{ "PCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PCOUNT )}, NULL },
{ "SAVESCREEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAVESCREEN )}, NULL },
{ "LASTKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( LASTKEY )}, NULL },
{ "DBSELECTAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSELECTAREA )}, NULL },
{ "ORDSETFOCUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ORDSETFOCUS )}, NULL },
{ "HISTORICO1", {HB_FS_PUBLIC}, {HB_FUNCNAME( HISTORICO1 )}, NULL },
{ "HISTORICO2", {HB_FS_PUBLIC}, {HB_FUNCNAME( HISTORICO2 )}, NULL },
{ "HISTORICO3", {HB_FS_PUBLIC}, {HB_FUNCNAME( HISTORICO3 )}, NULL },
{ "HISTORICO4", {HB_FS_PUBLIC}, {HB_FUNCNAME( HISTORICO4 )}, NULL },
{ "OP_SIMNAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_SIMNAO )}, NULL },
{ "BLOQREG", {HB_FS_PUBLIC}, {HB_FUNCNAME( BLOQREG )}, NULL },
{ "MDATA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DATAULT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DBCOMMIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCOMMIT )}, NULL },
{ "DBUNLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBUNLOCK )}, NULL },
{ "ADIREG", {HB_FS_PUBLIC}, {HB_FUNCNAME( ADIREG )}, NULL },
{ "CONTR", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "DATACONS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CADNOME", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SITUACAO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MMOD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MODALIDADE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVALOR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "VALOR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MRECIB", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "RECIBO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "ATENCAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATENCAO )}, NULL },
{ "RELATORI", {HB_FS_PUBLIC}, {HB_FUNCNAME( RELATORI )}, NULL },
{ "SMED700", {HB_FS_PUBLIC}, {HB_FUNCNAME( SMED700 )}, NULL },
{ "DBUNLOCKALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBUNLOCKALL )}, NULL },
{ "WVW_LCLOSEWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_LCLOSEWINDOW )}, NULL },
{ "DATA_PRO", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( DATA_PRO )}, NULL },
{ "EMPTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EMPTY )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_SMED311 )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_SMED311
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_SMED311 = hb_vm_SymbolInit_SMED311;
   #pragma data_seg()
#endif

HB_FUNC( SMED311 )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 43, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 14, 0,	/* 14 */
	HB_P_LOCALNEARSETSTR, 1, 8, 0,	/* MPRG 8*/
	'S', 'M', 'E', 'D', '3', '1', '1', 0, 
	HB_P_LOCALNEARSETINT, 26, 0, 0,	/* MPONTO 0*/
/* 00022 */ HB_P_LINEOFFSET, 2,	/* 16 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_PUSHSYMNEAR, 7,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 1,	/* MREG */
	HB_P_PUSHSYMNEAR, 2,	/* MNOME */
	HB_P_PUSHSYMNEAR, 3,	/* MCCONV */
	HB_P_PUSHSYMNEAR, 4,	/* MCPF */
	HB_P_PUSHSYMNEAR, 5,	/* M_HIST */
	HB_P_PUSHSYMNEAR, 6,	/* M_PONTO */
	HB_P_DOSHORT, 6,
	HB_P_POPVARIABLE, 6, 0,	/* M_PONTO */
	HB_P_POPVARIABLE, 5, 0,	/* M_HIST */
/* 00053 */ HB_P_LINEOFFSET, 4,	/* 18 */
	HB_P_PUSHSYMNEAR, 8,	/* VER_NIVEL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* MPRG */
	HB_P_PUSHSTRSHORT, 39,	/* 39 */
	'*', '*', ' ', 'C', 'O', 'N', 'S', 'U', 'L', 'T', 'A', ' ', '*', '*', ' ', 'D', 'E', ' ', 'C', 'L', 'I', 'E', 'N', 'T', 'E', 'S', ' ', 'P', 'E', 'L', 'O', ' ', 'M', 'E', 'D', 'I', 'C', 'O', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'1', 0, 
	HB_P_PUSHVARIABLE, 9, 0,	/* NIVEL_ACESS */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_JUMPTRUENEAR, 7,	/* 7 (abs: 00117) */
/* 00112 */ HB_P_LINEOFFSET, 5,	/* 19 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00117 */ HB_P_LINEOFFSET, 7,	/* 21 */
	HB_P_LOCALNEARSETINT, 17, 0, 0,	/* CCI 0*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_POPLOCALNEAR, 16,	/* LCI */
/* 00127 */ HB_P_LINEOFFSET, 8,	/* 22 */
	HB_P_LOCALNEARSETINT, 18, 32, 0,	/* LBA 32*/
/* 00133 */ HB_P_LINEOFFSET, 9,	/* 23 */
	HB_P_LOCALNEARSETINT, 19, 79, 0,	/* CBA 79*/
/* 00139 */ HB_P_LINEOFFSET, 11,	/* 25 */
	HB_P_PUSHVARIABLE, 10, 0,	/* MCONSULTA */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'C', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 30,	/* 30 (abs: 00179) */
/* 00151 */ HB_P_LINEOFFSET, 12,	/* 26 */
	HB_P_PUSHSYMNEAR, 11,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	' ', 'C', 'o', 'n', 's', 'u', 'l', 't', 'a', ' ', 0, 
	HB_P_DOSHORT, 5,
	HB_P_JUMPNEAR, 39,	/* 39 (abs: 00216) */
/* 00179 */ HB_P_LINEOFFSET, 14,	/* 28 */
	HB_P_PUSHSYMNEAR, 11,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_PUSHSTRSHORT, 22,	/* 22 */
	' ', 'R', 'e', 't', 'o', 'r', 'n', 'o', ' ', 'd', 'e', ' ', 'C', 'o', 'n', 's', 'u', 'l', 't', 'a', ' ', 0, 
	HB_P_DOSHORT, 5,
/* 00216 */ HB_P_LINEOFFSET, 18,	/* 32 */
	HB_P_PUSHSYMNEAR, 12,	/* EXIBI_PRG */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* MPRG */
	HB_P_DOSHORT, 1,
/* 00225 */ HB_P_LINEOFFSET, 19,	/* 33 */
	HB_P_PUSHSYMNEAR, 13,	/* ASIZE */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 6, 0,	/* M_PONTO */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
/* 00236 */ HB_P_LINEOFFSET, 20,	/* 34 */
	HB_P_PUSHSYMNEAR, 13,	/* ASIZE */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 5, 0,	/* M_HIST */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
/* 00247 */ HB_P_LINEOFFSET, 21,	/* 35 */
	HB_P_PUSHSYMNEAR, 14,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 25,	/* MLIN6 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 24,	/* MLIN5 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 23,	/* MLIN4 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 22,	/* MLIN3 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 21,	/* MLIN2 */
	HB_P_POPLOCALNEAR, 20,	/* MLIN1 */
/* 00273 */ HB_P_LINEOFFSET, 22,	/* 36 */
	HB_P_PUSHSYMNEAR, 14,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 7,	/* MEXAME */
/* 00283 */ HB_P_LINEOFFSET, 23,	/* 37 */
	HB_P_PUSHSYMNEAR, 14,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 8,	/* MRADIOLOGIA */
/* 00293 */ HB_P_LINEOFFSET, 24,	/* 38 */
	HB_P_PUSHSYMNEAR, 14,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 13,	/* OPCAO */
/* 00303 */ HB_P_LINEOFFSET, 25,	/* 39 */
	HB_P_ZERO,
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 1, 0,	/* MREG */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 2,	/* TECLA */
	HB_P_POPLOCALNEAR, 10,	/* OPCAOHIS */
/* 00315 */ HB_P_LINEOFFSET, 26,	/* 40 */
	HB_P_PUSHSYMNEAR, 14,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 3, 0,	/* MCCONV */
/* 00327 */ HB_P_LINEOFFSET, 27,	/* 41 */
	HB_P_PUSHSYMNEAR, 14,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 35,	/* 35 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 2, 0,	/* MNOME */
/* 00339 */ HB_P_LINEOFFSET, 28,	/* 42 */
	HB_P_PUSHSYMNEAR, 15,	/* CTOD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	' ', ' ', '/', ' ', ' ', '/', ' ', ' ', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 3,	/* MDATN */
/* 00359 */ HB_P_LINEOFFSET, 29,	/* 43 */
	HB_P_PUSHSYMNEAR, 14,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 4,	/* MRESP */
/* 00370 */ HB_P_LINEOFFSET, 30,	/* 44 */
	HB_P_PUSHSYMNEAR, 14,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 5,	/* MIND */
/* 00381 */ HB_P_LINEOFFSET, 31,	/* 45 */
	HB_P_PUSHSYMNEAR, 14,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 16,	/* 16 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 6,	/* MGUIA */
/* 00392 */ HB_P_LINEOFFSET, 32,	/* 46 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CPF */
	HB_P_POPVARIABLE, 4, 0,	/* MCPF */
/* 00401 */ HB_P_LINEOFFSET, 33,	/* 47 */
	HB_P_PUSHSYMNEAR, 18,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 41,	/* 41 */
	'P', 'r', 'e', 'e', 'n', 'c', 'h', 'a', ' ', 'o', ' ', 'C', 'a', 'm', 'p', 'o', ' ', 'o', 'u', ' ', 'T', 'e', 'c', 'l', 'e', ' ', '<', 'E', 'S', 'C', '>', ' ', 'R', 'e', 't', 'o', 'r', 'n', 'a', 'r', 0, 
	HB_P_DOSHORT, 1,
/* 00451 */ HB_P_LINEOFFSET, 34,	/* 48 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 19,	/* REGISTRO */
	HB_P_POPVARIABLE, 1, 0,	/* MREG */
/* 00460 */ HB_P_LINEOFFSET, 35,	/* 49 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 20,	/* CODCONV */
	HB_P_POPVARIABLE, 3, 0,	/* MCCONV */
/* 00469 */ HB_P_LINEOFFSET, 36,	/* 50 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 21,	/* NOME */
	HB_P_POPVARIABLE, 2, 0,	/* MNOME */
/* 00478 */ HB_P_LINEOFFSET, 38,	/* 52 */
	HB_P_PUSHSYMNEAR, 22,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
/* 00487 */ HB_P_LINEOFFSET, 39,	/* 53 */
	HB_P_PUSHSYMNEAR, 23,	/* DISPBOX */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 3, 0,	/* 3*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 3, 0,	/* 3*/
	HB_P_PUSHLOCALNEAR, 19,	/* CBA */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 5,
/* 00510 */ HB_P_LINEOFFSET, 40,	/* 54 */
	HB_P_PUSHSYMNEAR, 22,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00518 */ HB_P_LINEOFFSET, 41,	/* 55 */
	HB_P_PUSHSYMNEAR, 24,	/* SCROLL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 19,	/* CBA */
	HB_P_DOSHORT, 4,
	HB_P_PUSHSYMNEAR, 25,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_DOSHORT, 2,
/* 00551 */ HB_P_LINEOFFSET, 42,	/* 56 */
	HB_P_PUSHSYMNEAR, 26,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 27,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'R', 'e', 'g', '.', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00581 */ HB_P_LINEOFFSET, 43,	/* 57 */
	HB_P_PUSHSYMNEAR, 26,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 15, 0,	/* 15*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 27,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'N', 'o', 'm', 'e', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00611 */ HB_P_LINEOFFSET, 44,	/* 58 */
	HB_P_PUSHSYMNEAR, 26,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 58, 0,	/* 58*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 27,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'I', 'd', 'a', 'd', 'e', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00642 */ HB_P_LINEOFFSET, 45,	/* 59 */
	HB_P_PUSHSYMNEAR, 26,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 27,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'C', 'o', 'n', 'v', 'e', 'n', 'i', 'o', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00676 */ HB_P_LINEOFFSET, 46,	/* 60 */
	HB_P_PUSHSYMNEAR, 26,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 44, 0,	/* 44*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 27,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 14,	/* 14 */
	'E', 's', 't', 'a', 'd', 'o', ' ', 'C', 'i', 'v', 'i', 'l', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00714 */ HB_P_LINEOFFSET, 47,	/* 61 */
	HB_P_PUSHSYMNEAR, 22,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
/* 00723 */ HB_P_LINEOFFSET, 48,	/* 62 */
	HB_P_PUSHSYMNEAR, 26,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 8, 0,	/* 8*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 27,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* MREG */
	HB_P_DOSHORT, 1,
/* 00748 */ HB_P_LINEOFFSET, 49,	/* 63 */
	HB_P_PUSHSYMNEAR, 26,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 21, 0,	/* 21*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 27,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 2, 0,	/* MNOME */
	HB_P_DOSHORT, 1,
/* 00773 */ HB_P_LINEOFFSET, 50,	/* 64 */
	HB_P_PUSHSYMNEAR, 26,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 65, 0,	/* 65*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 27,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 28,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 29,	/* INT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 30,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 31,	/* DATANS */
	HB_P_MINUS,
	HB_P_PUSHINT, 109, 1,	/* 365 */
	HB_P_DIVIDE,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_DOSHORT, 1,
/* 00821 */ HB_P_LINEOFFSET, 51,	/* 65 */
	HB_P_PUSHSYMNEAR, 26,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 12, 0,	/* 12*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 27,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 32, 0,	/* MRSOC */
	HB_P_DOSHORT, 1,
/* 00846 */ HB_P_LINEOFFSET, 52,	/* 66 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 33,	/* ESTCIVIL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'C', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 36,	/* 36 (abs: 00893) */
/* 00859 */ HB_P_LINEOFFSET, 53,	/* 67 */
	HB_P_PUSHSYMNEAR, 26,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 58, 0,	/* 58*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 27,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'a', 's', 'a', 'd', 'a', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 172, 0,	/* 172 (abs: 01062) */
/* 00893 */ HB_P_LINEOFFSET, 54,	/* 68 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 33,	/* ESTCIVIL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 37,	/* 37 (abs: 00941) */
/* 00906 */ HB_P_LINEOFFSET, 55,	/* 69 */
	HB_P_PUSHSYMNEAR, 26,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 58, 0,	/* 58*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 27,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'S', 'o', 'l', 't', 'e', 'i', 'r', 'a', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMPNEAR, 123,	/* 123 (abs: 01062) */
/* 00941 */ HB_P_LINEOFFSET, 56,	/* 70 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 33,	/* ESTCIVIL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'D', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 39,	/* 39 (abs: 00991) */
/* 00954 */ HB_P_LINEOFFSET, 57,	/* 71 */
	HB_P_PUSHSYMNEAR, 26,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 58, 0,	/* 58*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 27,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'D', 'i', 'v', 'o', 'r', 'c', 'i', 'a', 'd', 'a', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMPNEAR, 73,	/* 73 (abs: 01062) */
/* 00991 */ HB_P_LINEOFFSET, 58,	/* 72 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 33,	/* ESTCIVIL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'V', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 34,	/* 34 (abs: 01036) */
/* 01004 */ HB_P_LINEOFFSET, 59,	/* 73 */
	HB_P_PUSHSYMNEAR, 26,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 58, 0,	/* 58*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 27,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'V', 'i', 'u', 'v', 'a', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMPNEAR, 28,	/* 28 (abs: 01062) */
/* 01036 */ HB_P_LINEOFFSET, 61,	/* 75 */
	HB_P_PUSHSYMNEAR, 26,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 58, 0,	/* 58*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 27,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_DOSHORT, 1,
/* 01062 */ HB_P_LINEOFFSET, 64,	/* 78 */
	HB_P_PUSHSYMNEAR, 22,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 01070 */ HB_P_LINEOFFSET, 65,	/* 79 */
	HB_P_LOCALNEARSETINT, 10, 0, 0,	/* OPCAOHIS 0*/
/* 01076 */ HB_P_LINEOFFSET, 66,	/* 80 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 34,	/* ULT_MEST1 */
	HB_P_POPLOCALNEAR, 29,	/* MULT_MEST1 */
/* 01084 */ HB_P_LINEOFFSET, 67,	/* 81 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 35,	/* ULT_MEST2 */
	HB_P_POPLOCALNEAR, 32,	/* MULT_MEST2 */
/* 01092 */ HB_P_LINEOFFSET, 68,	/* 82 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 36,	/* ULT_MEST3 */
	HB_P_POPLOCALNEAR, 35,	/* MULT_MEST3 */
/* 01100 */ HB_P_LINEOFFSET, 69,	/* 83 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 37,	/* ULT_MEST4 */
	HB_P_POPLOCALNEAR, 38,	/* MULT_MEST4 */
/* 01108 */ HB_P_LINEOFFSET, 70,	/* 84 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 38,	/* ULT_MEST5 */
	HB_P_POPLOCALNEAR, 41,	/* MULT_MEST5 */
/* 01116 */ HB_P_LINEOFFSET, 71,	/* 85 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 39,	/* PRO_NASC1 */
	HB_P_POPLOCALNEAR, 30,	/* MPRO_NASC1 */
/* 01124 */ HB_P_LINEOFFSET, 72,	/* 86 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 40,	/* PRO_NASC2 */
	HB_P_POPLOCALNEAR, 33,	/* MPRO_NASC2 */
/* 01132 */ HB_P_LINEOFFSET, 73,	/* 87 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 41,	/* PRO_NASC3 */
	HB_P_POPLOCALNEAR, 36,	/* MPRO_NASC3 */
/* 01140 */ HB_P_LINEOFFSET, 74,	/* 88 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 42,	/* PRO_NASC4 */
	HB_P_POPLOCALNEAR, 39,	/* MPRO_NASC4 */
/* 01148 */ HB_P_LINEOFFSET, 75,	/* 89 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 43,	/* PRO_NASC5 */
	HB_P_POPLOCALNEAR, 42,	/* MPRO_NASC5 */
/* 01156 */ HB_P_LINEOFFSET, 76,	/* 90 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 44,	/* DAT_NASC1 */
	HB_P_POPLOCALNEAR, 31,	/* MDAT_NASC1 */
/* 01164 */ HB_P_LINEOFFSET, 77,	/* 91 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 45,	/* DAT_NASC2 */
	HB_P_POPLOCALNEAR, 34,	/* MDAT_NASC2 */
/* 01172 */ HB_P_LINEOFFSET, 78,	/* 92 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 46,	/* DAT_NASC3 */
	HB_P_POPLOCALNEAR, 37,	/* MDAT_NASC3 */
/* 01180 */ HB_P_LINEOFFSET, 79,	/* 93 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 47,	/* DAT_NASC4 */
	HB_P_POPLOCALNEAR, 40,	/* MDAT_NASC4 */
/* 01188 */ HB_P_LINEOFFSET, 80,	/* 94 */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 48,	/* DAT_NASC5 */
	HB_P_POPLOCALNEAR, 43,	/* MDAT_NASC5 */
/* 01196 */ HB_P_LINEOFFSET, 82,	/* 96 */
	HB_P_PUSHSYMNEAR, 18,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'U', 'S', 'E', ' ', '<', 0, 
	HB_P_PUSHVARIABLE, 49, 0,	/* SETESQ */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'>', ' ', '<', 0, 
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 50, 0,	/* SETDIR */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 32,	/* 32 */
	'>', ' ', ' ', '-', ' ', ' ', 'T', 'e', 'c', 'l', 'e', ' ', '<', 'E', 'N', 'T', 'E', 'R', '>', ' ', 'P', '/', 'C', 'o', 'n', 'f', 'i', 'r', 'm', 'a', 'r', 0, 
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
/* 01261 */ HB_P_LINEOFFSET, 83,	/* 97 */
	HB_P_PUSHSYMNEAR, 22,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
/* 01270 */ HB_P_LINEOFFSET, 84,	/* 98 */
	HB_P_PUSHSYMNEAR, 23,	/* DISPBOX */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 5, 0,	/* 5*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 5, 0,	/* 5*/
	HB_P_PUSHLOCALNEAR, 19,	/* CBA */
	HB_P_ONE,
	HB_P_DOSHORT, 5,
/* 01292 */ HB_P_LINEOFFSET, 85,	/* 99 */
	HB_P_PUSHSYMNEAR, 22,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 01300 */ HB_P_LINEOFFSET, 86,	/* 100 */
	HB_P_PUSHSYMNEAR, 51,	/* __ATPROMPT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 4, 0,	/* 4*/
	HB_P_PUSHLOCALNEAR, 17,	/* CCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHSTRSHORT, 18,	/* 18 */
	' ', 'R', 'e', 's', 'u', 'm', 'o', ' ', 'A', 'd', 'm', 'i', 's', 's', 'a', 'o', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 5,
/* 01339 */ HB_P_LINEOFFSET, 87,	/* 101 */
	HB_P_PUSHSYMNEAR, 51,	/* __ATPROMPT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 4, 0,	/* 4*/
	HB_P_PUSHSYMNEAR, 52,	/* COL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHSTRSHORT, 22,	/* 22 */
	' ', 'E', 'n', 't', 'r', 'e', 'v', 'i', 's', 't', 'a', ' ', 'A', 'd', 'm', 'i', 's', 's', 'a', 'o', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 5,
/* 01385 */ HB_P_LINEOFFSET, 88,	/* 102 */
	HB_P_PUSHSYMNEAR, 51,	/* __ATPROMPT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 4, 0,	/* 4*/
	HB_P_PUSHSYMNEAR, 52,	/* COL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	' ', 'R', 'e', 's', 'u', 'm', 'o', ' ', 'A', 'v', 'a', 'l', 'i', 'a', 'c', 'a', 'o', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 5,
/* 01428 */ HB_P_LINEOFFSET, 89,	/* 103 */
	HB_P_PUSHSYMNEAR, 51,	/* __ATPROMPT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 4, 0,	/* 4*/
	HB_P_PUSHSYMNEAR, 52,	/* COL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHSTRSHORT, 22,	/* 22 */
	' ', 'E', 'v', 'o', 'l', 'u', 'c', 'a', 'o', ' ', 'T', 'r', 'a', 't', 'a', 'm', 'e', 'n', 't', 'o', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 5,
/* 01474 */ HB_P_LINEOFFSET, 90,	/* 104 */
	HB_P_PUSHSYMNEAR, 51,	/* __ATPROMPT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* LCI */
	HB_P_ADDINT, 4, 0,	/* 4*/
	HB_P_PUSHSYMNEAR, 52,	/* COL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	' ', 'F', 'i', 'm', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 5,
/* 01504 */ HB_P_LINEOFFSET, 91,	/* 105 */
	HB_P_PUSHSYMNEAR, 53,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 31,	/* 31 */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'O', 'N', 0, 
	HB_P_DOSHORT, 2,
/* 01518 */ HB_P_LINEOFFSET, 92,	/* 106 */
	HB_P_PUSHSYMNEAR, 54,	/* __MENUTO */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 28, 0,	/* 28 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	10, 0,	/* OPCAOHIS */
	HB_P_PUSHSYMNEAR, 55,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 01545) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 01550) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'o', 'p', 'c', 'a', 'o', 'h', 'i', 's', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 10,	/* OPCAOHIS */
/* 01566 */ HB_P_LINEOFFSET, 93,	/* 107 */
	HB_P_PUSHSYMNEAR, 56,	/* SAVESCREEN */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 11,	/* MTELA */
/* 01581 */ HB_P_LINEOFFSET, 94,	/* 108 */
	HB_P_PUSHSYMNEAR, 57,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 01602) */
/* 01593 */ HB_P_LINEOFFSET, 95,	/* 109 */
	HB_P_LOCALNEARSETINT, 10, 7, 0,	/* OPCAOHIS 7*/
	HB_P_JUMP, 109, 254,	/* -403 (abs: 01196) */
/* 01602 */ HB_P_LINEOFFSET, 99,	/* 113 */
	HB_P_PUSHSYMNEAR, 58,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'l', 'i', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 59,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 01621 */ HB_P_LINEOFFSET, 102,	/* 116 */
	HB_P_PUSHLOCALNEAR, 10,	/* OPCAOHIS */
	HB_P_ONE,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 16,	/* 16 (abs: 01643) */
/* 01629 */ HB_P_LINEOFFSET, 103,	/* 117 */
	HB_P_PUSHSYMNEAR, 60,	/* HISTORICO1 */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 19,	/* REGISTRO */
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 68, 254,	/* -444 (abs: 01196) */
/* 01643 */ HB_P_LINEOFFSET, 104,	/* 118 */
	HB_P_PUSHLOCALNEAR, 10,	/* OPCAOHIS */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 16,	/* 16 (abs: 01666) */
/* 01652 */ HB_P_LINEOFFSET, 105,	/* 119 */
	HB_P_PUSHSYMNEAR, 61,	/* HISTORICO2 */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 19,	/* REGISTRO */
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 45, 254,	/* -467 (abs: 01196) */
/* 01666 */ HB_P_LINEOFFSET, 106,	/* 120 */
	HB_P_PUSHLOCALNEAR, 10,	/* OPCAOHIS */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 16,	/* 16 (abs: 01689) */
/* 01675 */ HB_P_LINEOFFSET, 107,	/* 121 */
	HB_P_PUSHSYMNEAR, 62,	/* HISTORICO3 */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 19,	/* REGISTRO */
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 22, 254,	/* -490 (abs: 01196) */
/* 01689 */ HB_P_LINEOFFSET, 108,	/* 122 */
	HB_P_PUSHLOCALNEAR, 10,	/* OPCAOHIS */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 16,	/* 16 (abs: 01712) */
/* 01698 */ HB_P_LINEOFFSET, 109,	/* 123 */
	HB_P_PUSHSYMNEAR, 63,	/* HISTORICO4 */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 19,	/* REGISTRO */
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 255, 253,	/* -513 (abs: 01196) */
/* 01712 */ HB_P_LINEOFFSET, 110,	/* 124 */
	HB_P_PUSHLOCALNEAR, 10,	/* OPCAOHIS */
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 245, 253,	/* -523 (abs: 01196) */
/* 01722 */ HB_P_LINEOFFSET, 111,	/* 125 */
	HB_P_PUSHSYMNEAR, 53,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 31,	/* 31 */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'O', 'N', 0, 
	HB_P_DOSHORT, 2,
/* 01736 */ HB_P_LINEOFFSET, 112,	/* 126 */
	HB_P_PUSHSYMNEAR, 64,	/* OP_SIMNAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_PUSHSTRSHORT, 25,	/* 25 */
	'C', 'o', 'n', 'f', 'i', 'r', 'm', 'a', ' ', 'C', 'o', 'n', 's', 'u', 'l', 't', 'a', ' ', '[', 'S', '/', 'n', ']', ':', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 13,	/* OPCAO */
/* 01776 */ HB_P_LINEOFFSET, 113,	/* 127 */
	HB_P_PUSHLOCALNEAR, 13,	/* OPCAO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 160, 1,	/* 416 (abs: 02201) */
/* 01788 */ HB_P_LINEOFFSET, 114,	/* 128 */
	HB_P_PUSHVARIABLE, 10, 0,	/* MCONSULTA */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'C', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 211, 0,	/* 211 (abs: 02009) */
/* 01801 */ HB_P_LINEOFFSET, 116,	/* 130 */
	HB_P_PUSHSYMNEAR, 58,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'l', 'i', 0, 
	HB_P_DOSHORT, 1,
/* 01814 */ HB_P_LINEOFFSET, 118,	/* 132 */
	HB_P_PUSHSYMNEAR, 65,	/* BLOQREG */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01821 */ HB_P_LINEOFFSET, 119,	/* 133 */
	HB_P_PUSHVARIABLE, 66, 0,	/* MDATA */
	HB_P_PUSHSYMNEAR, 16,	/* CLI */
	HB_P_POPALIASEDFIELDNEAR, 67,	/* DATAULT */
/* 01830 */ HB_P_LINEOFFSET, 120,	/* 134 */
	HB_P_PUSHSYMNEAR, 68,	/* DBCOMMIT */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01837 */ HB_P_LINEOFFSET, 121,	/* 135 */
	HB_P_PUSHSYMNEAR, 69,	/* DBUNLOCK */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01844 */ HB_P_LINEOFFSET, 123,	/* 137 */
	HB_P_PUSHSYMNEAR, 58,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'c', 'o', 'n', 't', 'r', 0, 
	HB_P_DOSHORT, 1,
/* 01859 */ HB_P_LINEOFFSET, 125,	/* 139 */
	HB_P_PUSHSYMNEAR, 70,	/* ADIREG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPFALSENEAR, 92,	/* 92 (abs: 01958) */
/* 01868 */ HB_P_LINEOFFSET, 126,	/* 140 */
	HB_P_PUSHVARIABLE, 66, 0,	/* MDATA */
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 72,	/* DATACONS */
/* 01877 */ HB_P_LINEOFFSET, 127,	/* 141 */
	HB_P_PUSHVARIABLE, 2, 0,	/* MNOME */
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 73,	/* CADNOME */
/* 01886 */ HB_P_LINEOFFSET, 128,	/* 142 */
	HB_P_PUSHVARIABLE, 1, 0,	/* MREG */
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 19,	/* REGISTRO */
/* 01895 */ HB_P_LINEOFFSET, 129,	/* 143 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'C', 0, 
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 74,	/* SITUACAO */
/* 01905 */ HB_P_LINEOFFSET, 130,	/* 144 */
	HB_P_PUSHVARIABLE, 3, 0,	/* MCCONV */
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 20,	/* CODCONV */
/* 01914 */ HB_P_LINEOFFSET, 131,	/* 145 */
	HB_P_PUSHVARIABLE, 75, 0,	/* MMOD */
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 76,	/* MODALIDADE */
/* 01923 */ HB_P_LINEOFFSET, 132,	/* 146 */
	HB_P_PUSHVARIABLE, 77, 0,	/* MVALOR */
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 78,	/* VALOR */
/* 01932 */ HB_P_LINEOFFSET, 133,	/* 147 */
	HB_P_PUSHVARIABLE, 79, 0,	/* MRECIB */
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 80,	/* RECIBO */
/* 01941 */ HB_P_LINEOFFSET, 134,	/* 148 */
	HB_P_PUSHSYMNEAR, 68,	/* DBCOMMIT */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01948 */ HB_P_LINEOFFSET, 135,	/* 149 */
	HB_P_PUSHSYMNEAR, 69,	/* DBUNLOCK */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMP, 210, 0,	/* 210 (abs: 02165) */
/* 01958 */ HB_P_LINEOFFSET, 137,	/* 151 */
	HB_P_PUSHSYMNEAR, 81,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 39,	/* 39 */
	'N', 'a', 'o', ' ', 'f', 'o', 'i', ' ', 'p', 'o', 's', 's', 'i', 'v', 'e', 'l', ' ', 'a', 'c', 'e', 's', 's', 'a', 'r', ' ', 'o', ' ', 'A', 'r', 'q', 'u', 'i', 'v', 'o', ' ', '!', '!', '!', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 214, 252,	/* -810 (abs: 01196) */
/* 02009 */ HB_P_LINEOFFSET, 142,	/* 156 */
	HB_P_PUSHSYMNEAR, 58,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'c', 'o', 'n', 't', 'r', 0, 
	HB_P_DOSHORT, 1,
/* 02024 */ HB_P_LINEOFFSET, 144,	/* 158 */
	HB_P_PUSHSYMNEAR, 70,	/* ADIREG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPFALSENEAR, 83,	/* 83 (abs: 02114) */
/* 02033 */ HB_P_LINEOFFSET, 145,	/* 159 */
	HB_P_PUSHVARIABLE, 66, 0,	/* MDATA */
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 72,	/* DATACONS */
/* 02042 */ HB_P_LINEOFFSET, 146,	/* 160 */
	HB_P_PUSHVARIABLE, 2, 0,	/* MNOME */
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 73,	/* CADNOME */
/* 02051 */ HB_P_LINEOFFSET, 147,	/* 161 */
	HB_P_PUSHVARIABLE, 1, 0,	/* MREG */
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 19,	/* REGISTRO */
/* 02060 */ HB_P_LINEOFFSET, 148,	/* 162 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'R', 0, 
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 74,	/* SITUACAO */
/* 02070 */ HB_P_LINEOFFSET, 149,	/* 163 */
	HB_P_PUSHVARIABLE, 3, 0,	/* MCCONV */
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 20,	/* CODCONV */
/* 02079 */ HB_P_LINEOFFSET, 150,	/* 164 */
	HB_P_PUSHVARIABLE, 75, 0,	/* MMOD */
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 76,	/* MODALIDADE */
/* 02088 */ HB_P_LINEOFFSET, 151,	/* 165 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_PUSHSYMNEAR, 71,	/* CONTR */
	HB_P_POPALIASEDFIELDNEAR, 80,	/* RECIBO */
/* 02098 */ HB_P_LINEOFFSET, 152,	/* 166 */
	HB_P_PUSHSYMNEAR, 68,	/* DBCOMMIT */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02105 */ HB_P_LINEOFFSET, 153,	/* 167 */
	HB_P_PUSHSYMNEAR, 69,	/* DBUNLOCK */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMPNEAR, 53,	/* 53 (abs: 02165) */
/* 02114 */ HB_P_LINEOFFSET, 155,	/* 169 */
	HB_P_PUSHSYMNEAR, 81,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 39,	/* 39 */
	'N', 'a', 'o', ' ', 'f', 'o', 'i', ' ', 'p', 'o', 's', 's', 'i', 'v', 'e', 'l', ' ', 'a', 'c', 'e', 's', 's', 'a', 'r', ' ', 'o', ' ', 'A', 'r', 'q', 'u', 'i', 'v', 'o', ' ', '!', '!', '!', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 58, 252,	/* -966 (abs: 01196) */
/* 02165 */ HB_P_LINEOFFSET, 159,	/* 173 */
	HB_P_PUSHSYMNEAR, 82,	/* RELATORI */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 79, 0,	/* MRECIB */
	HB_P_DOSHORT, 1,
/* 02175 */ HB_P_LINEOFFSET, 160,	/* 174 */
	HB_P_PUSHSYMNEAR, 83,	/* SMED700 */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02182 */ HB_P_LINEOFFSET, 161,	/* 175 */
	HB_P_PUSHSYMNEAR, 84,	/* DBUNLOCKALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02189 */ HB_P_LINEOFFSET, 162,	/* 176 */
	HB_P_PUSHSYMNEAR, 85,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02196 */ HB_P_LINEOFFSET, 163,	/* 177 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 02201 */ HB_P_LINEOFFSET, 165,	/* 179 */
	HB_P_PUSHLOCALNEAR, 13,	/* OPCAO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 11,	/* 11 (abs: 02222) */
	HB_P_PUSHSYMNEAR, 57,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 21,	/* 21 (abs: 02243) */
/* 02224 */ HB_P_LINEOFFSET, 166,	/* 180 */
	HB_P_PUSHSYMNEAR, 84,	/* DBUNLOCKALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02231 */ HB_P_LINEOFFSET, 167,	/* 181 */
	HB_P_PUSHSYMNEAR, 85,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02238 */ HB_P_LINEOFFSET, 168,	/* 182 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMP, 233, 251,	/* -1047 (abs: 01196) */
	HB_P_ENDPROC
/* 02247 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( DATA_PRO )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 2,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 194, 0,	/* 194 */
	HB_P_PUSHSYMNEAR, 87,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* MDT */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 10,	/* 10 (abs: 00023) */
/* 00015 */ HB_P_LINEOFFSET, 1,	/* 195 */
	HB_P_PUSHLOCALNEAR, 1,	/* MDT */
	HB_P_POPLOCALNEAR, 2,	/* MPRO */
	HB_P_JUMPNEAR, 11,	/* 11 (abs: 00032) */
/* 00023 */ HB_P_LINEOFFSET, 3,	/* 197 */
	HB_P_PUSHLOCALNEAR, 1,	/* MDT */
	HB_P_ADDINT, 14, 1,	/* 270*/
	HB_P_POPLOCALNEAR, 2,	/* MPRO */
/* 00032 */ HB_P_LINEOFFSET, 5,	/* 199 */
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00037 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

